### ISSUE TITLE
Error running Demo

### ISSUE THREAD

**Issue by Tikam02** [MaybeShewill-CV/CRNN_Tensorflow#101]
File "tools/test_shadownet.py", line 19, in <module>
    from local_utils import data_utils
ModuleNotFoundError: No module named 'local_utils'

**Comment by vinayakkailas** [comment]
you need to set the root directory CRNN_Tensorflow in python path or add a line like this in your scipt at the top before importing other folders

import sys
sys.path.append('/home/ubuntu/vinayak/CRNN_Tensorflow')

change path accordingly.
