### ISSUE TITLE
model/shadownet error

### ISSUE THREAD

**Issue by Tikam02** [MaybeShewill-CV/CRNN_Tensorflow#102]
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model/shadownet/shadownet_2017-09-29-19-16-33.ckpt-39999
	 [[Node: save/RestoreV2_23 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_23/tensor_names, save/RestoreV2_23/shape_and_slices)]]

**Comment by vinayakkailas** [comment]
current repo doesnt have the weights you have mentioned in the script. Try changing the weight name to shadownet_2017-10-17-11-47-46.ckpt-199999
