### ISSUE TITLE
Code is not importing crnn_model

### ISSUE THREAD

**Issue by Tikam02** [MaybeShewill-CV/CRNN_Tensorflow#103]
~/ML/CRNN_Tensorflow-master$ python tools/demo_shadownet.py --image_path data/test_images/test_01.jpg --weights_path model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999.meta
Traceback (most recent call last):
  File "tools/demo_shadownet.py", line 22, in <module>
    from crnn_model import crnn_model
ModuleNotFoundError: No module named 'crnn_model'

**Comment by vinayakkailas** [comment]
Either add the project path to PYTHONPATH or include this line in your code

import sys
sys.path.append('/home/ec2-user/vinayak/CRNN_Tensorflow') //change path accordingly
