### ISSUE TITLE
Some problems about you code.

### ISSUE THREAD

**Issue by Polaris-SDU** [MaybeShewill-CV/CRNN_Tensorflow#104]
Thanks for your excellent work at first. Your code is elegant and exquisite. But i find some lines that i can't understand. In CRNN_Tensorflow/crnn_model/cnn_basenet.py, we can see you use "SAME padding" in conv2d() by default; I also find  you use conv7 = self.conv2d(inputdata=max_pool6, out_channel=512, kernel_size=2, stride=[2, 1], use_bias=False, name='conv7') in your CRNN_Tensorflow/crnn_model/crnn_model.py
That means you use "SAME padding" in the last convlution layer. But i see #maps:512,k:2x2,s:1,p:0 in CRNN paper. that means paper author use "VALID padding" in the last convolution layer.The finally output dimension should Nx1x24x512(NHWC). 
Could you help me solve this problem?Thanks.

**Comment by Polaris-SDU** [comment]
Thanks for your reply. I think you are right about the set of stride in the last convolution layer.
My question is why you set the padding to "SAME padding" in the last conv layer. Because i see paper author adopt p:0 (no padding) in the last conv layer. So i think maybe conv7 = self.conv2d(inputdata=max_pool6, out_channel=512, kernel_size=2, padding="VALID",stride=[2, 1], use_bias=False, name='conv7')  is preferable.

**Comment by Polaris-SDU** [comment]
知道啦，谢谢😄(刚才看你的个人简介，发现大佬是百度的工程师，早知道就用汉语交流了)

**Comment by MaybeShewill-CV** [comment]
@Polaris-SDU ........没事儿 多交流

**Comment by barhaiya11** [comment]
Key shadow/batch_normalization/beta not found in checkpoint
this error comes when i am testing the given data.Please help me to solve this.
![screenshot 205](https://user-images.githubusercontent.com/41964045/52994344-3f3b2180-343d-11e9-99d2-19ec54739db0.png)
