### ISSUE TITLE
tfrecord生成和读取

### ISSUE THREAD

**Issue by dehaisea** [MaybeShewill-CV/CRNN_Tensorflow#106]
我按照readme描述的格式保存的图片，并且成功生成了tfrecord，但训练的时候还是没有成功读取图片，这是怎么回事呢？
![screenshot from 2018-06-28 20-57-48](https://user-images.githubusercontent.com/15978747/42030716-1e561b08-7b17-11e8-8840-158004a8c902.png)
![screenshot from 2018-06-28 20-58-06](https://user-images.githubusercontent.com/15978747/42030730-2725e1be-7b17-11e8-8d79-fd34877712a9.png)
![screenshot from 2018-06-28 20-58-26](https://user-images.githubusercontent.com/15978747/42030735-29459692-7b17-11e8-927c-3fd44cf100c2.png)
![screenshot from 2018-06-28 21-05-54](https://user-images.githubusercontent.com/15978747/42030738-2ad2825e-7b17-11e8-985d-0038d053ed69.png)

**Comment by keerchaokeai** [comment]
@dehaisea 您好，请问可以教下我tfrecord生成和读取，不胜感激
