### ISSUE TITLE
Test Model Accuracy is 0.73 on provided model?

### ISSUE THREAD

**Issue by LucyLu-LX** [MaybeShewill-CV/CRNN_Tensorflow#107]
I tried to run the test on the provided converted dataset following the 
`python tools/test_shadownet.py --dataset_dir data/ --weights_path model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999`
But the Test accuracy is kinda low, about 0.730922.
Is the number right?
Or I may have some bugs in the code, cause I made some changes and deployed it in Python 2.7

**Comment by MaybeShewill-CV** [comment]
@LucyLu-LX You can test the model on python 3.5 or later. I can not get your test accuracy on my enviroment.

**Comment by LucyLu-LX** [comment]
@MaybeShewill-CV 
我在Python3.5里面重新做了测试，完全用你提供的模型和数据集。
现在的正确率是0.88. 我想知道你的环境下正确率是多少？
因为我看你训练的log里，准确度很高在0.95以上，所以我就想确定一下，我复现的这个正确率是不是和你的相同。

**Comment by MaybeShewill-CV** [comment]
@LucyLu-LX Log里记录的是train数据的正确率，所以测试集上准确率低一些很正常。最近一直在忙别的工作，这个具体的实验数据我也记不太清楚了。但是大致上准确率在90%到93%之间。

**Comment by LucyLu-LX** [comment]
@MaybeShewill-CV 
Thanks a lot.

**Comment by tuananhbui89** [comment]
Hi @LucyLu-LX 
I have the same accuracy when running the test model (0.730922). So can you tell me how to improve the performance, or just running on python 3.5 environment?
