### ISSUE TITLE
How I use GPU?

### ISSUE THREAD

**Issue by kikoo321** [MaybeShewill-CV/CRNN_Tensorflow#110]
I'm using your code very well.
But, I'm stucked in using GPU.
I'm trying to follow tensorflow gpu guide but it makes bottleneck between cpu and gpu.
Could you explain more details which part of the code should I modify?

**Comment by MaybeShewill-CV** [comment]
@kikoo321 Sorry i don't get your point

**Comment by kikoo321** [comment]
Thanks for your reply.
I write the code 'tf.device('/gpu:0'):' but, the entire excution is more slower.
When I use only cpu, it takes 4 seconds each epoch.
But, when I use that code, it takes 50 seconds each epoch.
Also, some functions such as 'saver, Adadelta' are excuting in cpu.
I concluded that I misuse the 'tf.device' code.
So, I wonder where I put the 'tf.device('/gpu:0') or what code you use for using GPU?

**Comment by MaybeShewill-CV** [comment]
@kikoo321 You can use tf.ConfigProto(device_count={'GPU': 1}) to use gpu resources

**Comment by kikoo321** [comment]
![image](https://user-images.githubusercontent.com/35215075/42721872-fad5794a-877c-11e8-9057-ee56eebe5621.png)
I modify the code but,
![image](https://user-images.githubusercontent.com/35215075/42721885-2efa2f9a-877d-11e8-9c0e-b6cc61a53e7c.png)
I found that some functions are excuting on CPU.
I think that it makes some bottleneck.
Could you give me some advise?

**Comment by MaybeShewill-CV** [comment]
@kikoo321 The data feed pipline is executed on cpu if you are familiar with tf

**Comment by kikoo321** [comment]
Sorry i can't get your point.
Could you give me a detail?

**Comment by MaybeShewill-CV** [comment]
@kikoo321 You can go to the Tensorflow project page to check the data feed pipline

**Comment by kikoo321** [comment]
Thank you, I'll try it
