### ISSUE TITLE
关于多行字符识别

### ISSUE THREAD

**Issue by Polaris-SDU** [MaybeShewill-CV/CRNN_Tensorflow#111]
你好,请问一下如何利用你构建的CRNN模型进行多行字符识别? @MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@Polaris-SDU 你可已关注一下这篇论文 对于多行文字 这个模型就需要更大量的训练数据了,应该效果比较一般

**Comment by Polaris-SDU** [comment]
谢谢大佬的回复. CRNN这篇论文,我已经拜读过啦. 我现在主要疑惑的是:如果训练集图片有多行/多列字符的话,如何使用网络来进行预测?  需不要要CTPN ?  小白硕一枚,期待大佬能够指引一条明路~~~
@MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@Polaris-SDU 这个模型需要实现的文字定位

**Comment by MaybeShewill-CV** [comment]
@Polaris-SDU 这个模型需要事先的文字定位

**Comment by Polaris-SDU** [comment]
好的,谢谢~
