### ISSUE TITLE
Premature end of JPEG file

### ISSUE THREAD

**Issue by jetjodh** [MaybeShewill-CV/CRNN_Tensorflow#112]
C:\Users\jetjo\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Initialize the dataset provider ......
Premature end of JPEG file
What does this mean and this process is taking too long.

**Comment by MaybeShewill-CV** [comment]
@jetjodh Check your image data

**Comment by jetjodh** [comment]
I downloaded the 90K image data set and am using that only. And ideally how much time should it take to convert into tf records?

**Comment by MaybeShewill-CV** [comment]
@jetjodh It may take a couple of hours
