### ISSUE TITLE
problems   of making   tfrecord   format

### ISSUE THREAD

**Issue by ccnankai** [MaybeShewill-CV/CRNN_Tensorflow#113]
![xx](https://user-images.githubusercontent.com/33537489/43056791-cf3149ae-8e70-11e8-9b37-7428cc77bd8b.jpg)
请问我哪里弄错了？

**Comment by MaybeShewill-CV** [comment]
@ccnankai 参数写错了吧

**Comment by ccnankai** [comment]
@MaybeShewill-CV
没写错啊  就--dataset_dir  和 --save_dir 
（生成tfrecords和训练）请问是用主分支 还是chinese分支啊？

**Comment by ccnankai** [comment]
python tools/write_text_features.py     --dataset_dir  onerow/   --save_dir  tfrecords_dir

**Comment by MaybeShewill-CV** [comment]
@ccnankai 主分支

**Comment by ccnankai** [comment]
Traceback (most recent call last):
  File "tools/write_text_features.py", line 101, in <module>
    write_features(dataset_dir=args.dataset_dir, save_dir=args.save_dir)
  File "tools/write_text_features.py", line 50, in write_features
    normalization=None)
  File "/home/yanfa/songwendong/ocr/recognition/CRNN_Tensorflow-master/data_provider/data_provider.py", line 172, in __init__
    shuffle=shuffle, normalization=normalization)
  File "/home/yanfa/songwendong/ocr/recognition/CRNN_Tensorflow-master/data_provider/data_provider.py", line 56, in __init__
    self._epoch_imagenames, self._epoch_labels = self.shuffle_images_labels(self._epoch_imagenames,self._epoch_labels)
TypeError: shuffle_images_labels() missing 1 required positional argument: 'imagenames'
@MaybeShewill-CV   一直这个错误，疯了，我直接找找吧 。多谢多谢。

**Comment by MaybeShewill-CV** [comment]
@ccnankai .......主分支三个参数, chinese两个参数 你可以仔细看一下啊＝＝！　你用主分支需要三个参数啊,函数参数不对啊==!

**Comment by ccnankai** [comment]
@MaybeShewill-CV

知道了，多谢多谢
