### ISSUE TITLE
cnn_basenet.py 290行，为什么要用tf.identity? 

### ISSUE THREAD

**Issue by ccnankai** [MaybeShewill-CV/CRNN_Tensorflow#114]
ret = tf.layers.dense(inputs=inputdata, activation=lambda x: nl(x, name='output'), 其中nl=tf.identity 请问为什么要用tf.identity啊？求指点

**Comment by MaybeShewill-CV** [comment]
@ccnankai You may check tensorflow api https://www.tensorflow.org/api_docs/python/tf/identity. We use it to construct a op in the graph

**Comment by ccnankai** [comment]
@MaybeShewill-CV 
tf.identity是转换成tensor，但是activation=lambda x: nl(x, name='output')  一般activation不是 relu,tanh什么的吗？  那这句话的意思是没有任何activation function吧，不好意思，新手。

**Comment by ryanwcyin** [comment]
@ccnankai It's a high level api for other model to call, so the default activation is undefined. Keras is using a similar approach when implementing their fully connect layer. See [(keras.layers.Dense )](https://keras.io/layers/core/) for details. You can find the default activation function is None as well.

**Comment by ccnankai** [comment]
@ryanwcyin 
thank you very much
