### ISSUE TITLE
Decay Rate and Decay Steps for 50k steps vs 25k steps

### ISSUE THREAD

**Issue by burglarhobbit** [MaybeShewill-CV/CRNN_Tensorflow#116]
I'm training on textual data where the fine tuning part of the data comes in the last 20% of the steps. So I wanted to know that if the learning rate, decay rate and decay steps were enought for the model to be learnt with 90+ accuracy, in this scenario? 

I have these graphs of the learning rate curve:
[Graph1](https://www.google.com/search?ei=IRNcW_a0BoX4vgT_uLrAAw&q=0.1*0.1%5E%28x%2F10000%29&oq=0.1*0.1%5E%28x%2F10000%29&gs_l=psy-ab.3...7045932.7047310.0.7047501.2.2.0.0.0.0.461.461.4-1.1.0....0...1.1.64.psy-ab..1.0.0....0.4Yj1YIZqiLw)
[Graph2](https://www.google.com/search?ei=IRNcW_a0BoX4vgT_uLrAAw&q=0.1*0.09%5E%28x%2F12000%29&oq=0.1*0.09%5E%28x%2F12000%29&gs_l=psy-ab.3...4888.11265.0.11375.9.9.0.0.0.0.1083.3354.2-1j6-1j2.4.0....0...1.1.64.psy-ab..5.0.0....0.9ujyAAC4Drg)
[Graph3](https://www.google.com/search?ei=dy5cW7CdMYnxvgT077bQCQ&q=0.2*0.09%5E%28x%2F12000%29&oq=0.2*0.09%5E%28x%2F12000%29&gs_l=psy-ab.3..0i71k1l8.2228.2301.0.2481.2.2.0.0.0.0.0.0..0.0....0...1.1.64.psy-ab..2.0.0....0.Rhb3MrXDXOc)

which one would be more appropriate for this experiment?

**Comment by MaybeShewill-CV** [comment]
@burglarhobbit The repo has been updated you may test again:)
