### ISSUE TITLE
Meet some questions during training

### ISSUE THREAD

**Issue by Polaris-SDU** [MaybeShewill-CV/CRNN_Tensorflow#117]
你好, 我使用自己的数据集来训练CRNN network. (我的训练集有5989 classes, 共10498 张) 
我的数据集如下:
![2018-08-01 09-06-26](https://user-images.githubusercontent.com/34428575/43495916-2bd40ff4-956d-11e8-8aee-f87430d71ffb.png)

首先我调用 tools/establish_char_dict.py 生成我自己字典的3个映射文件：
1:  data/char_dict/char_dict.json； 
2:  data/char_dict/ord_2_index_map.json
3:  data/char_dict/index_2_ord_map.json

其次我调用 tools/write_text_tfrecords.py  成功生成TF_records 文件了

最后调用 tools/train_shadownet.py 开始训练.
![2018-08-01 09-05-51](https://user-images.githubusercontent.com/34428575/43495832-cefbd0d2-956c-11e8-9d9d-9e27562257b3.png)

1：准确率变为0 的情况下，cost仍然 持续下降. (试了几个比较小的学习率，还是这种情况)

希望大神能给点指导~~ 谢谢啦。 @MaybeShewill-CV

**Comment by Jackson-Kang** [comment]
You have to downgrade TF version to 1.3.0.

In my server, the speed of calculating loss dramatically decreased to 50 - 60 seconds with more than 1.4.0 versions.
I am currently using geforce 1080ti and it takes 3~4 seconds when calculating loss.

**Comment by Polaris-SDU** [comment]
Thanks for your reply.  I don't understand why accuracy becomes  to zero while cost descend.  I think the train accuracy should ascend while the cost descend.  (PS if you delete beam search during training, the training  becomes very fast.)

**Comment by Jackson-Kang** [comment]
Can I ask some questions?

What kind of language did you trained as input data?
Is it Chinese? If yes, how many labels exists in your custom dataset?

**Comment by Jackson-Kang** [comment]
One more thing, can I see some examples of your custom dataset?

**Comment by Polaris-SDU** [comment]
Yes. 
My training dataset  is composed of  Chinese character, Arabic numerals, punctuation and some special character  (such as $, ①).   My custom dataset has 5989 classes.

![00](https://user-images.githubusercontent.com/34428575/45461294-e13f3b00-b734-11e8-8b35-d48214b8fffe.jpg)

![000002](https://user-images.githubusercontent.com/34428575/45461134-dafc8f00-b733-11e8-91a2-2080d272e84b.jpg)

![000003](https://user-images.githubusercontent.com/34428575/45461137-dd5ee900-b733-11e8-9c21-93ae000ca01e.jpg)

![000004](https://user-images.githubusercontent.com/34428575/45461138-e059d980-b733-11e8-872d-771f6b7ef120.jpg)

![000005](https://user-images.githubusercontent.com/34428575/45461139-e2bc3380-b733-11e8-9853-cbea62d4e69f.jpg)

**Comment by Jackson-Kang** [comment]
Thanks for answering my question. Your answer will be a great help to me.
