### ISSUE TITLE
模型转成PB格式之后，无法import

### ISSUE THREAD

**Issue by Albertcc** [MaybeShewill-CV/CRNN_Tensorflow#120]
提示ValueError: Node 'shuffle_batch/TakeManySparseFromTensorsMap' expects to be colocated with unknown node  'shuffle_batch/AddSparseToTensorsMap'
这是什么问题？

**Comment by wdsd641417025** [comment]
能告诉我怎么转的pb文件嘛 不知道网络输出名称是什么
感谢

**Comment by MaybeShewill-CV** [comment]
@Albertcc The repo has been updated you may test again:)

**Comment by junshipeng** [comment]
I met the same problem,how to solve it?
