### ISSUE TITLE
Regarding number of examples and decay step for shadownet_2017-09-29-19-16-33.ckpt-39999

### ISSUE THREAD

**Issue by rohitsaluja22** [MaybeShewill-CV/CRNN_Tensorflow#124]
Hey @MaybeShewill-CV 
Thanks for sharing your code and model.
You have used C.TRAIN.LR_DECAY_STEPS = 10000 in shared code. Is the shard model shadownet_2017-09-29-19-16-33.ckpt-39999 trained with this decay step?

Also, it would be helpful if you can share the number of examples you used from synth text for shadownet_2017-09-29-19-16-33.ckpt-39999.

Should we keep the decay steps = 1 epoch in general or more?

**Comment by MaybeShewill-CV** [comment]
@rohitsaluja22 The repo has been updated you may test it again:)
