### ISSUE TITLE
exception occurred when use the newest version code to test

### ISSUE THREAD

**Issue by taojian1989** [MaybeShewill-CV/CRNN_Tensorflow#129]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [512,547] rhs shape= [512,37]

**Comment by MaybeShewill-CV** [comment]
@taojian1989 Check if the tensors are with same shape

**Comment by Hakan79** [comment]
Hi I am getting the same error

**Comment by Hakan79** [comment]
Also please change decoder = data_utils.TextFeatureIO() to data_utils.TextFeatureIO().reader in the demo_shadownet.py file.  The demo does not work like this.

**Comment by everdark** [comment]
Same here.
Running the line

```sh
PYTHONPATH=. python3 tools/test_shadownet.py --dataset_dir data/ --weights_path model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999
```

will give the error

```
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [512,547] rhs shape= [512,37]
         [[Node: save/Assign_16 = Assign[T=DT_FLOAT, _class=["loc:@shadow/LSTMLayers/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shadow/LSTMLayers/w, save/RestoreV2:16)]]
```

The same error was thrown for running 

```sh
PYTHONPATH=. python3 tools/demo_shadownet.py --image_path data/test_images/test_01.jpg --weights_path model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999
```

(I've changed the file the line `decoder = data_utils.TextFeatureIO()` to `decoder = data_utils.TextFeatureIO().reader`)

**Comment by mdbenito** [comment]
This should be fixed now

**Comment by mdbenito** [comment]
See #134 and #142 . @MaybeShewill-CV I think this issue can be closed now
