### ISSUE TITLE
SystemError: new style getargs format but argument is not a tuple. When running demo_shadownet.py

### ISSUE THREAD

**Issue by mmaka4** [MaybeShewill-CV/CRNN_Tensorflow#131]
python tools/demo_shadownet.py --image_path data/test_images/test_01.jpg --weights_path model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999

Traceback (most recent call last):
  File "tools/demo_shadownet.py", line 112, in <module>
    recognize(image_path=args.image_path, weights_path=args.weights_path)
  File "tools/demo_shadownet.py", line 56, in recognize
    image = cv2.resize(image, config.cfg.ARCH.INPUT_SIZE)
SystemError: new style getargs format but argument is not a tuple

**Comment by ryanwcyin** [comment]
can you open config.py? what's the value of '__C.ARCH.INPUT_SIZE' ?

**Comment by mmaka4** [comment]
The value of '__C.ARCH.INPUT_SIZE = (100, 32)'

**Comment by mmaka4** [comment]
Thanks a lot Brothers. The error disappear, it runs well now.

**Comment by mdbenito** [comment]
@MaybeShewill-CV This issue could be closed.
