### ISSUE TITLE
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [512,547] rhs shape= [512,37]

### ISSUE THREAD

**Issue by mmaka4** [MaybeShewill-CV/CRNN_Tensorflow#136]
When running test_shadownet.py
![error](https://user-images.githubusercontent.com/42118634/44839230-e84f4f00-ac46-11e8-8781-d6a32c1014e5.jpg)

**Comment by mdbenito** [comment]
You need to set the number of classes to 37 with `python tools/test_shadownet.py -c 37 ....`

**Comment by mmaka4** [comment]
@mdbenito I have already specified the number of classes as 37, but still produce the same error as above snippet.

**Comment by mmaka4** [comment]
I have already figured out the problem. From the test_shadownet.py change num_classes = None in to num_classes = 37. 
This Line:
def test_shadownet(dataset_dir: str, weights_path: str, is_vis: bool=False, is_recursive: bool=True, num_threads: int=4,num_classes: int=37):

**Comment by mdbenito** [comment]
The problem is actually with the call to test_shadownet(), because one positional argument was omitted, so the command line argument is never actually used. I'll submit a PR shortly addressing this

**Comment by mmaka4** [comment]
Thanks Brother. That will be great.
