### ISSUE TITLE
Should the project migrate into tensorflow v1.10?

### ISSUE THREAD

**Issue by ryanwcyin** [MaybeShewill-CV/CRNN_Tensorflow#147]
I know the project is working quite well under tf version 1.3.

However, should we migrate the project into latest tensorflow version? So it can cover more new features like tf.debugging.

I've cloned the project locally and run with tensorflow 1.10. Only a few functions need to change (saver.restore(), etc.)

**Comment by mdbenito** [comment]
You can generate your own dataset easily with any of a number of available tools. Just google "synthetic text generator ocr" and pick the project that best suits your requirements

**Comment by mdbenito** [comment]
I am also running a local branch with TF 1.10 using the data api and would definitely support this. However, we need to make sure that nothing breaks and @MaybeShewill-CV has to agree to it. I guess you could submit a PR and we can discuss there.

**Comment by mdbenito** [comment]
Done in PR #162 .

**Comment by MaybeShewill-CV** [comment]
@mdbenito Thanks a lot I will close it
