### ISSUE TITLE
char_dict.json 和 ord_map.json是什么意思，可以科普一下吗？

### ISSUE THREAD

**Issue by 10183308** [MaybeShewill-CV/CRNN_Tensorflow#156]
char_dict.json 和 ord_map.json是什么意思，可以科普一下吗？
制作的时候格式是什么样的？

谢谢，

**Comment by LJXLJXLJX** [comment]
@MaybeShewill-CV 
你好，为什么这里需要两个文件来维护映射关系？
比如在ord_map中有一个条目
0→30589
而在char_dict中对应条目为
30589→\u777d
为什么不直接在其中一个文件里面将映射关系建立为
0→\u777d

**Comment by MaybeShewill-CV** [comment]
@LJXLJXLJX 你那样建立是没有问题的 我这么建立是因为这两个文件我还有别的用处:)
