### ISSUE TITLE
@MaybeShewill-CV 不好意思，想问一下这个如何训练数字？如何区分英文字母大小写？如何可以的话，需要修改代码的哪一部分，我刚接触这一方面不太了解，可不可以具体说明一下，十分感谢！

### ISSUE THREAD

**Issue by LiuHuiyue666** [MaybeShewill-CV/CRNN_Tensorflow#157]
_Originally posted by @LiuHuiyue666 in https://github.com/MaybeShewill-CV/CRNN_Tensorflow/issues/154#issuecomment-422308735_

**Comment by MaybeShewill-CV** [comment]
@LiuHuiyue666 只需要用所有你想要识别的单个字符构建标签字典（关于标签字典可以在前面的问题中找到制作方法），然后利用你提供的训练数据进行训练就可以了

**Comment by LiuHuiyue666** [comment]
@MaybeShewill-CV 可以具体说一下吗，修改哪个文件，或者方便的话能否加我一下微信lhy131102

**Comment by MaybeShewill-CV** [comment]
@LiuHuiyue666 你可以切换到Chinese-debug-version然后在data/char_dict/文件夹下有English_char_dict.txt你需要照着这个文件自己构建一份自己的字典文件，然后用tools/establish_char_dict.py来生成两个字典json文件 然后再按照readme的步骤用你的训练数据进行训练

**Comment by LiuHuiyue666** [comment]
@MaybeShewill-CV 这个分支下的模型是用来识别中文的吗

**Comment by MaybeShewill-CV** [comment]
@LiuHuiyue666 那个分支功能并没有全部上传完整 因为一直没有时间整理那部分， 只是因为那个生成字典的工具没有放在主分支里面 所以怕你自己找不到。如果你自己会生成这个字典那你完全可以不用切换 直接使用主分支训练就可以了

**Comment by LiuHuiyue666** [comment]
嗯嗯，谢谢你

**Comment by LiuHuiyue666** [comment]
@MaybeShewill-CV 您好，可以提供一部分synth90k的子集吗，我下载之后解压所需空间太大。电脑内存不够
