### ISSUE TITLE
TypeError: batch() got an unexpected keyword argument 'drop_remainder

### ISSUE THREAD

**Issue by 10183308** [MaybeShewill-CV/CRNN_Tensorflow#166]
when I train the model ,error occur:

TypeError: batch() got an unexpected keyword argument 'drop_remainder

Could you help me ?

thank you very much.

**Comment by MaybeShewill-CV** [comment]
@10183308 please put more details here:)

**Comment by 10183308** [comment]
when I  train my model : error occur:

(anaconda3-5.2.0):~/ICDAR_Text_Rec/CRNN_Tensorflow$ python tools/train_shadownet.py --dataset_dir data/feature --chardict_dir data/dict
../.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Importing configuration global_configuration.config from .
Traceback (most recent call last):
  File "tools/train_shadownet.py", line 187, in <module>
    num_threads=args.num_threads)
  File "tools/train_shadownet.py", line 79, in train_shadownet
    input_images, input_labels, input_image_names = decoder.read_features(cfg, cfg.TRAIN.BATCH_SIZE, num_threads)
  File "../ICDAR_Text_Rec/CRNN_Tensorflow/local_utils/data_utils.py", line 223, in read_features
    dataset = dataset.batch(cfg.TRAIN.BATCH_SIZE, drop_remainder=True)
TypeError: batch() got an unexpected keyword argument 'drop_remainder'

**Comment by MaybeShewill-CV** [comment]
@10183308 what is your tensorflow version

**Comment by 10183308** [comment]
1.8.0

**Comment by 10183308** [comment]
may be the version need to update to 1.10

**Comment by MaybeShewill-CV** [comment]
@10183308 You may upgrade your tensorflow to fit this code or you can modify the code to fit the tf dataset api of your local version

**Comment by 10183308** [comment]
ok ,thank you very much.

**Comment by MaybeShewill-CV** [comment]
@10183308 You're welcome
