### ISSUE TITLE
关于输入尺寸

### ISSUE THREAD

**Issue by LiangHao92** [MaybeShewill-CV/CRNN_Tensorflow#169]
你好楼主，我看你的模型输入尺寸是固定的，那么对于不定长的字符图像都会resize到固定长度，那你训练集是怎么构造的呢？各种不定长的字符序列还是固定字长的字符序列，如果是固定字长的（比如10个字），那在实际测试中，只有两个字的文字行，resize后长宽比肯定会发生畸变，那么识别效果怎么样

**Comment by AssKicker0214** [comment]
你可以把图片按照缩放到高度合适的尺寸（长高等比例缩放），然后左右补空白一直到满足长度

**Comment by MaybeShewill-CV** [comment]
@LiangHao92 你可以通过补充空白的方式 就像@AssKicker0214说的

**Comment by ProgrammerYuan** [comment]
@MaybeShewill-CV 那要是长度过长的话就是上下补空白就可以么？还想请问一下这样的做法对于精确度是否会有比较大的影响？

**Comment by MaybeShewill-CV** [comment]
@ProgrammerYuan You may update the repo and test it:)
