### ISSUE TITLE
2017-10-17 github上面的cktp文件restore的时候报错

### ISSUE THREAD

**Issue by weizhenzhao** [MaybeShewill-CV/CRNN_Tensorflow#170]
Hi 哥哥
今天把那个CRNN_TensorFlow clone下来的时候，然后在PyCharm中运行那个
测试图片ocr的时候报错，是不是github上面那个模型不好使呀？需要自己训练呀？
![image](https://user-images.githubusercontent.com/13706689/47649990-d3952600-dbb9-11e8-98b1-4ab77236d268.png)
![image](https://user-images.githubusercontent.com/13706689/47650012-e7408c80-dbb9-11e8-84a3-44a88ef3e59d.png)
Thanks
WeiZhen

**Comment by MaybeShewill-CV** [comment]
@weizhenzhao 是的 那个模型和现在的代码不匹配 新模型我最近没有时间训练==！

**Comment by weizhenzhao** [comment]
thank you 哥哥 是不是把那个90的数据集下下，然后再run那个train 方法就可以啦？

**Comment by MaybeShewill-CV** [comment]
@weizhenzhao 嗯 你可以自己训练一个模型

**Comment by zhangheng12310** [comment]
@MaybeShewill-CV 
您好，按照您给出的training方法我重新训练了一个模型，可是加载模型的时候依然报错。
DataLossError (see above for traceback): Unable to open table file model/shadownet/shadownet_2018-10-30-18-13-27.ckpt-105.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

  请问有什么好的建议吗？？？

**Comment by MaybeShewill-CV** [comment]
@zhangheng12310 你的weights_path传错了 不要加后面的.data****** 你可以查查tensorflow ckpt文件的加载

**Comment by zhangheng12310** [comment]
@MaybeShewill-CV 
感谢您的耐心指导，我删除.data******之后，加载模型出现了新的错误：
InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,547]
	 [[Node: save/Assign_8 = Assign[T=DT_FLOAT, _class=["loc:@shadow/LSTMLayers/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](shadow/LSTMLayers/w, save/RestoreV2/_17)]]
我不明白是什么原因导致了这个错误，希望您不吝赐教，非常感谢！

**Comment by zhangheng12310** [comment]
@MaybeShewill-CV 
我是从90的数据集里随机选取一小部分作为我的数据集进行训练的，请问我该如何保持原始模型的37类英文类型呢？？？感谢您的赐教！

**Comment by weizhenzhao** [comment]
@MaybeShewill-CV 哥哥能问一下这个cuda和cudnn的版本具体是多少吗？
之前装那个cuda9.0 cudnn7.0.5的跑不起来

**Comment by stevenliy** [comment]
怎么样才能把github 的demo 跑起来？
