### ISSUE TITLE
About the basicLSTM cell

### ISSUE THREAD

**Issue by Alexander-flyer** [MaybeShewill-CV/CRNN_Tensorflow#175]
I have install dependence as the same version declared in "requirements.txt"
after try 

    python tools/demo_shadownet.py --image_path data/test_images/test_01.jpg --weights_path model/shadownet/shadownet_2017-09-29-19-16-33.ckpt-39999

an error occur 

    AttributeError: module 'tensorflow.contrib' has no attribute 'rnn_cell'

I have noticed that "tf.contrib.rnn_cell.BasicLSTMCell" been used
official document declaration on https://www.tensorflow.org/api_docs/python/tf/nn/rnn_cell/BasicLSTMCell

    Please use tf.nn.rnn_cell.LSTMCell instead.

so...if I change it to `tf.nn.rnn_cell.LSTMCell` ? or ?

**Comment by MaybeShewill-CV** [comment]
@Alexander-flyer You may upodate the repo and test again:)
