### ISSUE TITLE
train predicted label is error and train accuracy is low

### ISSUE THREAD

**Issue by garspace** [MaybeShewill-CV/CRNN_Tensorflow#176]
I found the predicted label is error when training CRNN , num_classes=len(char_dict)+1,  I do not know  how to deal with the problem @MaybeShewill-CV 
![c8192446-f379-44dc-aca3-fd99403e14ff](https://user-images.githubusercontent.com/12806623/48777144-c547af00-ed0c-11e8-9b01-bdeec90d39ab.png)

![d69f081d-ba25-44af-b14c-ad3e4bea02be](https://user-images.githubusercontent.com/12806623/48777845-a6e2b300-ed0e-11e8-87ce-bf9c6b32d835.png)

**Comment by xiaoaoran** [comment]
我测试的predicted label都是空的，不显示

**Comment by Antonio-hi** [comment]
@xiaoaoran @garspace 遇到了同样的问题，目前不知道问题出在哪里了，你们有解决办法吗？

**Comment by MaybeShewill-CV** [comment]
@garspace The repo has been updated you may test again:)

**Comment by duxiangkun** [comment]
@Antonio-hi @xiaoaoran 您好，我的predicted label也是空，请问您解决了吗

**Comment by Antonio-hi** [comment]
@duxiangkun  继续训练就行了，从log来看，一切正常，训练到一定程度便会学到词汇，前期需要比较漫长的训练过程，CRNN要想训练的快需要一些特别的训练技巧

**Comment by duxiangkun** [comment]
@Antonio-hi 训练开始loss很快到30左右，并在很长一段时间都是在20-35之间波动，这样是正常吗

**Comment by Antonio-hi** [comment]
这是正常的，请保持适当的学习率，例如1e-1继续训练，需等待较长时间

duxiangkun <notifications@github.com> 于2019年4月14日周日 下午9:10写道：

**Comment by duxiangkun** [comment]
您好，对于这个较长时间我没有很清晰的概念，不知道您训练的样本量和batch_size设为多少呢？我现在的训练集有9万多张，batch_size为32，现在epoch到6万多，loss在30上下波动。




------------------ 原始邮件 ------------------
发件人: "Antonio-hi"<notifications@github.com>;
发送时间: 2019年4月14日(星期天) 晚上9:34
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com>;
抄送: "空空"<2476073471@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] train predicted label is errorand train accuracy is low (#176)



这是正常的，请保持适当的学习率，例如1e-1继续训练，需等待较长时间 
 
 duxiangkun <notifications@github.com> 于2019年4月14日周日 下午9:10写道：

**Comment by Antonio-hi** [comment]
继续训练到10Wstep，如果loss还没有下降可以回头再好好看看代码和论文，有可能是某个地方还没有完全理解导致设置错误，这个项目作者提供的代码没有问题，但是需要好好读一读

duxiangkun <notifications@github.com> 于2019年4月15日周一 上午10:57写道：

**Comment by duxiangkun** [comment]
好的，谢谢！
