### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint: model/shadownet/shadownet_2017-09-29-19-16-33.ckpt-39999

### ISSUE THREAD

**Issue by Spatialghost** [MaybeShewill-CV/CRNN_Tensorflow#178]
Hi, when i try to start demo_shadownet.py, i get ValueError: The passed save_path is not a valid checkpoint: model/shadownet/shadownet_2017-09-29-19-16-33.ckpt-39999.
Please help to solve this problem.
Great thanks!

**Comment by Spatialghost** [comment]
Solved!

**Comment by mementomori25** [comment]
how?
