### ISSUE TITLE
How to creat correct dataset?

### ISSUE THREAD

**Issue by Spatialghost** [MaybeShewill-CV/CRNN_Tensorflow#179]
Hi, how to create correct dataset for  CRNN_Tensorflow?
If possible, who can share instruction or give recomandation?

**Comment by mdbenito** [comment]
You have got some instructions in the readme. Basically you store your images and an index file in some folder and use `tools/write_text_features.py`

**Comment by Spatialghost** [comment]
Thank you for answer!

**Comment by Spatialghost** [comment]
In data folder need to create test and train subfolders.

**Comment by xiaoaoran** [comment]
It seems that images and an index file should be stored in both the 'Train' and 'Test' subfolders, which means we should divide images by ourselves. But the 'read me' file says all images can be divided into train, test and validation set after running `tools/write_text_features.py`. I am confused.
