### ISSUE TITLE
[question]Can we build the network from meta file instead of class

### ISSUE THREAD

**Issue by ryanwcyin** [MaybeShewill-CV/CRNN_Tensorflow#181]
Inside the tools/test and demo file, we build the shadow CRNN network before we do prediction.

Is it possible to restore the network from ckpt.meta instead of build from the class? like by using get_tensor_by_name from the restored graph.

Thanks

**Comment by MaybeShewill-CV** [comment]
@ryanwcyin I will upload a tools to convert the model into tensorflow saved model which may satisfy your wish:)
