### ISSUE TITLE
cuda8.0 must be used?

### ISSUE THREAD

**Issue by aiguiru** [MaybeShewill-CV/CRNN_Tensorflow#182]
Hello, everyone, my PC has installed cuda9.0. when I run the demo the results shows 'ImportError: libcusolver.so.8.0'.What should I do? reinstall cuda8.0 or other way?

**Comment by ryanwcyin** [comment]
Try:
echo $LD_LIBRARY_PATH

Make sure libcusolver.so.8.0 is existed and inside lib64 directory.

Ref:
https://stackoverflow.com/questions/44993098/importerror-libcusolver-so-8-0-cannot-open-shared-object-file-no-such-file-or?noredirect=1&lq=1

**Comment by MaybeShewill-CV** [comment]
@aiguiru The repo has been updated with tensorflow 1.12 and cuda 9.0
