### ISSUE TITLE
nvidia-docker run is error

### ISSUE THREAD

**Issue by smileAllYears** [MaybeShewill-CV/CRNN_Tensorflow#184]
I follow the procedure in the readme of docker folder, build the docker of GPU version, first run the command: "docker build-t crnn-tf: gpu-f docker/ GPU /Dockerfile." then run the command: "nvidia-docker run-it -- rm-v <path to project>:/app crnn-tf: GPU", and the error appears：
![image](https://user-images.githubusercontent.com/6064274/50471290-ec219100-09ee-11e9-9aa4-872ca0dd36e0.png)

**Comment by ryanwcyin** [comment]
Can you provide more info of error log and system config, please?
