### ISSUE TITLE
error while using pre-trained models 

### ISSUE THREAD

**Issue by tiru1930** [MaybeShewill-CV/CRNN_Tensorflow#186]
INFO: 01-02 13:50:14: tf_logging.py:115 * 140708023076608 Restoring parameters from model/shadownet/shadownet_2017-10-17-11-47-46.ckpt-199999
2019-01-02 13:50:14.751587: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key shadow/batch_normalization/beta not found in checkpoint

I am trying to use pre-trained model, cloned the repo installed requirements and ran the demo for single example but got above error.

**Comment by ziyuwzf** [comment]
ME TOO

**Comment by Wenqiang-Miao** [comment]
@tiru1930  Hello,  I have encountered the same problem,Have you solved it?

**Comment by tiru1930** [comment]
@Wenqiang-Miao  ,no ,not able to find the fix

**Comment by juanluisrosaramos** [comment]
The provided model doesn't work with the TF code version of the Master branch (1.10). You need to download the code of the branch "revert-138-patch-2". The model provided is trained with this TF version 1.3 "FROM tensorflow/tensorflow:1.3.0-gpu-py3" and it implements the CNN and LSTM layers in a different way that is why Tf 1.10. is not able to load that model.

I am trying to retrain a model with TF 1.10 but my net isn't able to converge.

**Comment by wdsd641417025** [comment]
@juanluisrosaramos  do you miss error when you  use you model to test data?

**Comment by juanluisrosaramos** [comment]
@wdsd641417025 I have no errors using the old branch and different and variate errors using master branch. This is due to the fact that the model provided is saved with older tensorflow version

**Comment by juanluisrosaramos** [comment]
@wdsd641417025  If you want to use the trained model provided by the author (in folder model/shadownet) you need to use the code provided in branch  revert-138-patch-2 that is in TF version 1.3

**Comment by MaybeShewill-CV** [comment]
@tiru1930 You may update the repo and test again:)
