### ISSUE TITLE
transform pre-model to pb

### ISSUE THREAD

**Issue by wdsd641417025** [MaybeShewill-CV/CRNN_Tensorflow#194]
I want transfrom my model to .pb but i dont know how to do could somebody give me some example code.

**Comment by MaybeShewill-CV** [comment]
@wdsd641417025 I will update a new tools to generate the tensorflow saved model which could be used to serve the net model

**Comment by wdsd641417025** [comment]
@MaybeShewill-CV  Thanks！ so kind of you
