### ISSUE TITLE
error in training model

### ISSUE THREAD

**Issue by barhaiya11** [MaybeShewill-CV/CRNN_Tensorflow#195]
When i am running training.py it is showing me the following error

 assert ops.exists(tfrecords_path), "tfrecords file not found: %s" % tfrecords_path
AssertionError: tfrecords file not found: G:/CRNN_Tensorflow-master/data\train_feature.tfrecords.

Please try to resolve this issue asap.

**Comment by MaybeShewill-CV** [comment]
@barhaiya11 The tensorflow records file is missing. You may update the repo and test again:)
