### ISSUE TITLE
Cv2.erro when Converting My Dataset into TensorFlow records

### ISSUE THREAD

**Issue by niddal-imam** [MaybeShewill-CV/CRNN_Tensorflow#197]
I am trying to convert my dataset into tensorflow records, but I have been getting this error massage:

!python3 /home/paperspace/Desktop/CRNN_Tensorflow-chinese_version_debug/tools/write_text_tfrecords.py --dataset_dir /home/paperspace/Desktop/CRNN_Tensorflow-chinese_version_debug/data --save_dir /home/paperspace/Desktop/CRNN_Tensorflow-chinese_version_debug/data/ --batch_size 2

Initialize the dataset provider ......
Dataset provider intialize complete
Start writing training tf records
  0%|                                                     | 0/1 [00:00<?, ?it/s]OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/imgwarp.cpp, line 3492

Traceback (most recent call last):
  File "/home/paperspace/Desktop/CRNN_Tensorflow-chinese_version_debug/tools/write_text_tfrecords.py", line 131, in <module>
    write_features(dataset_dir=args.dataset_dir, save_dir=args.save_dir, batch_size=args.batch_size)
  File "/home/paperspace/Desktop/CRNN_Tensorflow-chinese_version_debug/tools/write_text_tfrecords.py", line 71, in write_features
    train_images = [cv2.resize(tmp, (100, 32)) for tmp in train_images]
  File "/home/paperspace/Desktop/CRNN_Tensorflow-chinese_version_debug/tools/write_text_tfrecords.py", line 71, in <listcomp>
    train_images = [cv2.resize(tmp, (100, 32)) for tmp in train_images]
cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

Any suggestion?

**Comment by MaybeShewill-CV** [comment]
@niddal-imam You may update the repo and test the new tfrecods converter tools:)
