### ISSUE TITLE
How did the annotation file constructed

### ISSUE THREAD

**Issue by think-chao** [MaybeShewill-CV/CRNN_Tensorflow#198]
image_name, label_index = line.rstrip('\r').rstrip('\n').split(' ')
image_path = ops.join(self._dataset_dir, image_name)
label_index = int(label_index)

what does the label_index means?

**Comment by MaybeShewill-CV** [comment]
@think-chao The annotation file was included in the synth90k dataset. You may download the dataset and check it yourself:)
