### ISSUE TITLE
Questions about validating model capabilities and lexicon in data sets

### ISSUE THREAD

**Issue by SaraYue** [MaybeShewill-CV/CRNN_Tensorflow#199]
Hello, thank you for sharing. I have two questions to ask: 
1. I want to validate the model performance on the IC13 dataset as mentioned in the paper, but they use different char_maps, so I want to know how to implement this test. Do I need to convert the test data set into tfrecords?
2. Can you explain how lexicon is implemented in data sets?

**Comment by MaybeShewill-CV** [comment]
@SaraYue 1.If you do not want to use tfrecords you should implement your own data feed pipline 2.The lexcion of synth90k dataset was provided by it's own
3.If you want to validate the model's performance on other dataset you may implement your own data feed pipline and replace the old dataset inferface which is used in evaluation.py with your new one:)
