### ISSUE TITLE
bug in validation?

### ISSUE THREAD

**Issue by soldierofhell** [MaybeShewill-CV/CRNN_Tensorflow#200]
Hi @MaybeShewill-CV,
I think there's a bug in validation part of training where you override train_labels tensor with sess.run() result. Same goes for val_labels.
By the way, it would be nice to define a parameter for validation interval (currently hard-coded 500 epochs)

**Comment by MaybeShewill-CV** [comment]
@soldierofhell It's not a bug the first train_labels are sparase matrix and the second train labels are the transformed string label. The same variable name may confuse you. I will make it more clear:)

**Comment by soldierofhell** [comment]
With the same variable name afer first iteration of validation I had an error that train_labels tensor cannot be found in graph. That was because it was no longer initial (sparse) tensor, but string label.
Nevertheless, now it should be ok

**Comment by MaybeShewill-CV** [comment]
@soldierofhell Oops I got your meanning. That's definitely a bug. Since the beem search is quite slow I have not used the decode model ever. That's the reason why I leave that bug. Thanks a lot:)
