### ISSUE TITLE
To train on Engraved or stamped VIN number Images.

### ISSUE THREAD

**Issue by harshalcse** [MaybeShewill-CV/CRNN_Tensorflow#201]
Can we build model for CAPITAL ALPHANUMERIC Characters  i.e. Vehicle Identification Number(VIN) recognition using number of VIN images?
please help ...

**Comment by MaybeShewill-CV** [comment]
@harshalcse If you want to do such task you need to prepare your own dataset:)

**Comment by harshalcse** [comment]
@MaybeShewill-CV sir I already prepared dataset containing on Region of text which gray scaled images.

**Comment by MaybeShewill-CV** [comment]
@harshalcse Implement your own data feed pip line or make your dataset share the same dataset format of Synth90k dataset and you may start training then:)

**Comment by harshalcse** [comment]
@MaybeShewill-CV which dataset format Synth90k  word dataset or character dataset?

**Comment by MaybeShewill-CV** [comment]
@harshalcse Synthetic Word Dataset (MJSynth dataset):)

**Comment by soldierofhell** [comment]
Hi @harshalcse, how big is your dataset? Do you have VINs from all around the world? Actually I'm gonna try the same task soon. Will you do some custom op for decoding?

**Comment by harshalcse** [comment]
@MaybeShewill-CV MJSynth dataset contains annotation_test.txt, annotation_train.txt, annotation.txt, annotation_val.txt, imlist.txt, lexicon.txt files does that files need to at time to trainnig my own dataset if yes then
Is there any automated process ? 
What is use of that each file ?

**Comment by harshalcse** [comment]
> Hi @harshalcse, how big is your dataset? Do you have VINs from all around the world? Actually I'm gonna try the same task soon. Will you do some custom op for decoding?

@soldierofhell  not too much big my dataset contains 2000 images. If you are ready to help me then I will share with you.

**Comment by MaybeShewill-CV** [comment]
@harshalcse There is no automatically way unless you implement your own data feed pip line which is not difficult as far as I am concerned. The usage of each file you may find it on their website:)

**Comment by soldierofhell** [comment]
@harshalcse, contact me at 666.soldierofhell.666@gmail.com, I'm gonna set up some google colab.

**Comment by harshalcse** [comment]
@MaybeShewill-CV is MJSynth dataset contains word containing number or only characters ?

**Comment by MaybeShewill-CV** [comment]
@harshalcse Contains number and English letters:)

**Comment by harshalcse** [comment]
> @harshalcse, contact me at [666.soldierofhell.666@gmail.com](mailto:666.soldierofhell.666@gmail.com), I'm gonna set up some google colab.

shared imges please check

**Comment by soldierofhell** [comment]
Thanks, but I don't see any labels in this dataset?

And some of the images are definitely too much rotated

pon., 18 mar 2019 o 12:31 Harshal Bhamare <notifications@github.com>
napisał(a):

**Comment by harshalcse** [comment]
> > @harshalcse, contact me at [666.soldierofhell.666@gmail.com](mailto:666.soldierofhell.666@gmail.com), I'm gonna set up some google colab.
> 
> shared imges please check

@soldierofhell As per below reply from your mail 

```
Actually you have to know them :) I mean without some manually prepared list mapping: file.jpg -> VIN in whichever format you cannot start. Of course you can try too use pretrained MJSynth model but it will surely give you poor results and you'll have to correct it manullay.

In other words you have to at least have some text file like this:

file1.jpg, VIN00000000000001
file2.jpg, VIN00000000000002 
file3.jpg, VIN00000000000003 
```
so client have 9000 VIN images so we to add pictures of 9000 images but isit a robust solutions?

**Comment by harshalcse** [comment]
@soldierofhell Actually right now we have more than 5000 VIN images . So by that apporach how much accuracy we can get approximately?

**Comment by MaybeShewill-CV** [comment]
@harshalcse Since no further question about the repo. I will close the issue. You may discuss your problems somewhere else:)
