### ISSUE TITLE
Label length is zero error 

### ISSUE THREAD

**Issue by LinanYaooo** [MaybeShewill-CV/CRNN_Tensorflow#205]
Hi, thanks for your sharing above all,
and I am facing an issue that an InvalidArgumentError, saying:

InvalidArgumentError (see above for traceback): Labels length is zero in batch 27
         [[Node: CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shadow_net/sequence_rnn_module/transpose_time_major/_71, DeserializeSparse, DeserializeSparse:1, CTCLoss_1/sequence_length)]]

is there any solution can solve the problem above? thanks

**Comment by LinanYaooo** [comment]
By the way, the issue appears in  training step

**Comment by LinanYaooo** [comment]
the problem has been solved, the reason is I have a label like "", recognized as an empty label.

And now the training can be initiated but the cost cannot converge .....

I also have to admit the length of labels to be longer than the input(enable the corresponding flag),
does it really matter? otherwise, exception will be given.

**Comment by MaybeShewill-CV** [comment]
@LinanYaooo You may check the origin paper for details. The image length shoud be longer than the 100pix:)
