### ISSUE TITLE
Problem about the global_step.

### ISSUE THREAD

**Issue by LJXLJXLJX** [MaybeShewill-CV/CRNN_Tensorflow#208]
I try to restore my model and continue training, and  I noticed that the epoch was reset to 0 rather and restore from the saved global_step in the ckpt file, at line 276
`for epoch in range(train_epochs):`

Then at line 330
`saver.save(sess=sess, save_path=model_save_path, global_step=epoch)`
The global_step will be overwritten here.

**Comment by MaybeShewill-CV** [comment]
@LJXLJXLJX Yes the epoch nums will be over written here. If you find a suitable way to recover the epoch number from pretrained model weights you may share it with us:)
