### ISSUE TITLE
 can't download the chinese model 

### ISSUE THREAD

**Issue by pingzi5233** [MaybeShewill-CV/CRNN_Tensorflow#209]
Hi,i can't download the chinese model,there is any way to solve this? can you send me this model?thank you very much.

**Comment by MaybeShewill-CV** [comment]
@pingzi5233 The pretrained model has been uploaded into dropbox. If you can not download it  you may download the origin chinese dataset and trained your own model yourself:)

**Comment by pingzi5233** [comment]
ok,thank you.
but when i train the chinese model,i met a question:even though i add os.environ['CUDA_VISIBLE_DEVICES'] = "0" and with tf.device('/gpu:0')  in train_tfrecords.py,i just can't use gpu to train,through watch nvidia-smi ,the GPU Memory-Usage and GPU-Util  Compute M is all 0,can you tell me why?please

**Comment by MaybeShewill-CV** [comment]
@pingzi5233 Paste your complete command here and put more information:)

**Comment by pingzi5233** [comment]
thank you for reply.
i fix this problem,i install tensorflow ang tensorflow-gpu all,so when i train,maybe it use tensorflow firstly,so i uninstall tensorflow and retain the tensorflow-gpu,then can use gpu successfully when i train.
sorry to bother you:)
