### ISSUE TITLE
what's "ord_map.json" mean?

### ISSUE THREAD

**Issue by Giggledefy** [MaybeShewill-CV/CRNN_Tensorflow#211]
I have no idea that how to write `ord_map_en.json` in `PATH/data/char_dict`.
I guess the `char_dict_en.json` is ASCII. But the `ord_map` let me go to crazy.... I'd like to add `B D F G H K S W X Y Z ` in that .json file.
Could you tell me how to fill in  it ?

**Comment by MaybeShewill-CV** [comment]
@Giggledefy You can replace it with a relationship file which map the origin character with integer index.By the way those two files can be automatically generated:)

**Comment by Giggledefy** [comment]
@MaybeShewill-CV Thanks for your reply.
But I don't quite understand it. I think the values in your `ord_map` are discontinuous. Do you mean I can fill the values of `ord_map` by myself,  whether it's 1 or 2 or 101 or 102, just do not repeat it ?  And what do you say about automatic generation?

**Comment by Giggledefy** [comment]
It's my fault, I saw something about ord_map in `write_tfrecords.py`...

**Comment by MaybeShewill-CV** [comment]
@Giggledefy Yep you may refer to the code for details:)
