### ISSUE TITLE
Weird Results with New Pre-Trained Model

### ISSUE THREAD

**Issue by guddulrk** [MaybeShewill-CV/CRNN_Tensorflow#212]
I am trying to test the new model on pre-trained Synth90K data, but when I test the model I get the following result:

Predict image test_02.jpg result p8mm85k65

However, the previous version works correctly and gives me correct results.  Is this happening due to some changes in char_dict_en.json and ord_map_en.json files?

**Comment by MaybeShewill-CV** [comment]
@guddulrk Yep you should use the newly uploaded char dict and ord map json file:)

**Comment by guddulrk** [comment]
Hi @MaybeShewill-CV 
when I am trying to write my own dataset into TFRecord, I am getting following error:

E0331 14:35:06.912765 11600 tf_io_pipline_tools.py:212] Image file H:/asghar/CRNN_Tensorflow/data/dataset/imgs/word_950.png is not complete
b'`\x82'

I have prepared the dataset and text files in the same pattern as in Synthetic90K dataset. My dataset contain Arabic characters as  ('ب'). Any help please?

**Comment by MaybeShewill-CV** [comment]
@guddulrk The script will check whether the image format is jpeg you will run into this error due to the png image format:)

**Comment by guddulrk** [comment]
thanks @MaybeShewill-CV,

I have changed the type of images into JPG, but now I am getting the following error:

KeyError: 'Character ا missing in ord_map.json'

Even if I change the dataset to Synthetic90K, Chinese or my own, but getting the same error.
Any help will be appreciated. Thanks

**Comment by MaybeShewill-CV** [comment]
@guddulrk Which dataset did you use?

**Comment by guddulrk** [comment]
Synthetic90K

**Comment by guddulrk** [comment]
annotation.txt

dataset/word_1.jpg 500
dataset/word_1.jpg 200
dataset/word_1.jpg 120


lexicon.txt
فل
پارٹ
موٹروئے

These are my images and the lexicon values on the index: 500, 200, 120

**Comment by guddulrk** [comment]
@MaybeShewill-CV , if I am generating char_dict.json and ord_map.json files, automatically, then when the data is written in TFRecord, I get the following error:

TypeError: can't pickle SwigPyObject objects

at the following line:

 tfrecords_writer.run()
  File "\CRNN_Tensorflow\data_provider\tf_io_pipline_fast_tools.py", line 460, in run
    process.start()

**Comment by MaybeShewill-CV** [comment]
@guddulrk Which os platform did you run the code:)

**Comment by guddulrk** [comment]
Windows 64 bit

**Comment by MaybeShewill-CV** [comment]
@guddulrk fork can not be directly used in windows. You may google python multiprocess module's usage under windows:)

**Comment by guddulrk** [comment]
@MaybeShewill-CV Thanks very much. Looking for the help but could not got any help yet.

**Comment by MaybeShewill-CV** [comment]
@guddulrk Good luck:)
