### ISSUE TITLE
ModuleNotFoundError when running test_shadownet.py

### ISSUE THREAD

**Issue by opentld** [MaybeShewill-CV/CRNN_Tensorflow#214]
python ./tools/test_shadownet.py --dataset_dir ./data/test_images --weight_path ./crnn_chinese --char_dict_path ./data/char_dict --ord_map_dict_path ./data/char_dict --process_all 1 --visualize 1
Traceback (most recent call last):
  File "./tools/test_shadownet.py", line 20, in <module>
    from config import global_config
ModuleNotFoundError: No module named 'config'

anybody knows how to resolve this problem?

**Comment by opentld** [comment]
add these lines after  line19

from sys import path
from os import getcwd
path.append(getcwd())

fixed!

**Comment by AhmadShaik** [comment]
> add these lines after line19
> 
> from sys import path
> from os import getcwd
> path.append(getcwd())
> 
> fixed!

I have updated the script but still I am getting the same error.

**Comment by AhmadShaik** [comment]
Now I am able to run the test script successfully. Your suggestion worked perfectly. Thank you very much @MaybeShewill-CV and @opentld .
