### ISSUE TITLE
Suggestion : The image shape should be dynamic when test.

### ISSUE THREAD

**Issue by LJXLJXLJX** [MaybeShewill-CV/CRNN_Tensorflow#217]
Set a INPUT_SIZE is necessary when training , because the size of images in a batch should be unified.

But when doing a test for single image, the aspects are all different. Setting a global size will cause distortion of the image and affect the recognition result.

So I suggest set a dynamic input size when doing a test, just make sure the height is 32 and the sequence length is ok.
```python
new_heigth = 32
rate = new_heigth / image.shape[0]
new_width = int(rate * image.shape[1])
image = cv2.resize(image, (new_width, new_heigth), interpolation=cv2.INTER_LINEAR)
```

And I think separate the model loading step and recognition step will be more convenient .

**Comment by MaybeShewill-CV** [comment]
@LJXLJXLJX Yep you only need to make sure the image height is 32 and the image width can be scaled along the image height. I will change it when have spare time:)

**Comment by MaybeShewill-CV** [comment]
I have fixed the problem:)
