### ISSUE TITLE
Poor performance on chinese recognition

### ISSUE THREAD

**Issue by opentld** [MaybeShewill-CV/CRNN_Tensorflow#218]
The test jpg runs perfect. But to my own test jpg, the performance is poor :(
Is there any tricks?

![image](https://user-images.githubusercontent.com/21096515/55299945-ec0ab480-5467-11e9-84cc-2bccef24521f.png)

**Comment by MaybeShewill-CV** [comment]
@opentld Maybe you need to train your own model on your own dataset:)

**Comment by opentld** [comment]
> @opentld Maybe you need to train your own model on your own dataset:)

Must I train with my own data set to get a good recognition?
How can I achieve good results for any image recognition?

**Comment by MaybeShewill-CV** [comment]
@opentld The model's preformance is related to the dataset. You need to adjust the model according to your task. There is no model which can fit all the input data. You may read other paper and function which introduce method to transfer the model into neural scene usage:)
