### ISSUE TITLE
Loss does not decrease from 12

### ISSUE THREAD

**Issue by guddulrk** [MaybeShewill-CV/CRNN_Tensorflow#219]
Hi @MaybeShewill-CV, finally I am done with all the issues, but I am running a bit old version of the project. I am running the train_shadow on my own dataset but the cost does not decrease from 12. Any help please?

**Comment by MaybeShewill-CV** [comment]
@guddulrk Pull and the new code the put more information here:)

**Comment by guddulrk** [comment]
Thanks, @MaybeShewill-CV, I am working in windows 64bit environment and when I was trying to convert my dataset into tfrecords with new  code, I was getting some issues in multi-processing. I tried a lot but could got a solution. However, the old cold is running correctly. I am thinking to create a tfrecords file with old data provider code and then train the model with new code.

**Comment by MaybeShewill-CV** [comment]
@guddulrk Please make the sure the training image and it's corresponding label is correct. If the training samples are correct. You may need to adjust the lr and pay a little patience to the training procedure. The ctc loss need a period of time to warm up:).

**Comment by guddulrk** [comment]
@MaybeShewill-CV , thanks very much for your help. I will get back to you if need any help.
