### ISSUE TITLE
Please give more details about "annotation_train.txt"!

### ISSUE THREAD

**Issue by bihuan1999** [MaybeShewill-CV/CRNN_Tensorflow#220]
Please give more details about the  "annotation_train.txt" or "annotation_test.txt". It is useful for retraining the Chinese datasets.

**Comment by MaybeShewill-CV** [comment]
@bihuan1999 You may read the synth90k dataset for details of those two annotation file:) If you want to reuse the data feed pip line for synth90k dataset those two annotation files are needed but they're not necessary if you have your own data feed pip line:)

**Comment by bihuan1999** [comment]
Thanks for reply.  When I try to build the annotation files like "/img/407_MYSTERY_50708.jpg MYSTERY", the TFrecode_Writer doesn't works. Please give some examples about the annotation file and the lexicon file. Thanks again. I am new in study the CRNN.
