### ISSUE TITLE
Some questions about CRNN

### ISSUE THREAD

**Issue by xiaowenhe** [MaybeShewill-CV/CRNN_Tensorflow#221]
Hi, @MaybeShewill-CV ,I have two questions,can you give me some hints?
Question 1: Could I use CRNN to predict License Plate,License Plate like:
![EU_20160301200255](https://user-images.githubusercontent.com/28335784/55449837-c0223700-55ff-11e9-8ed2-b56ebafd99e1.jpg)
If could, how many datasets should used,1K or 10K or 100K?
Question 2:  Could CRNN used for two lines sequence in image ,like: 
![india_51541](https://user-images.githubusercontent.com/28335784/55450154-ccf35a80-5600-11e9-8cf7-619c637fa54f.jpg)

Thank you very much!

**Comment by MaybeShewill-CV** [comment]
@xiaowenhe The first row is suitable for crnn model. I can not tell you how many samples are needed for the model. The model's performance and generalization will rise when the have large dataset but you still need to do tests on your specific task. Two line sequence is not suitable for the model in my opinion:)

**Comment by xiaowenhe** [comment]
@MaybeShewill-CV ，I get it, thank you very much!

**Comment by MaybeShewill-CV** [comment]
@xiaowenhe welcome:)
