### ISSUE TITLE
New network

### ISSUE THREAD

**Issue by Usmankhujaev** [MaybeShewill-CV/CRNN_Tensorflow#222]
I used your previous network and I fully changed VGG part to the depthwise separable convolutional network, I made the network much deeper with a sequence length of 16 and with image size (128x64px) the accuracy significantly increased in all the ways and even it got better predictions. I used it to license plate recognition and using Geometric Image Transformations I was able to recognize multiple-row text (not only one line text). Send me an email for more details and changes performed on your previous project u.s.saidrasul@inha.edu.

**Comment by MaybeShewill-CV** [comment]
@Usmankhujaev I do not know what you're talking about. Why I should follow your command and send an email to you? Don't you learn what polite is in school?

**Comment by Usmankhujaev** [comment]
I don't think I talked to you in a rude way so that I have to consider if I am polite or no. You implemented CNN in this project. You just removed fully connected layers from simple VGG network and this work is already done by Baoguang Shi et al. I am saying that I modified the CNN network and I increased the performance. If you don't know what I am talking about seems like you don't know your project well.

**Comment by Usmankhujaev** [comment]
And I said if you are interested about what I have done you can send me email. AND WHERE DID YOU FIND ME RUDE IN THIS SENTENCE? I guess I said everything politely

**Comment by MaybeShewill-CV** [comment]
@Usmankhujaev You'e better look back to what you've said. Where is the word "if you are interested about what I have done"? I do not know which one of us is blind. I never said I made the CRNN model I just reimplement the origin author's great work which can be found [here](https://github.com/MaybeShewill-CV/CRNN_Tensorflow/blob/master/README.md). What you've done is just changing the backbone net which I am not interested in at all.

**Comment by MaybeShewill-CV** [comment]
@Usmankhujaev And I really want to know if you have little knowledge on DL. Can't you see I have not modified the network structure and just reimplement a more efficient data feed front-end?

**Comment by MaybeShewill-CV** [comment]
@Usmankhujaev I misunderstand your meaning of your words "Send me an email for more details and changes performed on your previous project u.s.saidrasul@inha.edu.". I thought you want me to send you an email to tell you the difference between the updated repo and old version but you want me to send you an email to discuss your modification on the origin CRNN model. If you have spare time you may create a new repo and upload your new modificated model there. We may discuss it there. Apologies for what I said:)

**Comment by Usmankhujaev** [comment]
I did say something bad to you I just wanted to share with my research with you because you implemented this version of CRNN i wanted to discuss about the changes I have done to your project

**Comment by Usmankhujaev** [comment]
*I DIDN'T

**Comment by MaybeShewill-CV** [comment]
@Usmankhujaev Yep. I misunderstood your words. I thought you meant to ask me to send you an email to tell you the difference between the old repo and the new repo. I've already known your true meaning of sharing your modification with me now. Anyway apologizes to you:)

**Comment by Usmankhujaev** [comment]
that's okay :)

**Comment by xxxpsyduck** [comment]
@Usmankhujaev Hello. I'm interested in changing the backbone. I have a question: how does the depthwise separable convolutional network compare with resnet at the same depth level?
