### ISSUE TITLE
about Training your own model

### ISSUE THREAD

**Issue by opentld** [MaybeShewill-CV/CRNN_Tensorflow#223]
Hi, friend!

I am trying to train my own model on my own dataset, here is questions:
1. Download the whole synth90k dataset...    Is that means I must download the synth90k? Can I use my own pictures ?  or I must put my pictures into the synth90k? 
2. If It is possible to use my own pictures, how many pictures are appropriate?

May you please give me a complete detailed example?

Many thanks!

**Comment by MaybeShewill-CV** [comment]
@opentld 1.Your own data can be used to train the model as well.If you want to reuse the data feed pip line you need to organize your dataset following the synth90k dataset's format. You may implement your own data feed pip line either. 2. In my experience the dataset I used to train the model all contains at least more than one million training samples:)

**Comment by opentld** [comment]
1 million samples .....            give me a sad expression, please  -_-!!!

**Comment by MaybeShewill-CV** [comment]
@opentld I just told you the sample count of the dataset I used before. You may test your own dataset:)

**Comment by opentld** [comment]
@MaybeShewill-CV   Here is a new bad news, the link you provided for Synth 90k dataset, can not be accessed now...

**Comment by MaybeShewill-CV** [comment]
@opentld Maybe something is wrong with your network connection. It can be accessed a minute ago

**Comment by OneIdea-OneWorld** [comment]
Could you tell me the details of synth90k dataset's format? @MaybeShewill-CV
