### ISSUE TITLE
识别缺好几个字

### ISSUE THREAD

**Issue by pingzi5233** [MaybeShewill-CV/CRNN_Tensorflow#224]
您好，不知道有没有遇到这样一个问题，例如我需要识别的文本框的宽高是427x32，使用您的中文模型，如果resize成280x32，会导致很多字都识别错误，但如果高固定在32，宽设置为原输入文本框的宽*一个比例，这样就识别出前十三个字（均识别正确），但是后五六个字根本没有识别结果，请问知道是什么原因吗？
![image](https://user-images.githubusercontent.com/48909056/55705655-d706c600-5a11-11e9-8996-ccd419c08840.png)
resize成280x32的识别结果：
![image](https://user-images.githubusercontent.com/48909056/55705961-98254000-5a12-11e9-8378-6e6f7d0df68d.png)
按实际宽来resize的话，识别结果为：
![image](https://user-images.githubusercontent.com/48909056/55706016-b4c17800-5a12-11e9-80c9-16d1d6dfa665.png)

**Comment by Fighting-JJ** [comment]
你好，作者提供的模型 训练数据的大小是怎样的你知道吧。使用作者提供的模型，需要你的测试图像在resize后和作者训练使用的图像相似，这样模型才可以正确预测。
模型的泛化能力还没有强大到塞什么进去都可以识别的地步吧。

**Comment by pingzi5233** [comment]
可是我采取的resize正是作者更新的test_shadownet.py内的啊
![image](https://user-images.githubusercontent.com/48909056/55712532-7c756600-5a21-11e9-8f2b-18309c21b667.png)

**Comment by Fighting-JJ** [comment]
看readme中，作者提供的数据长度都是275左右的样子，压缩到了100。
你的测试数据是宽是400多了，按比例应该是 427/（275/100），大概这样子吧

**Comment by MaybeShewill-CV** [comment]
@pingzi5233 I forgot to change the sequence length when applying the ctc beam search. I have correct the bug you may pull and update the repo and test again. I have test the model on a image in my local pc with shape (1161, 44) and the output performs normally.
![correct](https://user-images.githubusercontent.com/15725187/55730689-5795e880-5a4b-11e9-828e-6fb7f04b713c.png). Besides do not forget to change the config file when testing the chinese model:)

**Comment by pingzi5233** [comment]
thank you very much~

**Comment by pingzi5233** [comment]
已经验证过了，确实能识别了，再次感谢~

**Comment by MaybeShewill-CV** [comment]
@pingzi5233 好的 不客气:)
