### ISSUE TITLE
用自己的数据集训练模型

### ISSUE THREAD

**Issue by opentld** [MaybeShewill-CV/CRNN_Tensorflow#225]
您提供的链接指向的数据集一直下载不下来。我想完全用自己的数据集来进行训练。
请问数据集的格式是怎么样的？是类似这样的吗？
![image](https://user-images.githubusercontent.com/21096515/55796504-b9625b00-5afc-11e9-80c3-02c0139c589f.png)
![image](https://user-images.githubusercontent.com/21096515/55796545-d4cd6600-5afc-11e9-9e87-3ac96de816d1.png)

谢谢！

**Comment by majestichou** [comment]
下载不下来可能需要翻墙吧，我下载没问题

**Comment by opentld** [comment]
@MaybeShewill-CV  帅哥，我下载不下来咋看synth90k数据集的格式  -_-!!!  :(
麻烦直接贴一下好吗？

**Comment by MaybeShewill-CV** [comment]
@opentld 不好意思 太大了 你可以直接在百度上搜一下 我记得好像搜得到这个格式. 或者你自己实现一个data feed pip line就可以了,这样方便你使用你自定义的数据集格式:)

**Comment by MagicCodess** [comment]
@opentld 你好，请问中文训练起来了吗

**Comment by MaybeShewill-CV** [comment]
@MagicCodess 自己查看readme相关信息吧:)

**Comment by BigPandaCPU** [comment]
> 下载不下来可能需要翻墙吧，我下载没问题



> 您提供的链接指向的数据集一直下载不下来。我想完全用自己的数据集来进行训练。
> 请问数据集的格式是怎么样的？是类似这样的吗？
> ![image](https://user-images.githubusercontent.com/21096515/55796504-b9625b00-5afc-11e9-80c3-02c0139c589f.png)
> ![image](https://user-images.githubusercontent.com/21096515/55796545-d4cd6600-5afc-11e9-9e87-3ac96de816d1.png)
> 
> 谢谢！

我把synth90k数据的的那几个文件看了一下。
![image](https://user-images.githubusercontent.com/25834151/57358198-79e46880-71a7-11e9-858d-ae1d18abac0e.png)
这里的 annotation**.txt 文件夹存放的是 每一个文件的路径和它所对应的index（就是lexicon文件中对应的行）
![image](https://user-images.githubusercontent.com/25834151/57358344-cfb91080-71a7-11e9-856c-469d0e01d7bd.png)

这个lexicon.txt文件记录的是所有训练的数据的组成的集合
![image](https://user-images.githubusercontent.com/25834151/57358546-3d653c80-71a8-11e9-99da-064c4017fd5f.png)
annotation中每一行的index就对应这个文件中的 lexicon文件中该行的内容（就是该图片的标注信息）

你再训练自己的数据的时候，只需要按照这个格式准备好你那自己的训练数据，就可以使用他这个代码进行训练了

**Comment by MaybeShewill-CV** [comment]
@BigPandaCPU Thanks:)

**Comment by majestichou** [comment]
> > 下载不下来可能需要翻墙吧，我下载没问题
> 
> > 您提供的链接指向的数据集一直下载不下来。我想完全用自己的数据集来进行训练。
> > 请问数据集的格式是怎么样的？是类似这样的吗？
> > ![image](https://user-images.githubusercontent.com/21096515/55796504-b9625b00-5afc-11e9-80c3-02c0139c589f.png)
> > ![image](https://user-images.githubusercontent.com/21096515/55796545-d4cd6600-5afc-11e9-9e87-3ac96de816d1.png)
> > 谢谢！
> 
> 我把synth90k数据的的那几个文件看了一下。
> ![image](https://user-images.githubusercontent.com/25834151/57358198-79e46880-71a7-11e9-858d-ae1d18abac0e.png)
> 这里的 annotation**.txt 文件夹存放的是 每一个文件的路径和它所对应的index（就是lexicon文件中对应的行）这里的文件夹中存放的都是图片数据
> ![image](https://user-images.githubusercontent.com/25834151/57358344-cfb91080-71a7-11e9-856c-469d0e01d7bd.png)
> 
> 这个lexicon.txt文件记录的是所有训练的数据的组成的集合
> ![image](https://user-images.githubusercontent.com/25834151/57358546-3d653c80-71a8-11e9-99da-064c4017fd5f.png)
> annotation中每一行的index就对应这个文件中的 lexicon文件中该行的内容（就是该图片的标注信息）
> 
> 你再训练自己的数据的时候，只需要按照这个格式准备好你那自己的训练数据，就可以使用他这个代码进行训练了
> 
> 具体的过程，建议去看看write_tfrecords.py文件

嗯嗯，多谢分享了。

**Comment by majestichou** [comment]
> @BigPandaCPU Thanks:)

还是不太理解你这里为什么需要两个json文件？一般来说，神经网络训练不是需要把图片和标签转成tfrecords文件进行输入，然后训练就可以了嘛，为什么还需要json文件呀，还需要两个，这样做是为什么呀？

**Comment by MaybeShewill-CV** [comment]
@majestichou json文件维护了一个char到int标签的映射关系 字符串序列会被映射成int label然后用作标签来监督训练网络.细节你可以看代码:)
