### ISSUE TITLE
3.27 pretrained weights can't be download

### ISSUE THREAD

**Issue by seagullyoyo** [MaybeShewill-CV/CRNN_Tensorflow#226]
in 2019.3.27 Updates,pretrained weights can't be download~

**Comment by MaybeShewill-CV** [comment]
@seagullyoyo You may check your network connection:)

**Comment by seagullyoyo** [comment]
可以下载了～加载新的ckpt时有如下报错：
InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,5825]
   [[node save/Assign_45 (defined at tools/test_shadownet.py:118)  = Assign[T=DT_FLOAT, _class=["loc:@shadow_net/sequence_rnn_module/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](shadow_net/sequence_rnn_module/w, save/RestoreV2/_91)]]

以上报错在加载sync90k训练模型时没有出现

**Comment by seagullyoyo** [comment]
加载pretrained weights的模型，对中文的识别结果有些差，请问优化效果的话有哪些方向~

**Comment by seagullyoyo** [comment]
test_shadownet.py中是不是应该为：
new_width = new_width if new_width < CFG.ARCH.INPUT_SIZE[0] else CFG.ARCH.INPUT_SIZE[0]

**Comment by MaybeShewill-CV** [comment]
@seagullyoyo 可以贴一下识别的结果么:)

**Comment by seagullyoyo** [comment]
![test2](https://user-images.githubusercontent.com/7651392/55935007-137e3000-5c65-11e9-977b-32b7aeadfad9.png)
Predict image test2.png result 八S擎。《。顾38$俭333弱g卧;荡V同穿净■到

**Comment by MaybeShewill-CV** [comment]
@seagullyoyo 原始图像多大 resize以后是什么样子的？

**Comment by seagullyoyo** [comment]
原始shape(39, 618, 3)，resize后(32, 507, 3)

**Comment by MaybeShewill-CV** [comment]
@seagullyoyo Maybe you can do a threshold process to the image and recognize it later. You'd better make your test sample more like the training sample the better:)
![1](https://user-images.githubusercontent.com/15725187/55946459-577e2e80-5c7f-11e9-818b-475f45034345.png)

**Comment by seagullyoyo** [comment]
明白了，做了二值化后得到了相对可用的结果。但是测试中，对于不同的图片，二值化的方式也会不同。有什么办法让模型自适应么？还是说丰富样本的多样性，让模型学到。感谢答疑解惑。

**Comment by MaybeShewill-CV** [comment]
@seagullyoyo 这个靠你自己了哈 加油. 也欢迎分享结果和经验:)

**Comment by wx1111** [comment]
@seagullyoyo 您好，麻烦问下2019年03月27日更新的预训练模型您是怎么下载到的呢？我也遇到了相同的问题。谢谢
