### ISSUE TITLE
How to train it by characters

### ISSUE THREAD

**Issue by MagicCodess** [MaybeShewill-CV/CRNN_Tensorflow#227]
since i want to train the label "hello", is it possible for it to recognize it as h e l l o, and train it seperately as multi labels

**Comment by MaybeShewill-CV** [comment]
@MagicCodess The origin model is used to recognize sequence. You may modify the model structure
 to do your special task:)

**Comment by MagicCodess** [comment]
@MaybeShewill-CV thank you , but how the chinese predictor work, not one character for one label?can you show how the chinese annotation file looks like~

**Comment by MaybeShewill-CV** [comment]
@MagicCodess You may check the Synth90k dataset which is the same as the Chinese training samples:)

**Comment by MagicCodess** [comment]
@MaybeShewill-CV synth90k treat every sample as one label, since it's a word, but for chinese data "个人类交往的广义活动", i should save it as a word in lexcion?

**Comment by MaybeShewill-CV** [comment]
@MagicCodess You may save it as a sequence. You may check the chinese dataset mentioned in my README file:)

**Comment by MagicCodess** [comment]
@MaybeShewill-CV I downloaded chinese dataset but there are only images in it...so I dont know what the annotation files looks like if using chinese dataset

**Comment by MaybeShewill-CV** [comment]
@MagicCodess You may find some useful information about the Chinese dataset in old issue. You may go find it yourself:)
