### ISSUE TITLE
预测的label为空

### ISSUE THREAD

**Issue by duxiangkun** [MaybeShewill-CV/CRNN_Tensorflow#228]
您好，训练过程总cost总在15-40之间震荡，为什么我测试的时候预测结果为空呢，是跟cost过大有关吗？

**Comment by MaybeShewill-CV** [comment]
@duxiangkun 可能是的:)

**Comment by duxiangkun** [comment]
@MaybeShewill-CV 训练时把图片设置为[280, 32]，但是测试时，出现ValueError: Cannot feed value of shape (1, 32, 119, 3) for Tensor 'input:0', which has shape '(1, 32, 280, 3)'，怎么对不同大小的图片预测呢？

**Comment by MaybeShewill-CV** [comment]
@duxiangkun resize到高度为32如果宽度不够280可以pad到280宽:)

**Comment by MaybeShewill-CV** [comment]
@duxiangkun resize到高度为32如果宽度不够280可以pad到280宽:)
