### ISSUE TITLE
the code can not be cloned

### ISSUE THREAD

**Issue by majestichou** [MaybeShewill-CV/CRNN_Tensorflow#229]
![1555046526297](https://user-images.githubusercontent.com/43713443/56014009-0d03bd00-5d26-11e9-8952-62157403cd80.jpg)
git clone到一半就停了（楼主是中国人吧，我就写中文了）

**Comment by MaybeShewill-CV** [comment]
@majestichou 自己检查网络问题或者百度吧：）

**Comment by majestichou** [comment]
谢了老哥。clone或者通过.zip下载下来的代码文件没有区别吧（谷歌或者百度查这两种方式觉得区别不大），zip文件可以正常下载
