### ISSUE TITLE
grpc==0.3-19包

### ISSUE THREAD

**Issue by majestichou** [MaybeShewill-CV/CRNN_Tensorflow#231]
想问一下作者，grpc这个包安装不成功怎么办。
![image](https://user-images.githubusercontent.com/43713443/56024842-747c3580-5d43-11e9-8538-7c809ccb8837.png)

**Comment by MaybeShewill-CV** [comment]
@majestichou 这个你可以百度或者上stackoverflow或者去查grpc的issue:)
