### ISSUE TITLE
  没有write_text_features

### ISSUE THREAD

**Issue by zhoujianwen** [MaybeShewill-CV/CRNN_Tensorflow#232]
python tools/write_text_features 
--dataset_dir PATH/TO/SYNTH90K_DATASET_ROOT_DIR
--save_dir PATH/TO/TFRECORDS_DIR

没有write_text_features

**Comment by MaybeShewill-CV** [comment]
@zhoujianwen write_tfrecords。README忘了更新，周一更新下:)

**Comment by zhoujianwen** [comment]
@MaybeShewill-CV 我正在根据你的要求下载数据集，我想知道在完成conda env create -f crnntf-env.yml和pip3 install -r requirements.txt步骤之后，有需要再安装docker/README.md里面的要求么？

**Comment by zhoujianwen** [comment]
pip3 install GRPC  会出错 ，在 pip2安装却正常，我使用的是conda 环境。

**Comment by MaybeShewill-CV** [comment]
@zhoujianwen docker文件现在为空，如果不需要可以不安装，如果需要docker文件可以回滚代码然后查看原来的用法。关于docker和grpc的使用问题可以自己百度:)
