### ISSUE TITLE
请问lexicon的格式是怎样的

### ISSUE THREAD

**Issue by junkojunko** [MaybeShewill-CV/CRNN_Tensorflow#234]
我在别的项目下载了和您一样的训练中文的数据集，大小和这个一样，但是没有lexicon.txt文件，请问这个文件的格式是怎么样的呢
是不是:

温
柔
某
个
...

这样格式的文件

**Comment by junkojunko** [comment]
您可不可以提供一个后来您训练中文字符的那个lexicon.txt，您readme里英文的Syth90k下不了

**Comment by MaybeShewill-CV** [comment]
@junkojunko 这个文件是自己生成的，你看看synth90k数据集，自己按照那个形式生成一份这个文件就好了:)

**Comment by junkojunko** [comment]
@MaybeShewill-CV  谢谢您的回复，但是数据集比较大在国内下载不下来，挂vpn几十k的速度，下到一半就断了。。

**Comment by MaybeShewill-CV** [comment]
@junkojunko 你只需要看那几个文件是什么东西就好了，不需要下载完整的数据集:)

**Comment by junkojunko** [comment]
@MaybeShewill-CV 谢谢您，这个问题已经解决了，我已经转好数据格式了。但在运行write_tfrecords的时候出现了Broken pipe，我的机器是一个gtx1066 ，12g内存。

**Comment by MaybeShewill-CV** [comment]
@junkojunko 1.这个broken pip具体是什么错误，可以发一下错误截图还有你使用的命令是什么 2.生成tfrecords的顺序是train val test.具体细节你可以查阅代码:)

**Comment by junkojunko** [comment]
![image](https://github.com/junkojunko/pic/blob/master/Screenshot%20from%202019-04-17%2014-52-32.png)

**Comment by junkojunko** [comment]
@MaybeShewill-CV 您好，我刚才又用英文的syth90k跑了一下，还是这个问题，我刚才读了下代码，之前我出错了，确实是train val test的顺序写入，之前的只是读数据，但是在写入 train的时候没问题，接着写入val时broken pipe，错误截图在上一层。谢谢您的解答

**Comment by MaybeShewill-CV** [comment]
@MaybeShewill-CV 截图有问题 显示不了:)

**Comment by junkojunko** [comment]
@MaybeShewill-CV 更新了图片，还是上面的链接，这次应该行了，麻烦您再看一下。

**Comment by MaybeShewill-CV** [comment]
@junkojunko 你走错片场了吧==! 你这个截图不是我的repo吧:)

**Comment by junkojunko** [comment]
@MaybeShewill-CV 对不起🤕，刚才着急了，我确实是在用您的项目。。。两个图片名字相同，我搞混了。

**Comment by junkojunko** [comment]
@MaybeShewill-CV 这次改好了，实在抱歉<(_ _)>😰😰😰

**Comment by MaybeShewill-CV** [comment]
@junkojunko 1.你评论的时候可以直接把图拖进来不用专门建个repo存图==! 2.感觉你这个代码的版本不是我现在上传的版本,你可以重新pull更新一下试试 3.我明天有时间了再测试一下是不是会有这个问题:)

**Comment by junkojunko** [comment]
@MaybeShewill-CV 好的，谢谢您的提示～😋

**Comment by MaybeShewill-CV** [comment]
@junkojunko I have tested it just now. The tfrecords can be correctly generated. Maybe you should check the image path or some information about python Manager().Queue() module:)
![Screenshot from 2019-04-17 22-19-18](https://user-images.githubusercontent.com/15725187/56296040-51e18680-6160-11e9-9de5-48897d92fc7b.png)
![Screenshot from 2019-04-17 22-27-25](https://user-images.githubusercontent.com/15725187/56296049-55750d80-6160-11e9-96d0-14680b79047a.png)

**Comment by junkojunko** [comment]
@MaybeShewill-CV 好的，我好好检查一下，看看可不可以运行。

**Comment by junkojunko** [comment]
@MaybeShewill-CV 您好，我解决了，我把tf_io_pipline_fast_tools中的Manager().Queue()改成了multiprocessing.Queue() ，这样可以运行了

**Comment by MaybeShewill-CV** [comment]
@junkojunko 好的：）
