### ISSUE TITLE
how to use the tboard directory files

### ISSUE THREAD

**Issue by MagicCodess** [MaybeShewill-CV/CRNN_Tensorflow#235]
hi~how to use the tboard directory files to get something

**Comment by MaybeShewill-CV** [comment]
@MagicCodess what do you want to get?

**Comment by MaybeShewill-CV** [comment]
@MagicCodess What do you want?

**Comment by MagicCodess** [comment]
@MagicCodess I want to use tensorboard, but there is no log dir generated:(

**Comment by MaybeShewill-CV** [comment]
@MagicCodess The origin tensor board file is too large to upload here:)
