### ISSUE TITLE
Hardware details

### ISSUE THREAD

**Issue by anilreddykumar** [MaybeShewill-CV/CRNN_Tensorflow#236]
Can you please provide the hardware details you used to train this model.?
Also how many days it took for you to run 2000000 epochs.?

**Comment by MaybeShewill-CV** [comment]
@anilreddykumar Two gtx 1070 ti gpu , 32G RAM and i7 6700k cpu. Sorry I forgot how long it took me to run over the whole epochs:)

**Comment by anilreddykumar** [comment]
Thanks for the answer. Just curious to know whether you could try it on icdar-2019 dataset.

**Comment by anilreddykumar** [comment]
@MaybeShewill-CV  any idea how this model performs , compared to https://github.com/Calamari-OCR/calamari .?

**Comment by MaybeShewill-CV** [comment]
@anilreddykumar I will train a model on ICDAR 2019 dataset if I got spare time then you may compare it yourself:)

**Comment by anilreddykumar** [comment]
@MaybeShewill-CV Thank you. Please let me know once you trained.

**Comment by MaybeShewill-CV** [comment]
@anilreddykumar Ok:)
