### ISSUE TITLE
it's very beautiful work!

### ISSUE THREAD

**Issue by jesen8** [MaybeShewill-CV/CRNN_Tensorflow#237]
thanks so much~. can you give me your QQ?

**Comment by MaybeShewill-CV** [comment]
@jesen8 What do you want?:)

**Comment by jesen8** [comment]
emmm, just want to add you and  call you 大佬~,I've become a fan of yours

**Comment by MaybeShewill-CV** [comment]
@jesen8 .......==! qq基本不用了。你是谁啊 是不是认识我啊==!

**Comment by jesen8** [comment]
那就微信嘛，不认识你，就想认识认识大佬

**Comment by jesen8** [comment]
我对四平路有着执着的记忆

**Comment by MaybeShewill-CV** [comment]
@jesen8 howard327 WeChat:)

**Comment by MaybeShewill-CV** [comment]
@jesen8 .......我怎么感觉你好像认识我。。。。

**Comment by jesen8** [comment]
哈哈，你前女友

**Comment by MaybeShewill-CV** [comment]
@jesen8 。。。。。。666
