### ISSUE TITLE
Where are the char dict & ord map dict path located? 

### ISSUE THREAD

**Issue by brucezcg** [MaybeShewill-CV/CRNN_Tensorflow#239]
I can find the char-dict path:
CRNN_Tensorflow-master\data\char_dict
But where is the path located?
--ord_map_dict_path PATH/TO/ORD_MAP_PATH
Thanks.

**Comment by MaybeShewill-CV** [comment]
@brucezcg You may find them here https://github.com/MaybeShewill-CV/CRNN_Tensorflow/tree/master/data/char_dict

**Comment by ahappycutedog** [comment]
@brucezcg  I also have the same problem as you, where is this path?

**Comment by ahappycutedog** [comment]
@MaybeShewill-CV  Datasets and pre-training weights seem to be difficult to download due to network reasons. Is there any other way to download them?

**Comment by MaybeShewill-CV** [comment]
@ahappycutedog Sorry for that. You may need a vpn though:)
