### ISSUE TITLE
字典如何设置

### ISSUE THREAD

**Issue by duxiangkun** [MaybeShewill-CV/CRNN_Tensorflow#240]
你好，我想使用你的预训练模型做fine-tuninig，我的字典有4213个字符，请问训练时候送进去的字典是什么？

**Comment by MaybeShewill-CV** [comment]
@duxiangkun 你可以查看./data/char_dict_map.json查看数据集中的字符情况:)

**Comment by duxiangkun** [comment]
我的数据集生成的字符数为4213，现在我想使用你的模型做fine-tuning，您的模型的num_classes为5825，那我训练时候给的json文件是用你给出的char_dict_cn.json吗

**Comment by MaybeShewill-CV** [comment]
@duxiangkun 如果你的字符是我给出的字符集的子集的话可以使用否则不可以:)

**Comment by duxiangkun** [comment]
@MaybeShewill-CV 那我只能自己训练了是吧，谢谢了。

**Comment by MaybeShewill-CV** [comment]
@duxiangkun 如果不是子集的话不能用我的这个json文件:)
