### ISSUE TITLE
Getting error when changing training image size (height)

### ISSUE THREAD

**Issue by guddulrk** [MaybeShewill-CV/CRNN_Tensorflow#242]
Hi,
I am trying to train this network on a custom dataset, where all images have 100x64 size. When I train the network I get the following error:

assert shape[1] == 1  # H of the feature map must equal to 1

I have changed the parameters in the global_config file as well.

**Comment by MaybeShewill-CV** [comment]
@guddulrk The input tensor's height should be fixed at 32 if you do not adjust the net. The net will map the image tensor into a sequence vector so the image size need to be fixed.You may refer to the origin paper for details:)
