### ISSUE TITLE
Training Datasets problems

### ISSUE THREAD

**Issue by alexng88** [MaybeShewill-CV/CRNN_Tensorflow#243]
Hello,
  Besides using Synth90K dataset as suggested in README, any other smaller dataset contains number/symbols/letters can be used for training?

Thanks
Alex

**Comment by MaybeShewill-CV** [comment]
@alexng88 You may see if ICDAR have something that may satisfy your need:)

**Comment by alexng88** [comment]
Hello
thanks for your response and I just download from here
https://github.com/cs-chan/Total-Text-Dataset/tree/master/Dataset

however, how to create the annotation file in order for training?  it only contains the image

**Comment by MaybeShewill-CV** [comment]
@alexng88 You may read their introduction I do not know this dataset. You can convert the dataset into synth90k dataset's format then you can start your training process. Good luck:)

**Comment by alexng88** [comment]
thanks!  Actually I tried to use Synth90K database but when I do tfrecords , it shows error like "cannot read xx image"  that's why I want to try other image sets.
Ok so the only accept format for your code is  e.g. 0000_abc123.jpg  abc123  (index_image    ground truth content), right?

**Comment by MaybeShewill-CV** [comment]
@alexng88 If you correctly use the script there should be no problem during generating tfrecords for synth90k dataset. You may paste your error information here. The accept dataset format for the data input pip line here is the same as Synth90k dataset which is not what you said before. You'd better figure out the Synth90k dataset's format:)

**Comment by alexng88** [comment]
HI,
  OK,  let me do it again and paste error here if I see again.  My purpose is to recognize English alphabet / number / symbols (like . / ( )).  So I believe I may need to generate some data contains symbols and numbers,right?  Sounds like Synth90K onlly contains letters.

**Comment by MaybeShewill-CV** [comment]
@alexng88 Yep Synth90k only contains letters. If you want to recognize sequence contains symbols and numbers etc you'd better generate your own training dataset:)
