### ISSUE TITLE
dataset processing trouble

### ISSUE THREAD

**Issue by majestichou** [MaybeShewill-CV/CRNN_Tensorflow#244]
作者您好，因为数据集太大了，需要运行很长时间，所以为了验证代码是否可以跑通，我用数据集中的部分测试集，验证集，训练集图片，生成了对应的tfrecords，但是用evaluate_shadownet.py 函数运行，发现跑不通，总提示tfrecords不存在（路径没有问题）。
<img width="1072" alt="error" src="https://user-images.githubusercontent.com/43713443/57221240-fd2f7e00-7030-11e9-95b0-fa1e9d013b08.png">
想问作者，你的代码逻辑，都是必须要处理整个数据集的图片才可以正常运行吗，只要缺一些图片，代码就跑不通吗（我的情况是这样的）

**Comment by MaybeShewill-CV** [comment]
@majestichou tfrecords文件夹不存在 仔细检查下:)

**Comment by majestichou** [comment]
> @majestichou tfrecords文件夹不存在 仔细检查下:)

多谢作者的解答。新手，望谅解。解决文件夹之后出现预测问题，希望作者看看，怎么解决？
<img width="1089" alt="屏幕快照 2019-05-06 下午7 39 19" src="https://user-images.githubusercontent.com/43713443/57222872-c6f4fd00-7036-11e9-9174-811930267bb5.png">

**Comment by MaybeShewill-CV** [comment]
@majestichou 你的运行环境是什么? 然后你修改过代码么? 请提供一点详细信息:)

**Comment by yzq-123** [comment]
@majestichou 你好，我也是新手，我可以问你点问题吗？

**Comment by yzq-123** [comment]
@majestichou 你好，我也是新手，我可以问你点问题吗，我微信sy18705186987

**Comment by majestichou** [comment]
![image](https://user-images.githubusercontent.com/43713443/57224823-1dfdd080-703d-11e9-8e84-6a4187bc1ffe.png)
用的是macOS,然后环境配置和作者您readme里面提到的是一样的，修改的代码如图所示。如果不修改这部分代码，会报错，因为我没有训练整个训练集。通过改过的代码得到的tfrecords，然后再用evaluate函数去对得到的tfrecords处理，就会出现之前的错误了。

**Comment by MaybeShewill-CV** [comment]
@majestichou mac不是很清楚 因为看你上面的截图预测过程都已经结束了才出错，你先定位到代码的哪一行出错了吧,有可能是mac的matplotlib哪里和linux不一样导致显示图像的时候出问题, 这个错不像是tensorflow的问题:)

**Comment by majestichou** [comment]
> @majestichou mac不是很清楚 因为看你上面的截图预测过程都已经结束了才出错，你先定位到代码的哪一行出错了吧,有可能是mac的matplotlib哪里和linux不一样导致显示图像的时候出问题, 这个错不像是tensorflow的问题:)

好的，谢谢你了！

**Comment by MaybeShewill-CV** [comment]
@majestichou 如果解决了 欢迎分享解决方案给其他人:)

**Comment by majestichou** [comment]
> @majestichou 如果解决了 欢迎分享解决方案给其他
<img width="845" alt="屏幕快照 2019-05-07 上午11 47 08" src="https://user-images.githubusercontent.com/43713443/57270459-f13dcd80-70bd-11e9-92fb-6ebadec8f6a9.png">
mac系统和linux不太一样，解决方法见上图。多谢作者耐心的解答哈！

**Comment by MaybeShewill-CV** [comment]
@majestichou 好的 非常感谢:)
