### ISSUE TITLE
空格识别不出来

### ISSUE THREAD

**Issue by pingzi5233** [MaybeShewill-CV/CRNN_Tensorflow#246]
您好，我用您中文模型进行测试的时候，发现好像空格是识别不出来的，中文的话倒没关系，但是全英文就会导致单词与单词全部黏连在一起，请问有什么解决方法吗？
![1ecea9b48ccc9b72f706757e03fb8147_pdf_recognize_file_raw=true](https://user-images.githubusercontent.com/48909056/57269053-8047e700-70b8-11e9-93c1-677199e2890f.png)

**Comment by MaybeShewill-CV** [comment]
@pingzi5233 因为样本里没有空格：）
