### ISSUE TITLE
中文数据集 （Synthetic Chinese String Dataset）的lexicon文件

### ISSUE THREAD

**Issue by BigPandaCPU** [MaybeShewill-CV/CRNN_Tensorflow#248]
作者您好，下载的您提供的中文数据集中，里面只有图片文件，没有这个lexicon文件，你这个lexicon文件能提供一下吗？或是你那个中文数据集生成的py文件能提供一下吗？我想生成一个我自己的训练数据集。我是把synth90的数据生成过程搞明白了，我知道要训练自己的数据集的话，需要制作自己数据集的lexicon文件。

**Comment by MaybeShewill-CV** [comment]
@BigPandaCPU 那个中文数据集有自己的label文件 你自己按照synth90k数据集的格式生成annotation和lexicon文件就好了:)

**Comment by BigPandaCPU** [comment]
在你提供的这个中文数据集下载链接中，解压后只得到了图片文件，没有找对其对应的label文件了。你说的这个label文件是在哪下载呢？
![image](https://user-images.githubusercontent.com/25834151/57363371-9090bc80-71b3-11e9-80f2-6f1995c5727c.png)
解压后都是图片文件

**Comment by MaybeShewill-CV** [comment]
@BigPandaCPU https://pan.baidu.com/s/1jfAKQVjD-SMJSffOwGhh8A

**Comment by BigPandaCPU** [comment]
这个下载密码是多少呢
![image](https://user-images.githubusercontent.com/25834151/57423857-3d1c7e00-7248-11e9-9912-80dccb0d8fc4.png)

**Comment by MaybeShewill-CV** [comment]
@BigPandaCPU #50 这个里面自己找找吧:)

**Comment by TyrionChou** [comment]
知道密码了没？

**Comment by wandaoyi** [comment]
没找到lexicon文件，要不，晒一下lexicon文件的结构？我们根据结构，自己制作
