### ISSUE TITLE
用其他数据集训练

### ISSUE THREAD

**Issue by majestichou** [MaybeShewill-CV/CRNN_Tensorflow#249]
作者您好，我想训练自己的数据集，这个数据集有图片和对应的label。和您博客中提供的数据集不太一样，并没有annotation和lexicon，我应该如何生成训练数据呀，麻烦指导一下。

**Comment by MaybeShewill-CV** [comment]
@majestichou 我哪个博客?我没有博客啊==! 你有自己的label那么你就按照synth90k数据集的格式自己转换一下就好了:)

**Comment by majestichou** [comment]
> @majestichou 我哪个博客?我没有博客啊==! 你有自己的label那么你就按照synth90k数据集的格式自己转换一下就好了:)

我说的就是你这篇github文章😄。想咨询一下你是lexion-free还是基于lexion的实现呀？用自己的数据集必须要生成相应的json和lexion文件吗？麻烦您了

**Comment by MaybeShewill-CV** [comment]
@majestichou 不是必须要这个lexion文件,只是我现在上传的代码的data feed pip line都是根据synth90k数据集的格式写的,你如果可以实现自己的data feed pip line那么完全可以用你自己的数据标注格式来做:)

**Comment by majestichou** [comment]
> @majestichou 不是必须要这个lexion文件,只是我现在上传的代码的data feed pip line都是根据synth90k数据集的格式写的,你如果可以实现自己的data feed pip line那么完全可以用你自己的数据标注格式来做:)

好的，谢谢耐心的解答。

**Comment by jake221** [comment]
> > @majestichou 不是必须要这个lexion文件,只是我现在上传的代码的data feed pip line都是根据synth90k数据集的格式写的,你如果可以实现自己的data feed pip line那么完全可以用你自己的数据标注格式来做:)
> 
> 好的，谢谢耐心的解答。

你是不是也是英文字符和数字的混合识别？可以加下微信一起交流下吗？我wechat:15651859966
