### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by yzq-123** [MaybeShewill-CV/CRNN_Tensorflow#250]
作者您好，测试一张图片时出现这个错误，请问下这是什么错误？

(crnn1) yzq@yzq-123:~/Music/CRNN_Tensorflow-master$ python tools/test_shadownet.py --image_path Music/CRNN_Tensorflow-master/data/test_images/test_01.jpg --weights_path Music/CRNN_Tensorflow-master/crnn_synth90k/shadownet.ckpt --char_dict_path Music/CRNN_Tensorflow-master/data/char_dict/char_dict.json --ord_map_dict_path Music/CRNN_Tensorflow-master/data/char_dict/ord_map.json
Traceback (most recent call last):
  File "tools/test_shadownet.py", line 159, in <module>
    is_vis=args.visualize
  File "tools/test_shadownet.py", line 76, in recognize
    scale_rate = new_heigth / image.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by MaybeShewill-CV** [comment]
@yzq-123 你的图像没有正确读入 重新检查你的图像文件路径 如果你不能确定你的脚本的启动目录 那你最好使用绝对路径 避免使用相对路径:)

**Comment by yzq-123** [comment]
我图片的路径就是用的绝对路径  --image_path Music/CRNN_Tensorflow-master/data/test_images/test_01.jpg

**Comment by yzq-123** [comment]
@MaybeShewill-CV  我图片的路径就是用的绝对路径 --image_path Music/CRNN_Tensorflow-master/data/test_images/test_01.jpg

**Comment by MaybeShewill-CV** [comment]
@yzq-123 你确定这是绝对路径? Music是什么目录==! 你cd到test_images这个目录看看pwd的输出值吧==!

**Comment by yzq-123** [comment]
@MaybeShewill-CV 好的，谢谢作者指导了，刚接触linux系统和深度学习，还有很多地方不明白，望见谅==！

**Comment by MaybeShewill-CV** [comment]
@yzq-123 不客气 没有问题的话我关闭issue了:)

**Comment by yzq-123** [comment]
@
