### ISSUE TITLE
训练synth90数据时，报错  Failed to convert object of type <class 'list'> to Tensor. Contents: [Dimension(None), 32, 100, 3].

### ISSUE THREAD

**Issue by BigPandaCPU** [MaybeShewill-CV/CRNN_Tensorflow#251]
作者，您好：
      我在训练synth90这个数据集的时候，报了错，截图如下：
![image](https://user-images.githubusercontent.com/25834151/57424942-09dbee00-724c-11e9-9a4a-249acae7327f.png)

定位源代码如下：
![image](https://user-images.githubusercontent.com/25834151/57424989-2b3cda00-724c-11e9-9f5f-d8a2c0ce8b29.png)
这里在将list装成tensor的时候，报错了，我百度了一下，还没找到原因

**Comment by MaybeShewill-CV** [comment]
@BigPandaCPU 应该和tensorflow版本有关系 我本地的版本是1.12 你可以切换到这个版本重新测试:)

**Comment by BigPandaCPU** [comment]
问题找到了，之前是我这tf的版本不对，读取TFRecord数据时，
dataset = dataset.batch( batch_size, drop_remainder=True) 报错，
我改为 dataset = dataset.batch( batch_size)后，不报错，但就出现了上面那个问题，读取tfRecord的时候，数据取不出来，导致后面 reshape的时候，出现none，导致失败。

现在已经在我本地跑通整个训练、测试流程了，谢谢作者的分享和耐心回答。
下图训练过程输出的截图。
![image](https://user-images.githubusercontent.com/25834151/57432731-3eaa6e00-7269-11e9-826c-ea53351e7249.png)

**Comment by BigPandaCPU** [comment]
> 问题找到了，之前是我这tf的版本不对，读取TFRecord数据时，
> dataset = dataset.batch( batch_size, drop_remainder=True) 报错，
> 我改为 dataset = dataset.batch( batch_size)后，不报错，但就出现了上面那个问题，读取tfRecord的时候，数据取不出来，导致后面 reshape的时候，出现none，导致失败。
> 
> 现在已经在我本地跑通整个训练、测试流程了，谢谢作者的分享和耐心回答。
> 下图训练过程输出的截图。
> ![image](https://user-images.githubusercontent.com/25834151/57432731-3eaa6e00-7269-11e9-826c-ea53351e7249.png)
