### ISSUE TITLE
evaluate_shadownet.py 中 Mean test full sequence accuracy 计算错误

### ISSUE THREAD

**Issue by Once88** [MaybeShewill-CV/CRNN_Tensorflow#252]
当测试数据中某些样本的label有重复时，evaluate_shadownet.py 中 Mean test full sequence accuracy 计算结果错误。原因来自`avg_accuracy = len(set(ground_truth).intersection(predictions)) / len(ground_truth)` 此处会自动去重导致结果错误。

**Comment by MaybeShewill-CV** [comment]
@Once88 是你的数据集存在不同的图像对应同一个标签的情况吗?：）

**Comment by Once88** [comment]
是的：）

**Comment by MaybeShewill-CV** [comment]
@Once88 ==! 那确实是会计算错误 我现在的数据集都是没有重复label的所以没有考虑到这个地方 如果方便体格pr呗 谢谢:)
