### ISSUE TITLE
The accuracy of  per char and  full sequence tested is incorrect

### ISSUE THREAD

**Issue by yzq-123** [MaybeShewill-CV/CRNN_Tensorflow#255]
作者，您好！在测试数据集的时候，准确率和您的不同。不知是什么原因？还望指导下！
I0511 11:13:06.642651 3701 evaluate_shadownet.py:181] Predict 147_CESSPITS_12501.jpg image with gt label: cesspits **** predicted label: mr77t0p7
I0511 11:13:06.642686 3701 evaluate_shadownet.py:181] Predict 138_continents_16550.jpg image with gt label: continents **** predicted label: m51p01r1p7
I0511 11:13:06.642720 3701 evaluate_shadownet.py:181] Predict 129_Evilness_26925.jpg image with gt label: evilness **** predicted label: r40s1r77
E0511 11:13:06.679945 3701 evaluate_shadownet.py:209] End of tfrecords sequence
I0511 11:13:06.680186 3701 evaluate_shadownet.py:217] Mean test per char accuracy is 0.033470
I0511 11:13:06.680294 3701 evaluate_shadownet.py:218] Mean test full sequence accuracy is 0.000010
I0511 11:13:15.887930 3701 evaluation_tools.py:87] Normalized confusion matrix
[[0.00e+00 1.21e-03 0.00e+00 ... 0.00e+00 0.00e+00 0.00e+00]
 [2.91e-02 1.04e-03 0.00e+00 ... 1.04e-03 0.00e+00 4.16e-03]
 [1.56e-03 1.56e-03 0.00e+00 ... 3.12e-03 0.00e+00 0.00e+00]
 ...
 [1.82e-03 5.65e-03 1.92e-04 ... 4.65e-03 9.65e-01 0.00e+00]
 [1.14e-03 8.45e-04 1.61e-03 ... 8.45e-04 1.32e-04 0.00e+00]
 [6.13e-03 1.69e-03 2.08e-03 ... 1.81e-03 7.24e-04 3.02e-05]]

**Comment by MaybeShewill-CV** [comment]
@yzq-123 测试的数据集如果是synth90k数据集 那么最可能的问题就是你生成tfrecords用的json文件和测试的时候用的不是同一个:)

**Comment by yzq-123** [comment]
@MaybeShewill-CV 我用的是synth90k数据集，我想问下，生成tfrecord和测试用的json文件是哪个？我有点模糊。

**Comment by yzq-123** [comment]
@MaybeShewill-CV 我用的是synth90k数据集，我想问下，生成tfrecord和测试用的json文件是哪个？我有点模糊。

**Comment by MaybeShewill-CV** [comment]
@yzq-123 你测试的时候输入的两个参数:)

**Comment by yzq-123** [comment]
@MaybeShewill-CV  哦哦，我用的是一样的json文件，但还是出现了这个问题。请问还有其他的原因吗？

**Comment by MaybeShewill-CV** [comment]
@yzq-123 我本地测试没有问题 需要你自己排查你拿里操作不一样了:)

**Comment by yzq-123** [comment]
好的，谢谢作者，我先看看，有问题再请教您！
