### ISSUE TITLE
请问INPUT_SIZE这个参数如何设置

### ISSUE THREAD

**Issue by seagullyoyo** [MaybeShewill-CV/CRNN_Tensorflow#256]
目标是使用自定义数据集进行训练，训练数据中图片输入3到10个字符不等。请教下，INPUT_SIZE 如果是固定的，width 应该取 max 么？如果取max，3个字符或较短字符的图片样本，会被resize失真。请问有什么解决办法呢。

**Comment by MaybeShewill-CV** [comment]
@seagullyoyo 可以在图像后面增加空白补齐:)

**Comment by seagullyoyo** [comment]
ok，这样补齐到max width然后resize的做法合理么，常规做法是这样么

**Comment by MaybeShewill-CV** [comment]
@seagullyoyo 你自己实验验证吧:)
