### ISSUE TITLE
写入tfrecord卡住

### ISSUE THREAD

**Issue by junkojunko** [MaybeShewill-CV/CRNN_Tensorflow#257]

**Comment by junkojunko** [comment]
![Screenshot from 2019-05-12 20-11-44](https://user-images.githubusercontent.com/39071180/57582032-855ec900-74f2-11e9-98a6-0a101835a36d.png)

**Comment by MaybeShewill-CV** [comment]
@junkojunko 可以问一下用的是什么数据集么:)

**Comment by junkojunko** [comment]
我用的中文数据集，等了半小时，已经过去了，之前用pycharm总是卡死，这次用terminal就卡了一会儿

**Comment by junkojunko** [comment]
还有一个问题就是我大概拿了中文数据集中的2w张左右的图片来当测试集，但是每个预测标签都是错的，而且跑着跑着提示内存不足，我已经给提高到6G还是内存不足，我的内存是12g，怕给内存调的太高电脑卡死。

**Comment by keerchaokeai** [comment]
@junkojunko 您好能教一下我怎么生成tfrecord嘛，十分感谢

**Comment by keerchaokeai** [comment]
@junkojunko 如果可以，请加我微信love_qinging
