### ISSUE TITLE
关于中文数据集的evaluate

### ISSUE THREAD

**Issue by junkojunko** [MaybeShewill-CV/CRNN_Tensorflow#258]
博主你好，问一下儿我训练好的中文字符集，想获得accuracy的图，在运行evaluated_shadownet的时候发现每个预测的标签都是错的，但是单个图片的标签很好。是不是因为evaluation_tools中的syth90k_classnames的分类不同呢。

**Comment by junkojunko** [comment]
我将syth90k_classname都改成了有5800多个字符的list，但是依旧分类很不好。预测标签和给定标签并不相同

**Comment by MaybeShewill-CV** [comment]
@junkojunko 应该是标签的对应关系不一致导致的 只要你确保第一次生成json文件之后没有修改这个文件就可以了:)
