### ISSUE TITLE
识别错误率较高

### ISSUE THREAD

**Issue by loooong** [MaybeShewill-CV/CRNN_Tensorflow#260]
您好，我用了您的中文识别模型。发现用在扫描件上的效果不是很好。请教您下：）
![66_sample_21](https://user-images.githubusercontent.com/8617946/57615295-f1523780-75ad-11e9-9c60-90b243135df2.png)
![66_sample_16](https://user-images.githubusercontent.com/8617946/57615281-ec8d8380-75ad-11e9-8c46-306665af4d2e.png)

**Comment by MaybeShewill-CV** [comment]
@loooong 如果没记错的话 那个中文数据集中不包含数字 你可以先查看下那个数据集:)

**Comment by loooong** [comment]
您好，是包含的。下面这个图片就能够很好的识别。
![66_sample_0](https://user-images.githubusercontent.com/8617946/57619055-97566f80-75b7-11e9-9321-dfdebeb13c0a.png)

我想到一个方法是用生成接近印刷体的字符。[参考项目](https://github.com/AstarLight/CPS-OCR-Engine) 。看是否能够训练处一个合适的模型。弄完了还不清楚，再来请教您。

**Comment by MaybeShewill-CV** [comment]
@loooong 那可能是由于图像尺寸不同在resize的时候失真比较严重导致的识别错误:)
