### ISSUE TITLE
大佬求助

### ISSUE THREAD

**Issue by Daybreak000** [MaybeShewill-CV/CRNN_Tensorflow#261]
作者你好，我是一名大学本科生，现在在做毕业论文，内容是CRNN_Tensorflow识别文本，看了你的代码，感觉有很大帮助，但还是有一些问题不懂，能不能加一下我的qq：1033495317.帮我讲解一下，万分感谢🙏

**Comment by MaybeShewill-CV** [comment]
@Daybreak000 不方便加qq，抱歉：）

**Comment by Daybreak000** [comment]
请问是在哪里用到ctc的？

**Comment by MaybeShewill-CV** [comment]
@Daybreak000 计算loss 具体可以看代码:)

**Comment by Daybreak000** [comment]
请问ord_map_en和char_dict_en分别代表什么意思？

**Comment by MaybeShewill-CV** [comment]
@Daybreak000 字符 <==> ascii码 <==> label index之间的映射关系

**Comment by Daybreak000** [comment]
好的 谢谢

**Comment by Daybreak000** [comment]
请问代码是用的有词库的识别还是没有词库的识别？

**Comment by Daybreak000** [comment]
请问代码是用的有词典的识别还是没有词典的识别？
