### ISSUE TITLE
How Synth90k dataset is constructed?

### ISSUE THREAD

**Issue by Abdulazizbek** [MaybeShewill-CV/CRNN_Tensorflow#264]
I want to create dataset like `Synth90k` for the Korean language.
I have some idea about it, But for better understanding, I couldn't find any documentation about how the Synth90k dataset is collected and what does it mean text files:
`annotation.txt` file:
./3000/7/182_slinking_71711.jpg `71711`
./3000/7/181_REMODELERS_64541.jpg `64541`
./3000/7/180_Chronographs_13538.jpg `13538`
...
and how this text file is related to `lexicon.txt` file

Thank you for your assist

**Comment by MaybeShewill-CV** [comment]
@Abdulazizbek The number in annotation.txt file eg 71711 means you can find it's corresponding lexicon label in line 71711 of lexicon.txt file==!

**Comment by kiclent** [comment]
IF  I want to use the  [Synthetic Chinese Data Set](https://pan.baidu.com/s/1ufYbnZAZ1q0AlK7yZ08cvQ)  , should I build the `lexicon.txt` to generate the `char_map.json` and `ord_map.json` ?
OR use the exist file `char_map.json` and `ord_map.json` that you provided ?
