### ISSUE TITLE
预测标签

### ISSUE THREAD

**Issue by Daybreak000** [MaybeShewill-CV/CRNN_Tensorflow#265]
请问循环层最后的到的概率是多少维的？是不是最终预测标签里面只有26个英文字母和数字？

**Comment by MaybeShewill-CV** [comment]
@Daybreak000 如果使用synth90k数据集那么只包含26个英文和数字. 使用中文数据集则包含多个汉字和数字. 类别信息可以查看config文件和相关的json文件:)

**Comment by Daybreak000** [comment]
文本识别的评价指标有哪些呢？

**Comment by MaybeShewill-CV** [comment]
@Daybreak000 可以自己去论文上找
