### ISSUE TITLE
Training with Chinese dataset

### ISSUE THREAD

**Issue by Abdulazizbek** [MaybeShewill-CV/CRNN_Tensorflow#269]
I have several questions about training Chinese character recognition from scratch.
I downloaded Chinese dataset from your provided link. But I couln't find explanation how dataset constructed, how to decode label? lexicon file
label:
`20456343_4045240981.jpg 89 201 241 178 19 94 19 22 26 656`
image name, then 10 numbers, which, some 8 coordinates and what is next. 

Where I can find Chinese characters list (num_of_classes = 5825, for English 37 classes)? 
I browsed issues, but couldn't get the point.
Please, could you provide guideline to train Chinese dataset from scratch.

**Comment by MaybeShewill-CV** [comment]
@Abdulazizbek 1.Download the chinese dataset 2.Format the dataset according to the synth90k dataset's format 3.Make tfrecords according to the README file in my repo 4.Start your training process:)

**Comment by Abdulazizbek** [comment]
In synth90k dataset everything is clear:
image, word and corresponding lexicon file.

Could you Please provide some py file or some other thing to format, how to Format the dataset according to the synth90k dataset's format:
There is some confusion what does this 10 numbers mean?
`20456343_4045240981.jpg 89 201 241 178 19 94 19 22 26 656`

**Comment by MaybeShewill-CV** [comment]
@Abdulazizbek It seems that you're familiar with Synth90k dataset.The chinese dataset contains image and it's corresponding chinese text label you may convert them into Synth90k dataset's format easily:)

**Comment by Abdulazizbek** [comment]
Yes, I am good  familiar with Synth90k dataset.
I'm sorry for my asking again and again. I couldn't figure out what does it means this words in Chinese dataset.  Please, if there is any link or documentation could you provide. Thank you beforehand for your time and passion
varzik91@gmail.com

**Comment by MaybeShewill-CV** [comment]
@Abdulazizbek The label is something like that 
![Screenshot from 2019-05-30 10-35-47](https://user-images.githubusercontent.com/15725187/58604391-c0b91000-82c6-11e9-8dc0-c3f9d1abad38.png). You may find the dataset url in closed issue yourself:)

**Comment by Abdulazizbek** [comment]
Thank you. My downloaded labeled files were totally different than that you provided. 

![image](https://user-images.githubusercontent.com/15800037/58611292-97f64200-82e9-11e9-8eaf-ff05970a4250.png)

I found a link from closed issues, but couldn't find extraction code download. 
Could you provide a password, please

**Comment by MaybeShewill-CV** [comment]
@Abdulazizbek You may find it here https://blog.csdn.net/Sierkinhane/article/details/82857572
