### ISSUE TITLE
test多张图片（比如一万多张）

### ISSUE THREAD

**Issue by CharlesWu123** [MaybeShewill-CV/CRNN_Tensorflow#271]
你好，大神，我想test多张图片该怎么做呢，因为每次的inputdata的new_width都是不一样的。我把session放在了for循环里边，这样的话随着处理的图片增多，时间会不断的增加，太浪费时间了。求大神给出建议。

**Comment by MaybeShewill-CV** [comment]
@CharlesWu123 因为现在没有办法批处理尺寸不一样的tensor 所以要么你把所有的图像都归一化到同样的尺寸要么一张一张的处理:)

**Comment by CharlesWu123** [comment]
归一化到同样的尺寸，使用强制缩放比较好；还是使用同比例的缩放，然后再进行crop和pad比较好？
还有一个问题，现在test每张图片（280x32）的时间达到了3秒每张，有什么办法可以减少时间呢？
谢谢大神解答:)

**Comment by MaybeShewill-CV** [comment]
@CharlesWu123 1.强制缩放肯定会使图像失真影响检测结果 2.如果是正常使用gpu,单张图像的预测时间不会这么久, 你可以自己检查还有什么地方操作不对:)

**Comment by CharlesWu123** [comment]
1.不使用强制缩放的话，那就按照32的高度等比例缩放图片后，根据最长的图片对其他的图片进行pad，但是这样的话会增加那些小图片的预测时间，如果长图片特别长，短图片特别短，这样影响会更大（或许还有其他的什么办法？）
2.时间方面的话我再检查检查
谢谢大神了！

**Comment by CharlesWu123** [comment]
<img src="https://img-blog.csdnimg.cn/20190531130805185.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L20wXzM4MDA3Njk1,size_16,color_FFFFFF,t_70">
你好，大神，这是我预测一张图片的时间，代码没有改过，GPU是1080Ti 的，预测时间在2s左右

**Comment by MaybeShewill-CV** [comment]
@CharlesWu123 第一次启动的时候gpu 需要warm up 你最好循环测试然后求平均值:)
