### ISSUE TITLE
输出结果为空或乱码

### ISSUE THREAD

**Issue by Loovelj** [MaybeShewill-CV/CRNN_Tensorflow#272]
您好，请问我在dropbox下载了最新的ckpt，并修改了glob_config
`
![22222](https://user-images.githubusercontent.com/10558917/58762365-09e8b880-8582-11e9-9df8-528d3da7fe5b.png)

我的执行语句是
`
python3 tools/test_shadownet.py --image_path /root/ubuntu/crnn/data/test_images/test_01.jpg \
--weights_path /root/ubuntu/crnn/model/ch_model/shadownet.ckpt \
--char_dict_path /root/ubuntu/crnn/data/char_dict/char_dict_cn.json \
--ord_map_dict_path /root/ubuntu/crnn/data/char_dict/ord_map_cn.json
`

结果预测结果为空
![微信截图_20190602215519](https://user-images.githubusercontent.com/10558917/58762340-c68e4a00-8581-11e9-97ae-318362b488c5.png)

我换了几个测试图，也是偶尔出来一个数字

请问，我是需要在哪里修改吗

**Comment by MaybeShewill-CV** [comment]
@Loovelj 汉字的话需要手动修改https://github.com/MaybeShewill-CV/CRNN_Tensorflow/blob/master/tools/test_shadownet.py文件６４行is_english=False 来避免使用英文分词工具:)

**Comment by Loovelj** [comment]
> @Loovelj 汉字的话需要手动修改[https://github.com/MaybeShewill-CV/CRNN_Tensorflow/blob/master/tools/test_shadownet.py文件６４行is_english=False](https://github.com/MaybeShewill-CV/CRNN_Tensorflow/blob/master/tools/test_shadownet.py%E6%96%87%E4%BB%B6%EF%BC%96%EF%BC%94%E8%A1%8Cis_english=False) 来避免使用英文分词工具:)

嗯，是这个问题，已解决，谢谢
