### ISSUE TITLE
用另外公开数据集训练模型遇到的问题

### ISSUE THREAD

**Issue by wx1111** [MaybeShewill-CV/CRNN_Tensorflow#273]
用其他公开数据集训练模型，训练集上cost下降的很快，准确率也可以到0.98+；但是在验证集和测试集上，cost维持在20左右，准确率也非常差，几乎为0，看了下验证时的输出，基本是一样的。一开始考虑是bn层以及dropout层training参数设置的问题，将验证和测试的phase参数均设置为train后，问题依旧存在，验证集和测试集准确率到0.3左右，但是和训练集上为1的准确率差距依旧很大。并且看代码中BN参数更新是按照tf推荐方式做的。请问作者有什么建议吗，从哪里开始排除问题呢？ps：config文件没有动。tfrecord数据也已经检查。谢谢。
![image](https://user-images.githubusercontent.com/39900603/58896204-1dce1f00-8728-11e9-822f-1b30205618ed.png)

**Comment by MaybeShewill-CV** [comment]
@wx1111 1.你可以先验证一下在synth90k数据集上是否能正常训练 2.你的这个公开数据集是什么字符构成的,你是使用了我预先提供的两个json文件还是自己生成的json文件, 训练和预测过程是否使用了同一份json文件 3.这个公开数据集是否方便提供链接,有时间我可以自己也验证一下是否有你说的的这个问题:)

**Comment by wx1111** [comment]
@MaybeShewill-CV 谢谢回复。
 1.synth90k数据集数据集太大，目前无法在这个数据集上测试。
2.使用了新生成的json文件，训练和验证使用的是同一个json文件。
3.我使用的是 Incidental Scene Text 2015 数据集 （https://rrc.cvc.uab.es/?ch=4&com=downloads）
另外，我尝试过训练数据和验证数据用同一组数据，将phase参数都设置为train时，训练集和验证集准确率相近，但不是完全一样。

**Comment by MaybeShewill-CV** [comment]
@wx1111 １．好的有时间我看看这个数据集

**Comment by wx1111** [comment]
@MaybeShewill-CV 谢谢。另外，我是将训练数据集中word_1.png到word_99.png做了验证集。

**Comment by MaybeShewill-CV** [comment]
@wx1111 1.我看了一下这个数据集然后做了一个简单的实验,并没有出现val的准确率几乎为零的情况.2.但是这个数据集的数据量非常小，非常容易出现过拟合情况, 而且我现在上传的代码没有任何augmentation 3.这个数据集中的图像不像synth90k数据集,它的数据形状差异比较大，而我现在的处理会统一resize 这会造成许多图像严重失真 4.我没有使用数据集中的coord.txt文件将文字区域从原本提供的图像中抠取出来.5.训练中间结果截图如下
![crnn_train_log](https://user-images.githubusercontent.com/15725187/59003729-b0b2aa80-8849-11e9-8125-fc9c8038e542.png)
![crnn_train_log2](https://user-images.githubusercontent.com/15725187/59003732-b4463180-8849-11e9-970e-ef0838fab286.png)
![1](https://user-images.githubusercontent.com/15725187/59003823-0be49d00-884a-11e9-97ec-619255bd3b70.png)
![2](https://user-images.githubusercontent.com/15725187/59003829-0edf8d80-884a-11e9-98c0-a0d4db0aa044.png)

**Comment by wx1111** [comment]
@MaybeShewill-CV 谢谢您所做的实验，关于您的结果，我有几个不明白的地方：1.您现在的配置是什么样的呢？hidden layers之类的，图像resize的大小，num_classes等；2.您这边使用的json文件是在生成tfrecord时新生成吗？3.您是在预训练模型上fine-tune还是重头开始训练呢？再次谢谢您的回复。

**Comment by MaybeShewill-CV** [comment]
@wx1111 1.网络没有改变 2.图像resize的大小和global config中的英文实验使用的配置相同，num classes可以根据你提供的标签集自己计算 3.json文件是生成tfrecords的时候自动生成的 4.模型训练是从头开始没有finetune:)

**Comment by wx1111** [comment]
@MaybeShewill-CV 您好，我这边大致复现出了您的实验结果。但是我发现一个现象：当batch size设置为32时，验证集accuracy=0.729，cost=14.86；当batch size设置为256时，验证集accuracy=0.202535,cost= 49.625313。请问下，这个是因为什么呢，另外我的实验过程中验证集cost始终较大。
![image](https://user-images.githubusercontent.com/39900603/59239497-45474f00-8c34-11e9-90ec-a26b2299297c.png)
![image](https://user-images.githubusercontent.com/39900603/59239519-54c69800-8c34-11e9-8a73-da3c527d3ea5.png)

**Comment by MaybeShewill-CV** [comment]
@wx1111 实验过程中验证集cost大说明过拟合了 这个数据集样本太少了 你可能需要自己做数据增强然后可能改变图像对齐的方式不能直接resize这样：）

**Comment by litch-cl** [comment]
> 用其他公开数据集训练模型，训练集上cost下降的很快，准确率也可以到0.98+；但是在验证集和测试集上，cost维持在20左右，准确率也非常差，几乎为0，看了下验证时的输出，基本是一样的。一开始考虑是bn层以及dropout层training参数设置的问题，将验证和测试的phase参数均设置为train后，问题依旧存在，验证集和测试集准确率到0.3左右，但是和训练集上为1的准确率差距依旧很大。并且看代码中BN参数更新是按照tf推荐方式做的。请问作者有什么建议吗，从哪里开始排除问题呢？ps：config文件没有动。tfrecord数据也已经检查。谢谢。 ![image](https://user-images.githubusercontent.com/39900603/58896204-1dce1f00-8728-11e9-822f-1b30205618ed.png)

您好，请问您是如何制作数据集的，我看这个数据集没有ID
