### ISSUE TITLE
RuntimeError : freeze_support()

### ISSUE THREAD

**Issue by wangning316** [MaybeShewill-CV/CRNN_Tensorflow#278]
Thank you for your excellent work，I tested it in Windows, an exception occured：
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

it seems to be caused by the difference in multiple processing between Windows and Linux. 
I tried this  https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing    but it dosen't work.
Could you help me some advice?

**Comment by MaybeShewill-CV** [comment]
@wangning316 You may check this #238

**Comment by wangning316** [comment]
@MaybeShewill-CV Appreciate,it works

**Comment by MaybeShewill-CV** [comment]
@wangning316 You're welcome:)
