### ISSUE TITLE
关于tensorflow CTC使用的问题

### ISSUE THREAD

**Issue by Pay20Y** [MaybeShewill-CV/CRNN_Tensorflow#279]
您好，我想请教关于tf.nn.ctc_loss和tf.nn.ctc_beam_search_decoder两个api的使用问题。这两个函数都有一个sequence_length的参数，在您的代码中由于所有的图片都reshape成了相同的大小，所以这个参数的大小是一个25的list，如果我每一张图片保持长宽比的reshape，然后padding成一样的长度的话，这个参数是否应该是每个图片实际长度的一个list呢？谢谢！

**Comment by Pay20Y** [comment]
同样在stack_bidirectional_dynamic_rnn中这个参数是否也应该那样设置呢？谢谢！

**Comment by MaybeShewill-CV** [comment]
@Pay20Y padding成一样的长度了就可以:)

**Comment by Pay20Y** [comment]
> 
> 
> @Pay20Y padding成一样的长度了就可以:)

感谢你的回复，我的意思是padding成一样长度后，ctc函数的sequence_length是实际长度一个list还是统一的padding长度的list呢?

**Comment by MaybeShewill-CV** [comment]
@Pay20Y .....没明白你在说什么＝＝！　sequence length长度就是通过cnn得到的feature vec长度：）

**Comment by Pay20Y** [comment]
> @Pay20Y .....没明白你在说什么＝＝！　sequence length长度就是通过cnn得到的feature vec长度：）

呃 抱歉，我表述的不好，我理解的可能有点问题，感谢您的回复~
