### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by chenhaofen** [MaybeShewill-CV/CRNN_Tensorflow#280]
作者你好:十分感谢你的分享。我想问一问你提供的预训练模型我用起来准确相对来说有点差。可以放一个在百度云盘吗?还有在百度云盘的中文数据集也缺少了标签

**Comment by MaybeShewill-CV** [comment]
@chenhaofen 这个数据集不是我的数据集,关于标签问题你可以在以前关闭的issue里面找,有标签的地址链接.模型准确率差是因为在这个数据集上训练的模型无法很有效的泛华到你使用的场景,你可以尝试一些迁移学习的方法或者使用自己的训练数据:)

**Comment by chenhaofen** [comment]
1:我的意思是拿了你的预训练模型然后取预测你代码里面的testimages目录下的也不是那么准确

2:训练中文的时候打包成tfrecord的方法是不是也是用打包synth90k的方法,不过是要稍微改改代码?

3:作者  还有个问题想问一下,对于手写字体的,准确率的会高吗?我目前

**Comment by MaybeShewill-CV** [comment]
@chenhaofen 1.那你拿的预训练模型可能不对，或者你调用程序的方式不是按照readme中的使用方法调用的，否则应该会得到和readme中一样的结果
2.不需要修改代码,只需要你按照synth90k数据集的格式来组织中文数据集.否则你需要修改代码来实现自己的data feed pipline
3.手写字体也是没有问题的:)
