### ISSUE TITLE
训练时候的输入和测试时候的输入不一样

### ISSUE THREAD

**Issue by chenhaofen** [MaybeShewill-CV/CRNN_Tensorflow#282]
作者你好:
训练的时候输入的是    高(32)*宽(280)
测试的时候: 例如图片是高(56)*宽(480)

测试的时候并不是跟训练一样变成高(32)*宽(280)
而是变成了 高(32) 这个和训练一样    但是宽就是 (280/480)*480 算出了一个比例来调整训练图片的宽。并且处理的方法和训练时的方法不太一样，这是为什么呢?  这样的话训练过的样本输入进去,也有可能预测出来是错的。

如果直接变成和训练时候的输入一样,输入训练过的样本都是正确的。我想知道这个原因，谢谢作者。已经标星了,在这里学到了好多。我对ocr这块实在是菜鸟。感谢作者的回答

**Comment by MaybeShewill-CV** [comment]
@chenhaofen 因为强行把图像resize到(280, 32)很可能会造成图像很大程度上的失真，是出于这个考虑这样操作的:)

**Comment by chenhaofen** [comment]
明白明白  如果我的图片普遍比较大  有一部分都是集中在70*700的样子  我在训练的时候以70*700的样子训练这个可以的吗?

**Comment by MaybeShewill-CV** [comment]
@chenhaofen 针对现在的模型不可以,你得需要修改网络结构:)

**Comment by chenhaofen** [comment]
嗯 好的。我尝试一下。谢谢作者的耐心回答。十分感谢

**Comment by MaybeShewill-CV** [comment]
@chenhaofen ok :)
