### ISSUE TITLE
小白想请问一下，数据集我已经下下来了，作者说的路径这里要怎么改啊，弄了两天了都没成功，希望得到大家的帮助

### ISSUE THREAD

**Issue by keerchaokeai** [MaybeShewill-CV/CRNN_Tensorflow#283]
![image](https://user-images.githubusercontent.com/47933430/59893184-b47c2a80-940e-11e9-991a-a48a8e109ddf.png)

**Comment by MaybeShewill-CV** [comment]
@keerchaokeai 你这个文章出处在哪里啊＝＝！
