### ISSUE TITLE
中文训练数据问题

### ISSUE THREAD

**Issue by TyrionChou** [MaybeShewill-CV/CRNN_Tensorflow#284]
作者您好，我下载了中文数据8.6g数据，解压缩后只有images文件夹，没有标注数据，请问这个包里面包含图片的label吗？还是说怎么处理？

**Comment by MaybeShewill-CV** [comment]
@TyrionChou 你可以在close issue里面找到标签地址：）

**Comment by TyrionChou** [comment]
标签在这个网址里https://blog.csdn.net/Sierkinhane/article/details/82857572，网盘地址：https://pan.baidu.com/s/1jfAKQVjD-SMJSffOwGhh8A，密码：u7bo
