### ISSUE TITLE
create own dataset

### ISSUE THREAD

**Issue by ahare1535** [MaybeShewill-CV/CRNN_Tensorflow#285]
想請問 tools/write_text_features 有釋出嗎？感謝！

**Comment by MaybeShewill-CV** [comment]
@ahare1535 释出?

**Comment by keerchaokeai** [comment]
> 想请问工具/ write_text_feature你好，你也在应用这个模型吗，我有个错误解释不了能帮我看一下吗，微信love_qinging，非常感谢

**Comment by ahare1535** [comment]
![messageImage_1561427072657](https://user-images.githubusercontent.com/40626539/60063001-ebfc1700-972d-11e9-83d8-0cfc59a9d187.jpg)
這個.py沒有在tools裡面

**Comment by MaybeShewill-CV** [comment]
@ahare1535 不好意思是我的readme名字写错了 感谢纠正 应该是write_tfrecords.py 我已经更正了README文件:)

**Comment by ahare1535** [comment]
不好意思
因為我要用自己的dataset
請問可以提供 write_tfrecords.py 所以使用的SYNTH90K dataset的格式範例嗎><

![messageImage_1561433711443](https://user-images.githubusercontent.com/40626539/60067492-641e0900-973d-11e9-8a85-13144972041b.jpg)

**Comment by MaybeShewill-CV** [comment]
@ahare1535 你可以去官网下载synth90k数据集然后数据格式他们都有说明哈．你只需要按照他们的格式来组织你的数据集然后调用tools/write_tfrecords.py工具来生成对应的tfrecords就可以了:)

**Comment by Romance-Zhang** [comment]
那个数据集比较大，下载速度比较慢，下载失败了两次，请问可以把数据集内部格式截个图嘛？

**Comment by Romance-Zhang** [comment]
或者有百度云的数据集链接吗

**Comment by MaybeShewill-CV** [comment]
@Romance-Zhang 我这边没有百度云链接 但是我记得好像百度能搜到百度云的链接:)

**Comment by MaybeShewill-CV** [comment]
@Romance-Zhang @ahare1535 我这边解压之后是按照这样的形式存放的
![1](https://user-images.githubusercontent.com/15725187/60076756-f08af480-975a-11e9-9847-a3e5f49050df.png)

**Comment by Romance-Zhang** [comment]
非常感谢！请问同学是否能把几个txt文件以及两个文件夹90kDICT32px和tfrecords内部截图发到我的邮箱1003761104@qq.com?  不胜感激，所有项目都值得star!

**Comment by MaybeShewill-CV** [comment]
@Romance-Zhang tfrecords是生成tfrecords的时候自动生成的，正常生成以后结果如下：
![8](https://user-images.githubusercontent.com/15725187/60080422-7c544f00-9762-11e9-8d4a-16cd84d30151.png)
其余几个文件截图如下 文件名称在图片最上方可以自己仔细看一下
![1](https://user-images.githubusercontent.com/15725187/60080464-92620f80-9762-11e9-8976-43974a603839.png)
![2](https://user-images.githubusercontent.com/15725187/60080470-97bf5a00-9762-11e9-9ae6-5cdc8dd2779c.png)
![3](https://user-images.githubusercontent.com/15725187/60080486-9beb7780-9762-11e9-9934-ce3e11200889.png)
![4](https://user-images.githubusercontent.com/15725187/60080495-a0179500-9762-11e9-8e41-541ee24f9902.png)
![5](https://user-images.githubusercontent.com/15725187/60080503-a3128580-9762-11e9-9613-37f75a538956.png)
![6](https://user-images.githubusercontent.com/15725187/60080510-a574df80-9762-11e9-87fd-562adf553111.png)

**Comment by ahare1535** [comment]
十分感謝！

**Comment by keerchaokeai** [comment]
@ahare1535 你好，我也想用自己的数据集训练模型，你现在会根据原数据的格式创建自己的训练集了嘛

**Comment by keerchaokeai** [comment]
@MaybeShewill-CV 请问大神这个文件夹里面是怎样的
![image](https://user-images.githubusercontent.com/47933430/60164752-b55af500-9830-11e9-9c6b-b0621a9207e2.png)

**Comment by dinhdat789** [comment]
How to create lexicon.txt file?
