### ISSUE TITLE
python write_tfrecords.py 出错 

### ISSUE THREAD

**Issue by keerchaokeai** [MaybeShewill-CV/CRNN_Tensorflow#286]
Traceback (most recent call last):
  File "write_tfrecords.py", line 74, in <module>
    save_dir=args.save_dir
  File "write_tfrecords.py", line 56, in write_tfrecords
    writer_process_nums=2
  File "/Data/home/liuqingqing/Downloads/recognize/CRNN_Tensorflow-master/tools/data_provider/shadownet_data_feed_pipline.py", line 55, in __init__
    raise ValueError('Source image data is not complete, '
ValueError: Source image data is not complete, please check if one of the image folder or index file is not exist

请问我这个错误怎么改正啊，任何帮助将会不胜感激!

**Comment by MaybeShewill-CV** [comment]
@keerchaokeai 你下载的数据集缺少文件或者你指定的dataset_dir路径不对:)

**Comment by keerchaokeai** [comment]
> @keerchaokeai你下载的数据集缺少文件或者你指定的dataset_dir路径不对:)



> @keerchaokeai你下载的数据集缺少文件或者你指定的dataset_dir路径不对:)

我是把数据集中的五千多张图片放在一个文件夹下，请问这有问题嘛

**Comment by keerchaokeai** [comment]
@MaybeShewill-CV 我是把数据集中的五千多张图片放在一个文件夹下，请问这有问题嘛

**Comment by MaybeShewill-CV** [comment]
@keerchaokeai 自己检查你的数据集格式和synth90k的数据集有什么不一样的地方吧 这个工具只能处理synth90k类似格式的数据集 synth90k数据集格式可以自己去官网下载查看或者参考#285
