### ISSUE TITLE
请问为什么我训练出来的模型比自带的模型大

### ISSUE THREAD

**Issue by JXMss** [MaybeShewill-CV/CRNN_Tensorflow#288]
我训练出来的模型是68152KB
CRNN_Tensorflow-master\model\crnn_syn90k_saved_model\variables\文件夹里的模型是34085KB
我把训练好的模型丢到variables文件夹 倒是能运行test 但是根本识别不了 准确率低于5% 明明拿Synth 90k训练了200W
训练用的是GTX1070
请大佬解惑

**Comment by MaybeShewill-CV** [comment]
@JXMss train脚本保存的是ckpt模型文件 会比转换的saved model大 如果你要使用tensorflow saved model你需要执行tfserve里面的脚本转换一下 具体可参考README

**Comment by JXMss** [comment]
@MaybeShewill-CV 明白了 感谢大佬

**Comment by JXMss** [comment]
@MaybeShewill-CV 大佬 我用export输出saved model的时候 出现了以下错误

> 2019-06-25 20:16:59.625159: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-06-25 20:16:59.861884: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.63GiB
2019-06-25 20:16:59.862485: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0
2019-06-25 20:17:00.799937: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-25 20:17:00.800211: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971]      0 
2019-06-25 20:17:00.800402: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0:   N 
2019-06-25 20:17:00.800698: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7372 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
I0625 20:17:00.811722 15112 tf_logging.py:115] Restoring parameters from H:/MachineLearning/match/CRNN_Tensorflow-master/tools/model/crnn_syn90k/shadownet_2019-06-25-15-40-43.ckpt-2350000
I0625 20:17:00.948644 15112 tf_logging.py:115] No assets to save.
I0625 20:17:00.948644 15112 tf_logging.py:115] No assets to write.
I0625 20:17:01.284454 15112 tf_logging.py:115] SavedModel written to: H:/MachineLearning/match/CRNN_Tensorflow-master/tools/model/123/saved_model.pb
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp, line 4044
Traceback (most recent call last):
  File "H:/MachineLearning/match/CRNN_Tensorflow-master/tools/export_saved_model.py", line 196, in <module>
    test_load_saved_model(args.export_dir, args.char_dict_path, args.ord_map_dict_path)
  File "H:/MachineLearning/match/CRNN_Tensorflow-master/tools/export_saved_model.py", line 140, in test_load_saved_model
    interpolation=cv2.INTER_LINEAR
cv2.error: OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize


Process finished with exit code 1

**Comment by MaybeShewill-CV** [comment]
@JXMss git pull更新下仓库 重新export 如果还有问题 贴图你是怎么使用saved model的：）

**Comment by JXMss** [comment]
@MaybeShewill-CV 成功了 感谢大佬

**Comment by JXMss** [comment]
@MaybeShewill-CV 大佬 还是存在转换出来的模型识别率太低的问题 我看和之前转换错误的模型识别结果一毛一样
请问是不是训练模式 或者shadownet更改过了 我之前是直接download zip的 然后一直拿那个训练模型

**Comment by JXMss** [comment]
这两天一直在忙期末考试 没仔细测试过 当时export出来就没再管

**Comment by JXMss** [comment]
![image](https://user-images.githubusercontent.com/40733256/60312256-3929f400-998d-11e9-9146-51004f12b71b.png)
export的参数
![image](https://user-images.githubusercontent.com/40733256/60312273-5363d200-998d-11e9-8489-0244131f1749.png)
输出
![image](https://user-images.githubusercontent.com/40733256/60312284-6080c100-998d-11e9-836d-4e2cb5398983.png)
然后我先把原来的\CRNN_Tensorflow-master\model\crnn_syn90k_saved_model下整个删除 再把上图的文件和文件夹粘贴过来
![image](https://user-images.githubusercontent.com/40733256/60312387-b7869600-998d-11e9-8924-f4537346f605.png)
然后就是运行test了

我用的test是老版本的test 运行一开始自带的模型时 准确率很高 但一换我自己跑了export的 就歇菜了

**Comment by JXMss** [comment]
我现在无法确定到底是我模型训练的偏差 还是export出了问题 很纠结 希望大佬赐教

**Comment by MaybeShewill-CV** [comment]
@JXMss saved mode和ckpt模型的使用方式不一样．tools里面的test脚本只适合ckpt模型.这个export saved模型是用在tensorflow model server上的. 当然saved model也可以用来进行普通形式的测试, 需要你自己写代码测试吧：）

**Comment by MaybeShewill-CV** [comment]
@JXMss 建议你先多了解点tensorflow然后再上手DL 这些很基础的问题就不会困扰你了

**Comment by JXMss** [comment]
@MaybeShewill-CV 可我之前test用的都是自带的模型 就是saved model 正确率没问题 很迷茫

**Comment by JXMss** [comment]
@MaybeShewill-CV 之前的确没怎么了解过TensorFlow model server 受教了

**Comment by JXMss** [comment]
@MaybeShewill-CV 我记得我当时还跟同学说 自己训练出来的模型有问题 用自带的模型

**Comment by MaybeShewill-CV** [comment]
@JXMss 那你就自己查查吧：）

**Comment by JXMss** [comment]
我用两个ckpt的模型重新test了两遍 结果一模一样……
![image](https://user-images.githubusercontent.com/40733256/60313098-6035f500-9990-11e9-943a-8922d0cc6709.png)
![image](https://user-images.githubusercontent.com/40733256/60313106-67f59980-9990-11e9-960c-8a0fd1897eae.png)

**Comment by MaybeShewill-CV** [comment]
@JXMss 你可以把问题描述清楚点吗 你的ckpt文件怎么来的 两个json文件是你自己生成的还是直接用的下载的==！

**Comment by JXMss** [comment]
@MaybeShewill-CV ckpt文件有两个 一个是在train_shadownet.py用syn90k数据集跑了200W的结果 一个是在前一个ckpt的基础上用我自己的数据集跑了50W的结果
两个json文件用的自带的json

**Comment by JXMss** [comment]
@MaybeShewill-CV 我之前曾经测试过很多训练出来的ckpt模型 无一例外都有问题 很苦恼

**Comment by JXMss** [comment]
@MaybeShewill-CV 我刚才以为是以前的test有问题 又用最新的test测试了 识别结果还是有问题

**Comment by JXMss** [comment]
![image](https://user-images.githubusercontent.com/40733256/60314654-fae50280-9995-11e9-9171-32d9b3f09576.png)

附一张TensorBoard 下面第二个尖是我在200W步的时候新换的数据集导致的

**Comment by MaybeShewill-CV** [comment]
@JXMss synth90k上训练200w次的模型测试正常吗？（使用ckpt文件和tools/test_shadownet.py测试）

**Comment by JXMss** [comment]
@MaybeShewill-CV 不正常……

**Comment by MaybeShewill-CV** [comment]
@JXMss 那你重新检查你什么地方的执行步骤和readme上不一样吧 synth90k上训练不可能出问题:)

**Comment by JXMss** [comment]
@MaybeShewill-CV 以为test读取saved model这事真不能怪我…… 您看
![image](https://user-images.githubusercontent.com/40733256/60315118-d427cb80-9997-11e9-903a-0e8a3bcbc8c6.png)
![image](https://user-images.githubusercontent.com/40733256/60315128-e0ac2400-9997-11e9-9428-00d0d5c8dd1f.png)
![image](https://user-images.githubusercontent.com/40733256/60315138-ec97e600-9997-11e9-8176-de63457b3acf.png)

test跑自带的saved model识别没问题 一换我自己的ckpt或者我ckpt转换过的saved model就不行……

**Comment by JXMss** [comment]
我是真的按照README做的…… cmd命令、执行bat文件还有PyCharm直接填参数运行都试过了……
