### ISSUE TITLE
问一个比较简单的问题，下面的路径我该怎么改

### ISSUE THREAD

**Issue by keerchaokeai** [MaybeShewill-CV/CRNN_Tensorflow#289]
![image](https://user-images.githubusercontent.com/47933430/60144106-c5081880-97f3-11e9-84d8-54884f4fb5de.png)

**Comment by MaybeShewill-CV** [comment]
@keerchaokeai ==! 就是字面意思 就是你的模型文件的路径 还有两个json文件的路径:)
