### ISSUE TITLE
怎么将整个synth90k数据集 并将所有文件提取到根目录中

### ISSUE THREAD

**Issue by keerchaokeai** [MaybeShewill-CV/CRNN_Tensorflow#290]

**Comment by MaybeShewill-CV** [comment]
@keerchaokeai 官网下载然后解压:)

**Comment by keerchaokeai** [comment]
@MaybeShewill-CV 这个我知道，我看你的readme里面说是要把所有文件提取到一个根目录啊，解压之后也是分别存在于好多级目录里面啊，，，tfrecord过程不是要把所有文件放在一个根目录里面吗
