### ISSUE TITLE
使用其他数据集训练，训练loss正常，但所有预测结果相同

### ISSUE THREAD

**Issue by dmlan** [MaybeShewill-CV/CRNN_Tensorflow#292]
你好，
在1000张银行卡图片数据上跑最新代码：
出现训练损失下降，但验证损失不变，最后测试时发现输出固定数字。
浏览了一下issues,发现几个人有这样的问题，但没说详细的解决方案。只能麻烦master解答一下。
![image](https://user-images.githubusercontent.com/29965978/60260313-d7757580-990b-11e9-8a55-5a8e1d6f19ee.png)

数据集：http://www.cnsoftbei.com/upload_files/article/155/1_20190312170354_p8wwl.rar
修改global_config.py如下
__C.ARCH.SEQ_LENGTH = 30  
__C.ARCH.INPUT_SIZE = (120, 46)  
__C.ARCH.INPUT_CHANNELS = 3
__C.ARCH.NUM_CLASSES = 12 （10个数字+'_'+1） `

char_dict_num.json
`{
    "48_ord": "0",
    "49_ord": "1",
    "50_ord": "2",
    "51_ord": "3",
    "52_ord": "4",
    "53_ord": "5",
    "54_ord": "6",
    "55_ord": "7",
    "56_ord": "8",
    "57_ord": "9",
    "95_ord": "_"
}`

ord_map_num.json
`{
    "0_index": "48",
    "10_index": "95",
    "1_index": "49",
    "2_index": "50",
    "3_index": "51",
    "48_ord": "0",
    "49_ord": "1",
    "4_index": "52",
    "50_ord": "2",
    "51_ord": "3",
    "52_ord": "4",
    "53_ord": "5",
    "54_ord": "6",
    "55_ord": "7",
    "56_ord": "8",
    "57_ord": "9",
    "5_index": "53",
    "6_index": "54",
    "7_index": "55",
    "8_index": "56",
    "95_ord": "10",
    "9_index": "57"
}`

annotation_train.txt
`0000a_0.png 1
0000e_0.png 2
0000f_0.png 3
0000g_0.png 4
0000h_0.png 5`
共1084条
annotation_test.txt annotation_val.txt 与annotation_train.txt 完全相同

lexicon.txt
`0000
0000
0000
0000
0000`

之后按readme运行python tools/write_tfrecords.py  
python tools/train_shadownet.py
以上步骤是否有不合理的地方？十分感谢。

**Comment by dmlan** [comment]
或者这种label类别不同的情况下，我能否经过简单修改，先加载已有模型当作预训练模型呢？
或者在原有模型结构基础上，后面再加一层output=12，这样方案是否可行？
或者有更好的方案么？
十分感谢。

**Comment by MaybeShewill-CV** [comment]
@dmlan 可以增加．你训练数据太少并且训练时间太短,时间长一点再观察validation吧．有点耐心,才几百个epoch＝＝！

**Comment by dmlan** [comment]
@MaybeShewill-CV  我之前试了10000个epoch，结果也是这样。
而且我不太明白的是，我的annotation_train、annotation_test 、annotation_val三个文件完全相同，是不是意味着训练集验证集测试集都是一个呢？
为什么训练集准确率提升，但是验证集准确率基本为0？

**Comment by MaybeShewill-CV** [comment]
@dmlan 文件都一样那就是同一个:)

**Comment by liumengyaaa** [comment]
请问准备数据集的时候， 需要哪些文件 方便说一下数据集是如何准备的吗 我们打算做票据识别的，在准备数据集的过程中出现了一些问题 @dmlan

**Comment by dmlan** [comment]
@MaybeShewill-CV 
你好，我目前不太理解的这是个地方，为什么val还需要重新初始化一个网络呢？而不是使用一个？验证时候确实用的shadownet_val预测，它应该完全没有更新过呀。
`    # set crnn net
    shadownet = crnn_net.ShadowNet(
        phase='train',
        hidden_nums=CFG.ARCH.HIDDEN_UNITS,
        layers_nums=CFG.ARCH.HIDDEN_LAYERS,
        num_classes=CFG.ARCH.NUM_CLASSES
    )
    shadownet_val = crnn_net.ShadowNet(
        phase='test',
        hidden_nums=CFG.ARCH.HIDDEN_UNITS,
        layers_nums=CFG.ARCH.HIDDEN_LAYERS,
        num_classes=CFG.ARCH.NUM_CLASSES
    )`

目前我把train_shadownet.py 文件中使用shadownet_val的地方，改成了shadownet，单从结果上来看是正常的。训练1000轮之后准确率接近1。

**Comment by MaybeShewill-CV** [comment]
@dmlan 两个网络phase标示位不同：）

**Comment by dmlan** [comment]
@MaybeShewill-CV 我目前读下来，
1.shadownet_val和shadownet这两个网络的权重是不共享的。
2.shadownet_val在训练过程中并没有更新权重。
shadownet_val一直都是刚初始化的新网络。

所以导致我最开始的那个情况，训练集使用shadownet预测，准确率不断上升，验证集使用shadownet_val预测时候准确率为0。

所以是否应该把验证和测试时候使用的网络从shadownet_val改成shadownet呢?

**Comment by MaybeShewill-CV** [comment]
@dmlan 不该:)

**Comment by dmlan** [comment]
@MaybeShewill-CV 
非常感谢，但是还是要请教一下，为什么我们需要shadownet_val预测呢，因为我觉得它完全就是一个全新的网络呀，没有经过任何训练，reuse=True。

**Comment by MaybeShewill-CV** [comment]
@dmlan 你自己查查tensorflow和bn吧，顺便再读一下原文:)

**Comment by dmlan** [comment]
@MaybeShewill-CV 嗯，总之十分感谢。

**Comment by dmlan** [comment]
@liumengyaaa 如你所见，我目前还没能搞懂一些问题。所以暂时帮不了你，非常抱歉。

**Comment by pingzi5233** [comment]
请问问题解决了吗？银行卡现在识别效果怎么样？
