### ISSUE TITLE
weights on Synth90k dataset 

### ISSUE THREAD

**Issue by keerchaokeai** [MaybeShewill-CV/CRNN_Tensorflow#293]
![image](https://user-images.githubusercontent.com/47933430/60310523-dd0fa180-9985-11e9-871c-1acc3694f5bd.png)

--weights_path PATH/TO/YOUR/MODEL_WEIGHTS_PATH，请问大神，这个我要怎么改啊，非常感谢！

**Comment by dmlan** [comment]
@keerchaokeai 
--weights_path 是参数名，后面是指模型保存的地址。
如果是想用训练好的模型，你可以翻一下model文件夹
--weights_path model/crnn_syn90k_saved_model/1/variables/variables

**Comment by keerchaokeai** [comment]
@dmlan 好的，谢谢啦。明白了

**Comment by keerchaokeai** [comment]
@dmlan 但是作者给出的链接里面没有shadownet.ckpt啊，都是想下面这样有其他后缀啊，我该怎么弄
![image](https://user-images.githubusercontent.com/47933430/60314134-236bfd00-9994-11e9-9935-f3616ab22732.png)

**Comment by dmlan** [comment]
@keerchaokeai 你可以先直接试试下面这个。
--weights_path model/crnn_syn90k/shadownet.ckpt
这是第二个文件名字.data之前的。或者也可以查看一下checkpoint文件。

**Comment by keerchaokeai** [comment]
@dmlan 我试过，貌似不行啊

**Comment by dmlan** [comment]
@keerchaokeai 
![image](https://user-images.githubusercontent.com/29965978/60324404-49ef5f80-99b7-11e9-9fb8-72e59d1e5c44.png)

python tools/test_shadownet.py  
--image_path dataset/images/9701r_0.png 
--weights_path model/crnn_syn90k/shadownet_2019-06-28-01-58-15.ckpt-1500 
--char_dict_path data/char_dict/char_dict_num.json 
--ord_map_dict_path data/char_dict/ord_map_num.json
我这条命令是可以的，你参考下。或者把报错贴上来。

**Comment by keerchaokeai** [comment]
@dmlan 谢谢~谢谢~我试试，顺便问一下，作者说的这句话，意思是把所有图片提取出来放在一个文件夹下吗
![image](https://user-images.githubusercontent.com/47933430/60325250-70ae9580-99b9-11e9-8bc1-a677d08b0ee6.png)

**Comment by dmlan** [comment]
@keerchaokeai 我目前环境网络有点限制，10G那个数据集并没下载。
但是这边报错写得很明确，根据报错很容易的调好的。

**Comment by keerchaokeai** [comment]
@dmlan 好的，明白~非常感谢你

**Comment by keerchaokeai** [comment]
@dmlan 
![image](https://user-images.githubusercontent.com/47933430/60378431-1531e580-9a55-11e9-93c9-1ab4c4af6985.png)qi请问你知道我这是怎么回事吗，为什么总是显示这张照片没有呢

**Comment by keerchaokeai** [comment]
@dmlan 能帮我看看我这是怎么回事吗
![image](https://user-images.githubusercontent.com/47933430/60407492-a0de7a00-9bed-11e9-878f-472c1382604d.png)
上面四个文件我都是过了，都显示错误

**Comment by dmlan** [comment]
@keerchaokeai  
--weights_path ....../shadownet.ckpt
第一条命令，把权重文件shadownet.ckpt.data-000000-of000001 只保留.data之前的“shadownet.ckpt”试试

**Comment by keerchaokeai** [comment]
@dmlan 非常感谢你的回复，但是还是不行啊
![image](https://user-images.githubusercontent.com/47933430/60407847-e18ac300-9bee-11e9-9a94-e88d46a978e7.png)你的图中的日期是怎么出来的，那几个文件都是你训练出来的还是从作者给的网址中下下来的啊，能不能发给我一份
![image](https://user-images.githubusercontent.com/47933430/60407888-0f700780-9bef-11e9-9fab-480a647d3926.png)

**Comment by dmlan** [comment]
@keerchaokeai 
你打开你shadownet.ckpt.data-000000-of000001的目录，然后pwd一下。看看文件所在路径对不对。
我的模型是自己train的实验品，局限性很大。
作者的demo是没问题的。

**Comment by keerchaokeai** [comment]
@dmlan 我能加你微信吗，如果可以麻烦加下我love_qinging
