### ISSUE TITLE
有没有人用这个模型训练了自己的数据集啊，比如说识别数字字符，能告诉我怎么把自己的数据集做成类似synth90的格式嘛，我该怎么做

### ISSUE THREAD

**Issue by 1810325** [MaybeShewill-CV/CRNN_Tensorflow#297]

**Comment by 2017TJM** [comment]
格式是这样的：图片路径 图片ID

**Comment by 1810325** [comment]
@2017TJM 你好，请问我按照原数据格式制作了自己的数据集，运行的时候报错如下是怎么回事啊
![image](https://user-images.githubusercontent.com/47933430/60497177-e337b200-9ce6-11e9-90e5-61a851a97dac.png)
![image](https://user-images.githubusercontent.com/47933430/60497199-f0ed3780-9ce6-11e9-8705-05b11602953e.png)
