### ISSUE TITLE
如果我需要训练车牌这样的，需要怎么做了

### ISSUE THREAD

**Issue by 2017TJM** [MaybeShewill-CV/CRNN_Tensorflow#298]

**Comment by MaybeShewill-CV** [comment]
@2017TJM 自己按照synth90k数据集的格式准备数据集或者实现自己的data feed pipline:)

**Comment by 1810325** [comment]
@MaybeShewill-CV ，请问我按照原数据格式制作了自己的数据集，运行的时候报错如下是怎么回事啊
![image](https://user-images.githubusercontent.com/47933430/60497251-0f533300-9ce7-11e9-95fb-1f0208c6b83e.png)
![image](https://user-images.githubusercontent.com/47933430/60497277-18440480-9ce7-11e9-9e5a-fb4a77f124c3.png)

**Comment by MaybeShewill-CV** [comment]
@1810325 error信息很清楚了 自己检查下你的数据集和synth90k哪里不一样吧:)
