### ISSUE TITLE
测试中文报错

### ISSUE THREAD

**Issue by cl886699** [MaybeShewill-CV/CRNN_Tensorflow#299]
运行python tools/recongnize_chinese_pdf.py ^
-c data/char_dict/char_dict_cn.json  ^
-o data/char_dict/ord_map_cn.json ^
--weights_path crnn_chinese/shadownet.ckpt  ^
--image_path data/test_images/test_pdf.png  ^
--save_path pdf_recognize_result.txt
报错信息如下：
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current gra
ph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,5825]
         [[Node: save/Assign_45 = Assign[T=DT_FLOAT, _class=["loc:@shadow_net/sequence_rnn_module/w"], use_locking=true, validate_shape=true, _device="/job:l
ocalhost/replica:0/task:0/device:GPU:0"](shadow_net/sequence_rnn_module/w, save/RestoreV2/_91)]]
         [[Node: save/RestoreV2/_32 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/jo
b:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_38_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:
CPU:0"](save/RestoreV2:16)]]

**Comment by cl886699** [comment]
找到原因了，需要修改config
# __C.ARCH.NUM_CLASSES = 5825  # cn dataset
__C.ARCH.NUM_CLASSES = 37  # synth90k dataset

**Comment by XueKX** [comment]
能给个Q 请教一下吗

**Comment by cl886699** [comment]
88659445



 




------------------ 原始邮件 ------------------
发件人: "Carry在Carry"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 下午4:11
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com>;
抄送: "开开心心每一天"<88659445@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] 测试中文报错 (#299)




能给个Q 请教一下吗
