### ISSUE TITLE
请问一下如何提高中文模型的识别精度？

### ISSUE THREAD

**Issue by gallice** [MaybeShewill-CV/CRNN_Tensorflow#300]
我下载了你说的360万的中文数据集，并且可以按照你建议的格式来制作TF record，也可以自己来训练中文的模型了，但是我发现在识别的时候，还有有部分的字体是识别错误的，我已经是迭代了185K之后再识别的。请问一下还有什么建议的方法可以提高识别精度吗？
I0703 14:14:56.323463 17656 train_shadownet.py:329] Epoch_Train: 185607 cost=  1.217654
I0703 14:14:56.770658 17656 train_shadownet.py:329] Epoch_Train: 185608 cost=  0.235001
I0703 14:14:57.222515 17656 train_shadownet.py:329] Epoch_Train: 185609 cost=  0.335758
I0703 14:14:57.670471 17656 train_shadownet.py:329] Epoch_Train: 185610 cost=  0.157049
I0703 14:14:58.128119 17656 train_shadownet.py:329] Epoch_Train: 185611 cost=  0.264159
I0703 14:14:58.585088 17656 train_shadownet.py:329] Epoch_Train: 185612 cost=  0.910272
I0703 14:14:59.041423 17656 train_shadownet.py:329] Epoch_Train: 185613 cost=  0.536857
I0703 14:14:59.493664 17656 train_shadownet.py:329] Epoch_Train: 185614 cost=  1.259677
I0703 14:14:59.953136 17656 train_shadownet.py:329] Epoch_Train: 185615 cost=  0.505736
I0703 14:15:00.408621 17656 train_shadownet.py:329] Epoch_Train: 185616 cost=  0.201098
I0703 14:15:00.859777 17656 train_shadownet.py:329] Epoch_Train: 185617 cost=  1.740116
I0703 14:15:01.303842 17656 train_shadownet.py:329] Epoch_Train: 185618 cost=  0.228649
I0703 14:15:01.754715 17656 train_shadownet.py:329] Epoch_Train: 185619 cost=  0.133792
I0703 14:15:02.194902 17656 train_shadownet.py:329] Epoch_Train: 185620 cost=  0.695963
I0703 14:15:02.640017 17656 train_shadownet.py:329] Epoch_Train: 185621 cost=  0.267997
I0703 14:15:03.092632 17656 train_shadownet.py:329] Epoch_Train: 185622 cost=  0.268708
I0703 14:15:03.545149 17656 train_shadownet.py:329] Epoch_Train: 185623 cost=  0.207863
I0703 14:15:04.001993 17656 train_shadownet.py:329] Epoch_Train: 185624 cost=  0.202221

我识别的原图：
![image](https://user-images.githubusercontent.com/31061867/60570129-759d8b80-9da3-11e9-9358-bec36ff1f206.png)
对应的识别结果：
gallice@gallice-Precision-T7610-AI:~/project/tensorflow_programing/CRNN_Tensorflow$ python tools/test_shadownet.py  --image_path ./data/test_images/0_7.png --weights_path ./model/crnn_syn90k/shadownet_2019-07-03-09-30-41.ckpt-180000 --char_dict_path ./data/char_dict/char_dict.json --ord_map_dict_path ./data/char_dict/ord_map.json
/usr/local/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-07-03 15:04:05.720464: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce RTX 2080 major: 7 minor: 5 memoryClockRate(GHz): 1.8
pciBusID: 0000:04:00.0
totalMemory: 7.76GiB freeMemory: 7.62GiB
2019-07-03 15:04:05.720523: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-07-03 15:04:06.236511: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-03 15:04:06.236571: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-07-03 15:04:06.236589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-07-03 15:04:06.236959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2385 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:04:00.0, compute capability: 7.5)
INFO:tensorflow:Restoring parameters from ./model/crnn_syn90k/shadownet_2019-07-03-09-30-41.ckpt-180000
I0703 15:04:06.239976 6967 tf_logging.py:115] Restoring parameters from ./model/crnn_syn90k/shadownet_2019-07-03-09-30-41.ckpt-180000
preds: 是一个基于GNUunux的轻量级图碟作界面，它虽然没有GNOME和KDE样精歇，但由于它的运行对系统资源和配置耍
I0703 15:04:18.567836 6967 test_shadownet.py:138] Predict image 0_7.png result: GNU unu x GNOME KDE
gallice@gallice-Precision-T7610-AI:~/project/tensorflow_programing/CRNN_Tensorflow$

**Comment by MaybeShewill-CV** [comment]
@gallice 1.根据你自己的应用场景准备相应的数据 2.关注更新的ocr模型：）

**Comment by gallice** [comment]
@MaybeShewill-CV ，你的意思是针对360万的中文数据集，已经很难精度再提升了，对吗？ 另外，我再训练中文数据集的时候，我发现NUM_CLASSES不太一样。我的是__C.ARCH.NUM_CLASSES = 5696  # cn dataset，而你的是__C.ARCH.NUM_CLASSES = 5825  # cn dataset。 我也是利用360万样本自动算出来的呀，怎么和你的不太一样？

**Comment by MaybeShewill-CV** [comment]
@gallice 不清楚你怎么算的:)

**Comment by MaybeShewill-CV** [comment]
@gallice 针对这个数据集不是没有方法再提升精度, 你可以再多查阅一些文献和方法.如果愿意也欢迎分享哈：）

**Comment by gallice** [comment]
另外，如果一段文字既有中文，也有英文的话，英文的识别结果是需要分词的，而中文又不能分词（分词就结果都是空的，我试过），请问一下这样的情况目前有建议的做法吗？
        if is_english:
            preds = ' '.join(wordninja.split(preds))

**Comment by gallice** [comment]
> @gallice 不清楚你怎么算的:)
我是根据char_dict.json这个文件来算的。如下图，我就认为NUM_CLASSES是5696，请问这样算对吗？
![image](https://user-images.githubusercontent.com/31061867/60576736-8e606e00-9db0-11e9-9b8b-d7077be2a271.png)

**Comment by MaybeShewill-CV** [comment]
@gallice 我是用的那个wordnijia就是专门做英文分词的 你用在中文上肯定是空的吧。可能你需要可以支持混合分词的package:)
