### ISSUE TITLE
在新增字体类别的情况下，如何支持继续训练？

### ISSUE THREAD

**Issue by gallice** [MaybeShewill-CV/CRNN_Tensorflow#301]
我这边遇到这样一个情况，就是我用自己的数据集训练好了一个模型，但是后来又有一些新的字需要训练，这些字是没有出现在我之前训练的样本里面的，请问这种情况下，我还能继续训练吗？如果是重头训练的话，时间上又太久了。

**Comment by MaybeShewill-CV** [comment]
@gallice 可以继续训练 全链接的地方需要重新初始化参数，你自己修改那个地方的代码重新初始化就好了:)

**Comment by gallice** [comment]
@MaybeShewill-CV , 我看了代码里面好像没有用到全连接层，你是指下面的fullyconnect(inputdata, out_dim, w_init=None, b_init=None,
                     use_bias=True, name=None) 函数吗？ 我看这个函数在整个代码都没有被调用。
![image](https://user-images.githubusercontent.com/31061867/60584604-43e6ed80-9dc0-11e9-8f17-b18eb0873eb3.png)
林外，一旦新增了字体label，这个char_dict.json文件不是也得同步修改的吗？ 可是，我看代码char_dict.json这个文件是生成TF record的时候，自动生成的呀。

**Comment by MaybeShewill-CV** [comment]
@gallice 是的，这个文件也需要同步更新,这个文件你可以重新生成:)

**Comment by gallice** [comment]
@MaybeShewill-CV ,我测试发现ord_map.json这个文件在每次用write_tfrecords.py执行的时候，都会被修改。这样子应该会影响到再训练吧？
![image](https://user-images.githubusercontent.com/31061867/60706102-4ae63b00-9f3b-11e9-9283-d622ac6fa38b.png)

**Comment by MaybeShewill-CV** [comment]
@gallice 不会影响，但是你开始训练之后这个文件就不可以在修改了。测试模型的时候这个文件也不可以修改否则会找不到正确的标签:)

**Comment by gallice** [comment]
@MaybeShewill-CV ，关于继续训练，你之前的回复是 “全链接的地方需要重新初始化参数“，这个是修改哪个部分的代码？ 可否帮忙给一下例子说明，非常感谢。

**Comment by MaybeShewill-CV** [comment]
@gallice 你看下代码里和CFG.TRAIN.CLASSES_NUMS有关系的部分就知道了哈：）
