### ISSUE TITLE
我用自己的数据做了一个300张图的数据集，为什么训练的时候出现这样的错误啊，请问我该怎么改

### ISSUE THREAD

**Issue by 1810325** [MaybeShewill-CV/CRNN_Tensorflow#302]
![image](https://user-images.githubusercontent.com/47933430/60588190-d8ede480-9dc8-11e9-8eee-5a562fc9a5f4.png)

![image](https://user-images.githubusercontent.com/47933430/60588167-cd9ab900-9dc8-11e9-89ae-1782a78118ad.png)

![image](https://user-images.githubusercontent.com/47933430/60588130-b4920800-9dc8-11e9-9d3c-538668fb4b74.png)

**Comment by MaybeShewill-CV** [comment]
@1810325 1.首先确保你正确生成了tfrecords 2.使用1.12或者以上版本的tensorflow

**Comment by 1810325** [comment]
@MaybeShewill-CV 谢谢，是数据量不足的原因，现在已经改好了

**Comment by 1810325** [comment]
@MaybeShewill-CV 谢谢作者

**Comment by kspook** [comment]
@1810325,  how many records do I have at least?
