### ISSUE TITLE
请问我用自己的数据集识别数字和字母时，训练完成之后想要测试一下，但是weight_path在哪里能找到啊

### ISSUE THREAD

**Issue by 1810325** [MaybeShewill-CV/CRNN_Tensorflow#305]
![image](https://user-images.githubusercontent.com/47933430/60750302-38bada00-9fd9-11e9-8a9e-e0a5007daaaa.png)

**Comment by MaybeShewill-CV** [comment]
@1810325 自己仔细看下readme吧：）
