### ISSUE TITLE
请问我用自己的数据集训练重新训练了模型，为什么就是识别不出来呢，每次results后面都是空

### ISSUE THREAD

**Issue by 1810325** [MaybeShewill-CV/CRNN_Tensorflow#306]
![image](https://user-images.githubusercontent.com/47933430/60750631-acf77c80-9fdd-11e9-8f05-c5eedd8ebdab.png)
而且我用作者的模型识别原数据集的图片也识别不出来

**Comment by MaybeShewill-CV** [comment]
@1810325 提供的pretrained模型在synth90k数据集上测试不会有问题, 自己看readme排查吧:)

**Comment by Tian14267** [comment]
请问你识别不出的原因找到了吗？我的也是没结果 @1810325

**Comment by kstys** [comment]
我在训练模型的时候也遇到的相同的问题，请问你是怎么解决的？ @yuxiaomu
