### ISSUE TITLE
CNN特征提取的网络架构好像和论文里面的网络架构不太一样，请问会有什么影响吗？

### ISSUE THREAD

**Issue by gallice** [MaybeShewill-CV/CRNN_Tensorflow#307]
我看代码里面的CNN部分抽取特征的网络架构，和论文里面的架构好像不一样，请问是这样的吗？如果真的不一样的话，会有什么样的影响吗？
代码的网络架构：
![image](https://user-images.githubusercontent.com/31061867/60756916-30dd5300-a036-11e9-9f5d-516ad934b7f2.png)

论文原始的架构：
![image](https://user-images.githubusercontent.com/31061867/60756921-3b97e800-a036-11e9-9c60-bd40b1429512.png)

**Comment by MaybeShewill-CV** [comment]
@gallice 具体哪里不一样
