### ISSUE TITLE
使用数据训练后只识别出了文本第一个字 

### ISSUE THREAD

**Issue by LXLun** [MaybeShewill-CV/CRNN_Tensorflow#308]
可能是什么原因？

**Comment by LXLun** [comment]
2019-07-09 09:17:16.772853: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-07-09 09:17:16.914688: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:65:00.0
totalMemory: 10.91GiB freeMemory: 6.40GiB
2019-07-09 09:17:16.914725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-07-09 09:17:17.148129: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-09 09:17:17.148177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-07-09 09:17:17.148186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-07-09 09:17:17.148367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6705 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from model/crnn_gag/shadownet_2019-07-07-18-04-16.ckpt-302000
I0709 09:17:17.152462 47007 tf_logging.py:115] Restoring parameters from model/crnn_gag/shadownet_2019-07-07-18-04-16.ckpt-302000
2019-07-09 09:17:17.178720: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 6.55G (7031645696 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
I0709 09:17:19.297317 47007 test_shadownet.py:140] Predict image 00003814.jpg result: 万

**Comment by LXLun** [comment]
# __C.ARCH.SEQ_LENGTH = 70  # cn dataset
__C.ARCH.SEQ_LENGTH = 75  # synth90k dataset
# Width x height into which training / testing images are resized before feeding into the network
# __C.ARCH.INPUT_SIZE = (280, 32)  # cn dataset
__C.ARCH.INPUT_SIZE = (300, 32)  # synth90k dataset

**Comment by LXLun** [comment]
image = np.array(image, np.float32) / 127.5 - 1.0
这是用来做什么的

**Comment by LXLun** [comment]
I0709 10:03:01.664045 41367 train_shadownet.py:313] Epoch_Train: 306001 cost=  0.423155 seq distance=  0.156250 train accuracy=  0.843750

**Comment by LXLun** [comment]
准确率没有问题

**Comment by LXLun** [comment]
try:
                lexicon_label = label
                encoded_label, _ = self.encode_labels(lexicon_label)
                print(encoded_label)

                _SAMPLE_INFO_QUEUE.put((image_path, encoded_label[0]))
            except IndexError:
                log.error('Lexicon doesn\'t contain lexicon index {:d}'.format(lexicon_index))
                continue

**Comment by MaybeShewill-CV** [comment]
@LXLun 1.不知道你具体是怎么执行的所以不是很清楚你的问题在什么地方 我觉得你可以对比下和用我训练中文模型测试过程有什么区别 2.

> image = np.array(image, np.float32) / 127.5 - 1.0
> 这是用来做什么的

这是归一化
3.

> ```
>         try:
>             lexicon_label = label
>             encoded_label, _ = self.encode_labels(lexicon_label)
>             print(encoded_label)
> 
>             _SAMPLE_INFO_QUEUE.put((image_path, encoded_label[0]))
>         except IndexError:
>             log.error('Lexicon doesn\'t contain lexicon index {:d}'.format(lexicon_index))
>             continue
> ```
> 
> _SAMPLE_INFO_QUEUE.put((image_path, encoded_label[0]))这句是不是有问题那不就是只取了一个字？

这是生成tensorflow records时候用的和你的测试过程没关系:)

**Comment by LXLun** [comment]
您好，我用您的模型测试的时候没问题，现在是加了一些文本，主要是空格和一些数字，然后纯使用的您那份数据集的文本生成了图片，然后制作成tfrecord训练，发现只能够识别出每张图的第一个字

**Comment by MaybeShewill-CV** [comment]
@LXLun 根据你的描述我也猜不出哪里有问题,而且我也没有提供过数据集文本生成图片的相关模块吧＝＝！

**Comment by LXLun** [comment]
encoded_label, _ = self.encode_labels(lexicon_label)这一句里的lexicon_label是不是就是单条的一个label

**Comment by MaybeShewill-CV** [comment]
@LXLun 是

**Comment by LXLun** [comment]
def encode_labels(self, labels):
        """
        Convert a batch of text labels into int index labels
        :param labels: List of text labels such as ['hello world', 'fuck world', ...]
        :return: Two list. One is a list of int index labels another is
        a list of label length
        """
        encoded_labels = []
        lengths = []
        for label in labels:
            encode_label = [self.char_to_int(char) for char in label]
            encoded_labels.append(encode_label)
            lengths.append(len(label))
        return encoded_labels, lengths

这样看是一个label list啊，我改成单条了


    def encode_labels(self, labels):
        """
        Convert a batch of text labels into int index labels
        :param labels: List of text labels such as ['hello world', 'fuck world', ...]
        :return: Two list. One is a list of int index labels another is
        a list of label length
        """
        encoded_labels = []
        lengths = []
        # for label in labels:
        #     print(label)
        encode_label = [self.char_to_int(char) for char in labels]
        encoded_labels.append(encode_label)
        lengths.append(len(labels))
        return encoded_labels, lengths

**Comment by MaybeShewill-CV** [comment]
@LXLun 这个地方不会错的，这是把每个字符转换成index标签, 如果这个地方错是无法训练synth90k数据集的:)

**Comment by LXLun** [comment]
可能是我的数据集格式不一样，我是直接是imgpath label 这种格式的，我前面也改了

**Comment by MaybeShewill-CV** [comment]
@LXLun 数据格式不一样的话你需要自己实现data feed pipeline 或者修改数据格式为synth90k格式:)

**Comment by LXLun** [comment]
我改了下，synth90k格式，lexicon是个行数对应label的文件，我的label文件是直接图片路径对应label，改了少部分读取代码就行了

**Comment by MaybeShewill-CV** [comment]
@LXLun ok 👌

**Comment by 13438960761** [comment]
@LXLun 请问你有预训练模型吗？能发我一份不？ 我一直打不开下载的网页。
邮箱：404262186@qq.com
非常感谢。
