### ISSUE TITLE
请问不定长文本在测试过程中如何调整送入网络的参数

### ISSUE THREAD

**Issue by zhangdaxia1** [MaybeShewill-CV/CRNN_Tensorflow#310]
作者您好，很感谢您的分享。我在跑您代码过程中发现不同长度以及不同字体的文本需要设置不同的宽度参数才可以很好的识别，请问这个问题您是怎么看的

**Comment by MaybeShewill-CV** [comment]
@zhangdaxia1 模型当然是不能fit所有的数据的。只能具体问题再具体做相应的优化:)

**Comment by zhangdaxia1** [comment]
模型效果很好，我现在就是每次去跑测试都要试一次参数，还没找到合适的解决方法

**Comment by MaybeShewill-CV** [comment]
@zhangdaxia1 提供一种解决思路，图片统一成你数据中最长的长度，长度不足的图像补零对齐, 可以试试:)

**Comment by zhangdaxia1** [comment]
我试过这个方法。在您的识别pdf的代码中有过使用。但这个不是解决多次加载模型的问题么？影响识别的还是这个resize步骤的new_width参数：pdf_image_text_area = cv2.resize( pdf_image_text_area, (new_width_tmp, new_heigth),interpolation=cv2.INTER_LINEAR)  您在识别pdf时使用高度等比例resize效果很好，但我的数据上效果就不理想了，所以我想请问您是否可以使用不定长文本的数据集进行训练？会不会出现问题？

**Comment by MaybeShewill-CV** [comment]
@zhangdaxia1 可以使用啊, 就是不定长的文本数据集通过补零对齐就可以变成定长的了哈:)

**Comment by zhangdaxia1** [comment]
非常感谢您的解答！所以送入网络前还是得预处理（补零对齐）保证文本数据定长吧

**Comment by MaybeShewill-CV** [comment]
@zhangdaxia1 是的 我的理解是这样的:)
