### ISSUE TITLE
中文训练出来的模型

### ISSUE THREAD

**Issue by Tian14267** [MaybeShewill-CV/CRNN_Tensorflow#312]
可否麻烦作者把你在中文模型（ckpt）上传呢？最好是百度云。
我自己训练出来的模型，效果蛮差的。想看看作者你的模型。

**Comment by MaybeShewill-CV** [comment]
@Tian14267 中文训练的模型已上传dropbox了 不方便传百度云 可以想办法科学上网:)

**Comment by Tian14267** [comment]
我是完全打不开你上传的那个网。那能否麻烦你发一份到我的邮箱呢？因为实在是打不开~~~

**Comment by Tian14267** [comment]
@MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@Tian14267 邮箱留一下 有时间了发给你:)

**Comment by chenyanghe** [comment]
@MaybeShewill-CV,能给我发一份中文训练的模型？我的邮箱chenyang_acy@163.com,谢谢！

**Comment by MaybeShewill-CV** [comment]
@chenyanghe 好的:)

**Comment by Tian14267** [comment]
tian14267@163.com
谢谢！
@MaybeShewill-CV

**Comment by Kryptonites** [comment]
@MaybeShewill-CV dropbox打不开,更新一下链接吧

**Comment by 13438960761** [comment]
@Tian14267 能否发我一份啊? 谢谢， 我也打不开网页， 邮箱 404262186@qq.com
