### ISSUE TITLE
关于模型finetune和字典的问题

### ISSUE THREAD

**Issue by Tian14267** [MaybeShewill-CV/CRNN_Tensorflow#314]
作者你好，我有两个关于模型finetune和字典的问题。
1：基于你训练的中文模型，我想在那个基础上加上自己的数据进行finetune。针对这个，我的json字典是以你的模型字典为依据，还是以我自己数据的字典为依据呢？
2：json字典是不是在制作tfrecords数据的时候自己生成的？同样都是中文，为什么字典不一样呢？

**Comment by Tian14267** [comment]
@MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@Tian14267 1.以你自己的数据字典为依据 2.没有使用ordered dict作为容器所以可能顺序和你的稍有不同吧:)

**Comment by Tian14267** [comment]
好的谢谢
