### ISSUE TITLE
评估时 char_dict_path 与 ord_map_dict_path参数的问题

### ISSUE THREAD

**Issue by curryJ** [MaybeShewill-CV/CRNN_Tensorflow#315]
利用readme中的提示，
```
python tools/evaluate_shadownet.py --dataset_dir PATH/TO/YOUR/DATASET_DIR 
--weights_path PATH/TO/YOUR/MODEL_WEIGHTS_PATH
--char_dict_path PATH/TO/CHAR_DICT_PATH 
--ord_map_dict_path PATH/TO/ORD_MAP_PATH
--process_all 1 --visualize 1
```
但是不知道char_dict_path与ord_map_dict_path的参数是什么？
能说明一下吗 谢谢！
我生成tfrecords之后并没有json格式的文件啊。

**Comment by MaybeShewill-CV** [comment]
@curryJ data文件夹里可以找到:)

**Comment by curryJ** [comment]
啊！我当时只把tfrecords下载下来了忘记保存这个了。我还要再运行一遍吗😂😂😂------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>
发送时间: 2019年7月17日(星期三) 下午3:01
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com>;
抄送: "curryJ"<761478292@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] 评估时 char_dict_path 与 ord_map_dict_path参数的问题 (#315)



@curryJ data文&#x4EF6;夹里可以找到:)
 
&mdash;

**Comment by MaybeShewill-CV** [comment]
@curryJ 如果没有这个文件则需要重新生成

**Comment by curryJ** [comment]
中文的这两个文件地址在哪里呢，我也是要先生成tfrecord格式，然后才有这两个json文件吗？中文的话需要改网络的配置参数吗？谢谢！

**Comment by curryJ** [comment]
中文的这两个文件地址在哪里呢，我也是要先生成tfrecord格式，然后才有这两个json文件吗？中文的话需要改网络的配置参数吗？谢谢！




------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>; 
发送时间: 2019年7月17日(星期三) 下午5:22
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com>; 
抄送: "PGyoung13"<761478292@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] 评估时 char_dict_path 与 ord_map_dict_path参数的问题 (#315)




@curryJ 如果没有这个文件则需要重新生成

**Comment by MaybeShewill-CV** [comment]
@curryJ 仔细看看readme 写的很清楚.这两个json文件生成tfrecords的过程中会自动生成:)
