### ISSUE TITLE
中文数据集Synthetic Chinese String Dataset 

### ISSUE THREAD

**Issue by CharlesWu123** [MaybeShewill-CV/CRNN_Tensorflow#317]
您好，从您链接下载下来的中文数据集Synthetic Chinese String Dataset 中只有图片，没有标注呢？

**Comment by Wenqiang-Miao** [comment]
您好，请问您找到标注了么，我也没发现标注...求告知，谢谢

**Comment by andrewwyl** [comment]
@CharlesWu123 麻烦问一下标注文件找到了吗？我下载的数据集有train.txt和val.txt文件但是里面的标注数据都是数字信息，这个是什么意思啊？

**Comment by musenlllm** [comment]
> @CharlesWu123 麻烦问一下标注文件找到了吗？我下载的数据集有train.txt和val.txt文件但是里面的标注数据都是数字信息，这个是什么意思啊？

请问您知道这个数据标注是什么意思嘛？
