### ISSUE TITLE
使用预训练模型运行失败

### ISSUE THREAD

**Issue by xueyongfu** [MaybeShewill-CV/CRNN_Tensorflow#321]
![image](https://user-images.githubusercontent.com/48610386/61923846-fd884700-af97-11e9-8e62-c35587869472.png)
![image](https://user-images.githubusercontent.com/48610386/61923869-109b1700-af98-11e9-855e-29425317be42.png)
![image](https://user-images.githubusercontent.com/48610386/61923882-227cba00-af98-11e9-9706-8e5a6420aaec.png)
![image](https://user-images.githubusercontent.com/48610386/61923890-2dcfe580-af98-11e9-87f6-b6d1a2e25080.png)

**Comment by AhmadShaik** [comment]
I think you need to update the global_config.py script which is placed in the config folder. 
You need to comment the synth90k (English OCR) config parameters and un-comment  the  cn dataset config parameters. 

```
__C.ARCH.SEQ_LENGTH = 70  # cn dataset
# __C.ARCH.SEQ_LENGTH = 25  # synth90k dataset
# Width x height into which training / testing images are resized before feeding into the network
__C.ARCH.INPUT_SIZE = (280, 32)  # cn dataset
# __C.ARCH.INPUT_SIZE = (100, 32)  # synth90k dataset
# Number of channels in images
__C.ARCH.INPUT_CHANNELS = 3
# Number character classes
__C.ARCH.NUM_CLASSES = 5825  # cn dataset
# __C.ARCH.NUM_CLASSES = 37  # synth90k dataset

```

**Comment by MaybeShewill-CV** [comment]
@xueyongfu 检查config文件里的配置是否符合你的数据集:)

**Comment by xueyongfu** [comment]
thanks
