### ISSUE TITLE
How can I train shadownet without char_dict.json, ord_dict.json, lexicon.txt? 

### ISSUE THREAD

**Issue by AhmadShaik** [MaybeShewill-CV/CRNN_Tensorflow#322]
I am working on a problem where I need to recognise a label crop which contains both numbers and characters. The present `synth90k dataset` format need `lexicon.txt` and `annotation.txt` files to generate `train.tfrecord`, `char_dict.json` and `ord_dict.json`. 
Currently, I have raw images and a `annotation.txt` file. My txt file contains absolute path of all the training images followed by ground truth text. 
An example is shown below:
![13_19](https://user-images.githubusercontent.com/34000753/61931263-bdc45e00-af9d-11e9-854d-723edaedc4d7.jpg)
`...
/data/work/ocr/CRNN_Tensorflow/data/training/image1.jpg  M1080540
...
...
`
Please provide a small example to create tfrecord using this data, that will be suitable for training shadownet.

Thank you.

**Comment by MaybeShewill-CV** [comment]
@AhmadShaik 1.You may orgnize your own dataset according Syth90k dataset's format and use the tools here to generate the tfrecords. 2.You may implement your own data feed pipline which is not difficult 3.Sorry I have no spare time for such a small example:)
