### ISSUE TITLE
low GPU memory-usuage

### ISSUE THREAD

**Issue by ElegyTsai** [MaybeShewill-CV/CRNN_Tensorflow#324]
训练时，看了一下GPU占用，显存使用94MiB/7951MiB GPU使用基本低于20%，电源5W/225W
按照readme所写， 多GPU和单GPU的命令都尝试过了，GPU都没有工作的痕迹
感觉没有正确的使用GPU进行训练，速度也不够理想（700张的数据集一个epoch大约0.8s）
请问一下这是正常状态还是GPU没有参与训练，如何加快训练速度
环境：Intel CPU集显+RTX2080  NVIDIA驱动版本418.74  CUDA10.1+Cudnn7.4+temsorflow1.13.1

**Comment by MaybeShewill-CV** [comment]
@ElegyTsai 如果GPU使用率这么低 大概率是你的gpu没有正常工作 可查看是否cpu使用率很高来确定模型计算到底在什么设备上完成.大概率是你的tensorflow gpu版本安装有问题 你可以先测试好这个没有问题了再继续测试后面的问题:)
