### ISSUE TITLE
@LXLun cv2.resize(image, dsize=tuple(CFG.ARCH.INPUT_SIZE), interpolation=cv2.IMREAD_GRAYSCALE) 建议你多看点基础只是 IMREAD_GRAYSCALE不是插值方法

### ISSUE THREAD

**Issue by LXLun** [MaybeShewill-CV/CRNN_Tensorflow#326]
@LXLun cv2.resize(image, dsize=tuple(CFG.ARCH.INPUT_SIZE), interpolation=cv2.IMREAD_GRAYSCALE) 建议你多看点基础只是 IMREAD_GRAYSCALE不是插值方法

_Originally posted by @MaybeShewill-CV in https://github.com/MaybeShewill-CV/CRNN_Tensorflow/issues/323#issuecomment-515824060_

这是我前面写错了位置，我生成数据用的是
image = cv2.imread(sample_path, cv2.IMREAD_GRAYSCALE)
image = cv2.resize(image, dsize=tuple(CFG.ARCH.INPUT_SIZE), interpolation=cv2.INTER_LINEAR)

这不是这个错误的原因........

**Comment by MaybeShewill-CV** [comment]
@LXLun 单通道当然不能用现有的模型直接训练 需要修改一些tensor的shape这个你自己看代码改吧:)

**Comment by LXLun** [comment]
可以指点下大概的需要修改那个地方么

**Comment by MaybeShewill-CV** [comment]
@LXLun 报错提示已经很清楚了 哪里的维度不匹配你就改相应的地方:)

**Comment by LXLun** [comment]
问一下，你的配置一张图片大概要解析耗时多长时间
