### ISSUE TITLE
How to use tfserver？

### ISSUE THREAD

**Issue by 447428054** [MaybeShewill-CV/CRNN_Tensorflow#328]
i do this:
bash script.

bash tfserve/export_crnn_saved_model.sh
To start the tensorflow model server you may check following script

bash tfserve/run_tfserve_crnn_gpu.sh
There are two different ways to test the python client of crnn model. First you may test the server via http/rest request by running

python tfserve/crnn_python_client_via_request.py ./data/test_images/test_01.jpg
Second you may test the server via grpc by running

python tfserve/crnn_python_client_via_grpc.py

But i can't get result from server

**Comment by MaybeShewill-CV** [comment]
@447428054 You may add more information here:)
