### ISSUE TITLE
get different result

### ISSUE THREAD

**Issue by safehumeng** [MaybeShewill-CV/CRNN_Tensorflow#329]
I use the pretrained weights on chinese dataset to predict the test image,but get different result
![image](https://user-images.githubusercontent.com/16226299/62850278-f3df3d00-bd14-11e9-964c-4593da160741.png)
![image](https://user-images.githubusercontent.com/16226299/62850325-1ffabe00-bd15-11e9-8243-19c93d17a393.png)
![image](https://user-images.githubusercontent.com/16226299/62850377-43be0400-bd15-11e9-9da1-57977d9cccba.png)
what's wrong with me?

**Comment by MaybeShewill-CV** [comment]
@safehumeng If you do not change any of the code and use the same version of tensorflow as mine. That should not happen in my opinion:)

**Comment by safehumeng** [comment]
I just use 'conda env create -f crnntf-env.yml' to create a conda environment and run
then get import error ----No module named 'cv2'，so I pip install opencv-python==3.4.1.15
but I get the wrong result

**Comment by MaybeShewill-CV** [comment]
@safehumeng the Conda environment was not supported by me so I can not tell you what happed. You may follow the readme file and test the model directly:)

**Comment by safehumeng** [comment]
thanks very much! I try training the model on my own dataset directly :)

**Comment by MaybeShewill-CV** [comment]
@safehumeng OK:)

**Comment by tabsun** [comment]
@safehumeng Exactly the same error for me. If you use your own trained model, does this problem occured again?

**Comment by safehumeng** [comment]
@tabsun new trained model  perfect well
