### ISSUE TITLE
怎么提高预测速度

### ISSUE THREAD

**Issue by smith-jianbo** [MaybeShewill-CV/CRNN_Tensorflow#330]
将训练好的模型封装了一个服务，当sequence_length为70时，一张图片速度要2秒，请问应该怎样优化速度？

**Comment by MaybeShewill-CV** [comment]
@smith-jianbo 如果是gpu的话 第一次使用的时候需要warm up 可以多测试一些数据后再统计效率:)

**Comment by Wenqiang-Miao** [comment]
您好！我也遇到了一样的问题，我把tf.nn.ctc_beam_search_decoder中的参数beam_width调整成了1，处理一张图片的时间就在0.5s以内了，您也可以试一下！

但是我没有深究这个参数的作用，我测试了几张图片，对结果貌似是没有影响的.....期待您的反馈
