### ISSUE TITLE
单通道训练的问题

### ISSUE THREAD

**Issue by archwolf118** [MaybeShewill-CV/CRNN_Tensorflow#332]
您好！请问楼主尝试过单通道训练吗？我在自己的数据集上分别训练了单通道和三通道的模型，三通道的模型要比单通道的模型召回率要高出3个百分点（自己的测试集），“三通道”和“单通道”训练的模型差距真的有那么大吗？
多谢！

**Comment by MaybeShewill-CV** [comment]
@archwolf118 没有尝试过单通道模型哈:)
