### ISSUE TITLE
CKPT files

### ISSUE THREAD

**Issue by vinicius-mariano** [MaybeShewill-CV/CRNN_Tensorflow#333]
Hi, good afternoon! 

MaybeShewill-CV, it's the first time I try to work with pretrained models... Can you help me? :)

How can I get the .ckpt file to use as parameter in "--weights_path"?

Thank you so much for your time!

**Comment by MaybeShewill-CV** [comment]
@vinicius-mariano Follow readme file. Download the pertained ckpt file

**Comment by 13438960761** [comment]
@MaybeShewill-CV HI author: thanks for your code! but i also cannot open the page of the pertained ckpt file, could you please send me by email?  
email-id: ### fairy@knowledge-vision.com
thank you very much!
