### ISSUE TITLE
Errors may have originated from an input operation.

### ISSUE THREAD

**Issue by 1810325** [MaybeShewill-CV/CRNN_Tensorflow#334]
请问我这是什么问题啊
看了好久都没检查出来，不胜感激
![image](https://user-images.githubusercontent.com/47933430/64334236-b36c9980-d00a-11e9-9d27-3981b6343b7c.png)

**Comment by MaybeShewill-CV** [comment]
@1810325 可以更换到和我一个版本的tensorflow试试哈:)

**Comment by 1810325** [comment]
@MaybeShewill-CV 好哒，谢谢回复

**Comment by 1810325** [comment]
@MaybeShewill-CV 
![image](https://user-images.githubusercontent.com/47933430/64342050-4c57e080-d01c-11e9-8a3f-4386e1f8ed2b.png)楼主您好，上面的问题我解决了，请问现在这个问题您知道时怎么回事吗

**Comment by MaybeShewill-CV** [comment]
@1810325 应该还是不同版本tensorflow之间的ctc有不一样的地方吧 你可以先试试切换到和我一个版本的tensorflow那样是不会有问题的:)

**Comment by 1810325** [comment]
@MaybeShewill-CV 是因为版本的问题吗，楼主我大胆猜想一下，是不是标签的问题啊，我看上面说的是标签方面的，另外我会尝试一下换个版本的tensorflow,嘿嘿

**Comment by MaybeShewill-CV** [comment]
@1810325 因为我假设的是你按照readme中提供的步骤和数据在实验的时候出了问题 如果是你自己的数据那也可能是你自己数据不对的问题。因为你的提问没有提供任何别的有效信息，我也没办法判断:)

**Comment by 1810325** [comment]
@MaybeShewill-CV 那应该就是我数据的问题了，谢谢楼主
