### ISSUE TITLE
windows生成tfrecords多线程报错 freeze_support()

### ISSUE THREAD

**Issue by vinceyzw** [MaybeShewill-CV/CRNN_Tensorflow#335]
windows版本下调用 write_tfrecords.py时报错，提示freeze_support() can be omitted if the program is not going to be frozen to produce an executable

**Comment by MaybeShewill-CV** [comment]
@vinceyzw 可以查看前面的issue有相關的問題和解決方案:)

**Comment by vinceyzw** [comment]
可以具体一点吗？或者连接给我下  issues就6个问题，我都看过 @MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@vinceyzw 你自己查看closed的issue：）

**Comment by vinceyzw** [comment]
@MaybeShewill-CV 谢谢，刚发现有closed！

看了hzy5660251的帖子，现在我的做法：

1、在write_tfrecords.py的main中加入：
if name == 'main':
_SAMPLE_INFO_QUEUE = Manager().Queue()
_SENTINEL = ("", [])
2、把与multiprocessing相关的两个Manager、Process在write_tfrecords.py加载：
from multiprocessing import Manager
from multiprocessing import Process
3、通过write_tfrecords把参数一步步传到tf_io_pipline_fast_tools中：
write_tfrecords(
        dataset_dir=args.dataset_dir,
        char_dict_path=args.char_dict_path,
        ord_map_dict_path=args.ord_map_dict_path,
        save_dir=args.save_dir,
        SAMPLE_INFO_QUEUE = _SAMPLE_INFO_QUEUE,
        SENTINEL = _SENTINEL,
        Process = Process
    )

但是好像还是报错
TypeError: can't pickle SwigPyObject objects

@hzy5660251 可以分享下你如何做的吗？
