### ISSUE TITLE
我在运行到一半时出现了下面的问题，标签长度为零，请问这是什么意思，是对应某一行没有标签吗，我该怎么排查

### ISSUE THREAD

**Issue by 1810325** [MaybeShewill-CV/CRNN_Tensorflow#336]
![image](https://user-images.githubusercontent.com/47933430/64497239-f2d30880-d2de-11e9-93d2-8f742a0af87b.png)

**Comment by MaybeShewill-CV** [comment]
@1810325 這個最大的可能就是你的標籤值不對 這個你只能自己先檢查好數據 確認數據沒有問題:)
