### ISSUE TITLE
TF Records

### ISSUE THREAD

**Issue by vinicius-mariano** [MaybeShewill-CV/CRNN_Tensorflow#337]
Hi, good afternoon!

MaybeShewill-CV, it's the first time I try to work with pretrained models... Can you help me? :)

I'm trying to execute this command:
python write_tfrecords.py --dataset_dir 90kDICT32px --save_dir tfrecords

But this is the error that I get: 
![image](https://user-images.githubusercontent.com/41582307/64864812-4a8ab000-d60e-11e9-8bbe-30d25bbe0bb3.png)

P.S.: Every time I execute the command, the error occurs in a different percentage. 

Do you have any idea of what is occurring and how can I resolve it?

Thank you so much for your time!

**Comment by MaybeShewill-CV** [comment]
@vinicius-mariano can not see any useful information here. Can not help you without them:)

**Comment by vinicius-mariano** [comment]
Hi again! I found the solution: the amount of RAM memory was insufficient to run the threads. Increasing the memory the problem was solved. Thanks! :)
