### ISSUE TITLE
请问，为什么我用自己的数据集训练出来的准确率能有百分之八九十，但测试的准确率总是百分之二十几啊

### ISSUE THREAD

**Issue by 1810325** [MaybeShewill-CV/CRNN_Tensorflow#338]
![image](https://user-images.githubusercontent.com/47933430/65001924-21c32d00-d924-11e9-822a-17a30b460717.png)

**Comment by MaybeShewill-CV** [comment]
@1810325 可以检查下你的预处理过程是不是完全相同 然后test phase是否设置正确:)

**Comment by 1810325** [comment]
@MaybeShewill-CV 谢谢您的回复，我把数据集进行了扩充，现在训练和测试的准确率到0.9+了，不过训练还没停止，我想跟您问一下ctc-loss不是可以跟词库进行比对嘛，请问我该怎么做才能进行比对啊

**Comment by MaybeShewill-CV** [comment]
@1810325 没明白你说的跟词库对比是什么意思:)

**Comment by 1810325** [comment]
![image](https://user-images.githubusercontent.com/47933430/65231086-9d2e0580-db01-11e9-98c0-15221699fd07.png)
这是我在学习CRNN论文的时候看到的，您看看，跟词库对比就是这个意思

**Comment by MaybeShewill-CV** [comment]
@1810325 ctc就是没有词库的啊:)

**Comment by MaybeShewill-CV** [comment]
@1810325 如果你想要看概率矩阵你可以查看raw prediction 代码里可以找一下:)

**Comment by 1810325** [comment]
@MaybeShewill-CV 可能上面描述有些问题，但是ctc貌似是可以跟词库比对的，谢谢回复，我再看看

**Comment by 1810325** [comment]
@MaybeShewill-CV 请问怎么才能知道我识别的字符究竟是不是正确的啊

**Comment by MaybeShewill-CV** [comment]
@1810325 ....你不是有label么 你对比一下不就好了么

**Comment by 1810325** [comment]
@昂，我运行了evaluate.py现在出来的label本身就串了一行，但识别出来的结果跟串行后的标签是对应的，label的函数应该是从0开始而不是从1开始是吗

**Comment by 1810325** [comment]
@MaybeShewill-CV 而且我在训练的过程中print了标签和predicate的值，并没有出现串行的现象，但evaluate.py时却出现了串行的现象，label的值是实际值的下一行，识别出来的也是串行之后的值，请问这是怎么一回事，博主知道我该改哪里嘛

**Comment by MaybeShewill-CV** [comment]
@1810325 那可能是你哪里index错了吧:)

**Comment by 1810325** [comment]
@MaybeShewill-CV 博主您好，前面的问题我调好了，但是现在又遇到新的问题，我test的时候，predicte出来的字符跟实际字符不一样，predicte出来的字符前半段是正确的label，但后面还会有一部分字符，就像下图这样，您知道是怎么回事吗file:///home/yyk/Pictures/webwxgetmsgimg.jpeg 
![image](https://user-images.githubusercontent.com/47933430/66269211-7cdba600-e878-11e9-9746-03155392ae9d.png)

**Comment by MaybeShewill-CV** [comment]
@1810325 识别结果不正确 首先确认模型是否收敛 然后test的时候预处理是否一致 test phase设置是否正确:)
