### ISSUE TITLE
can not download the pretained checkpoint model 

### ISSUE THREAD

**Issue by 13438960761** [MaybeShewill-CV/CRNN_Tensorflow#339]
i try to download the pretrained model but i always can not open the web page 'https://www.dropbox.com/sh/z22xsn4byddalv3/AAAiIxAHJKbqy44M73ow5znSa?dl=0'
 would you please send it to me  by email? thanks !
email id : ### 404262186@qq.com

**Comment by MaybeShewill-CV** [comment]
@13438960761 找个vpn吧
