### ISSUE TITLE
请问lexicon.txt的行数是从第零行还是第一行开始计数？

### ISSUE THREAD

**Issue by Leedorado** [MaybeShewill-CV/CRNN_Tensorflow#340]
synth90下的太慢了，大佬能否提供一份缩小版的样例，这样我可以依照样例准备数据就可以开始训练了，这对一些想训练自己数据集不需要synth90k的童鞋会有很大的帮助，thx~~

**Comment by MaybeShewill-CV** [comment]
@Leedorado 这个你搜下类似csdn的地方 我记得是有说明的:)

**Comment by Leedorado** [comment]
@MaybeShewill-CV 我要识别的图片中，有几个字在char_dict_cn里面没有，除了把这几个字的ord值和utf-8值添加到char_dict_cn中，我还需要做哪些更改吗？谢谢~~

**Comment by MaybeShewill-CV** [comment]
@Leedorado config文件里面的类别数字也需要改:)

**Comment by Leedorado** [comment]
@MaybeShewill-CV 感谢，我是用的自己的数据集，要识别的字数也就几十个，这样的话，是不是可以把char_dict_cn中其他的字符都删掉呢？另外，config中的seq_length值和input_size值是直接使用cn dataset还是需要自己做更改呢？

**Comment by MaybeShewill-CV** [comment]
@Leedorado 如果不需要可以删掉 input size和seq length可以先不需要改 后续你需要改进模型的时候可以根据自己的数据集修改.开始你可以直接使用那个参数:)

**Comment by Leedorado** [comment]
@MaybeShewill-CV 好的，感谢~~
