### ISSUE TITLE
the label written in tfrecord is not same with the label read

### ISSUE THREAD

**Issue by 13438960761** [MaybeShewill-CV/CRNN_Tensorflow#341]
我写入tfrecord格式的label是索引值24,26,3,25,12 ； 但是从tfrecord解析出来的label索引是2.25.8.14； 不一样； 图片路径是正确的；
不知道是否与解析的稀疏tensor有关系？

**Comment by MaybeShewill-CV** [comment]
@13438960761 不知道你是怎么解析的 我生成label和读取label是对应的 没有问题。因为没有专门的测试单元测试这个 所以你可以用小batch数据训练 看模型是否能收敛：）
