### ISSUE TITLE
tf-gpu版本为1.12，训练的时候报错Failed to get convolution algorithm. This is probably because cuDNN failed to initialize，请问这种问题应该如何解决？谢谢~~

### ISSUE THREAD

**Issue by Leedorado** [MaybeShewill-CV/CRNN_Tensorflow#343]

**Comment by MaybeShewill-CV** [comment]
@Leedorado 查看你的cudnn, cuda, cuda driver, tensorflow是不是匹配吧:)

**Comment by Leedorado** [comment]
@MaybeShewill-CV 请问你的cuda、tf、cudnn版本是多少？如果是版本不匹配的原因话，是不是连一开始的write_tfrecords.py都跑不起来啊

**Comment by Leedorado** [comment]
我现在用的版本是tf-gpu 1.12 cuda 9 cudnn 7

**Comment by MaybeShewill-CV** [comment]
@Leedorado 跟你的一样cudnn 我是7.5

**Comment by Leedorado** [comment]
@MaybeShewill-CV 请问你的cuda是9点几呢？
