### ISSUE TITLE
Is it possible to retrain the model with my own images from the checkpoint weights you made available?

### ISSUE THREAD

**Issue by vinicius-mariano** [MaybeShewill-CV/CRNN_Tensorflow#344]
Hello!

I would like to train my own images, without need to train all the synth90k dataset again.
That is, training just the images I have, but not loosing the pre-training of synth90k dataset.

Is it possible? How?

**Comment by MaybeShewill-CV** [comment]
@vinicius-mariano Yep but you need to adjust the final fc layer which is related to the classification classes nums and reinitialize it yourself:)
