### ISSUE TITLE
用自己的中英文数据集训练，只能识别字母与数字，所有的汉字以及标点全都识别成空。global_config中相关项已经做了更改，为什么会出现这种情况呢？thx~

### ISSUE THREAD

**Issue by Leedorado** [MaybeShewill-CV/CRNN_Tensorflow#345]

**Comment by MaybeShewill-CV** [comment]
@Leedorado 感觉是不你使用的json文件是不是有问题:)

**Comment by Leedorado** [comment]
@MaybeShewill-CV 模型识别准确率现在到了一个瓶颈阶段，请问有什么方法可以进一步提高准确率吗，thx~

**Comment by MaybeShewill-CV** [comment]
@Leedorado 加数据：）

**Comment by wandaoyi** [comment]
我使用: crnn_chinese_model, char_dict_cn.json, ord_map_cn.json 这三个配置文件，中文识别都为空。想请教一下大佬，这是什么情况
