### ISSUE TITLE
用自己的数据运行train以后 程序被killed 并非代码报错会是什么原因呢

### ISSUE THREAD

**Issue by GreenTree1990** [MaybeShewill-CV/CRNN_Tensorflow#348]

**Comment by MaybeShewill-CV** [comment]
@GreenTree1990 可能是tensorflow安装的问题吧:)

**Comment by GreenTree1990** [comment]
感谢！
但我装的也是tensorflow1.12.0 而且tfrecords也跑完了 

是运行第一个epoch的时候 到train_shadownet的这一句 进程就被killed了
                _, train_ctc_loss_value, merge_summary_value = sess.run(
                    [optimizer, train_ctc_loss, merge_summary_op])

和机器或是gpu的内存有没有关系呢？

**Comment by MaybeShewill-CV** [comment]
@GreenTree1990 如果是显存问题应该是ＯＯＭ　一般不会被直接kill掉:)

**Comment by LJXLJXLJX** [comment]
被kill是因为内存占用过多，我也遇到了这个问题，不知道该怎么解决。

**Comment by GreenTree1990** [comment]
@LJXLJXLJX 
我后来解决了 发现我这里被kill不是因为内存问题 而是我装的cudnn版本不太对，一定要参照tensorflow推荐的版本安装，你可以再检查一下定位一下问题
