### ISSUE TITLE
Retraining for line with more than two words

### ISSUE THREAD

**Issue by eravallirao** [MaybeShewill-CV/CRNN_Tensorflow#351]
Can this architecture be used for longer text, If so what changes are needed to be made in order to get better accuracies.

**Comment by MaybeShewill-CV** [comment]
@eravallirao 1.Model input tensor size and final sequence length:)

**Comment by eravallirao** [comment]
Are there any optimal number which you can suggest for?

**Comment by MaybeShewill-CV** [comment]
@eravallirao That depends on your data:)

**Comment by eravallirao** [comment]
![b97d950fe186a99ad4c9869afeb68183](https://user-images.githubusercontent.com/49031948/66621164-c1609c00-ec00-11e9-8a14-200c725fe408.jpg)
My data is of this type, can you please suggest something

**Comment by eravallirao** [comment]
Do I need to change the LSTM layer from 256 to 512 and increase the layers of is the present one good enough

**Comment by MaybeShewill-CV** [comment]
@eravallirao No need to change that in my opinion:)
