### ISSUE TITLE
做中文预测，代码需要有点小改进，不然，result会为空

### ISSUE THREAD

**Issue by wandaoyi** [MaybeShewill-CV/CRNN_Tensorflow#353]
对于中文预测，需要将：
def recognize(image_path, weights_path, char_dict_path, ord_map_dict_path, is_vis, is_english=True):
中的 is_english 定义为 False，不然，预测的result 会显示为空。可以在
 parser.add_argument('-e', '--english', type=args_str2bool, nargs='?', const=True,
                            default="False",
                            help='Whether to display images')
然后，修改一下recognize 为下面的形式
recognize(
        image_path=args.image_path,
        weights_path=args.weights_path,
        char_dict_path=args.char_dict_path,
        ord_map_dict_path=args.ord_map_dict_path,
        is_vis=args.visualize,
        is_english=args.english
    )
定义一下。
我把这个留下，为后面的朋友少踩坑

**Comment by MaybeShewill-CV** [comment]
@wandaoyi 是的 否则会调用一个针对英文的分词工具。这个分词工具是不适用于中文的:)

**Comment by wandaoyi** [comment]
谢谢你的回复。


我贴出来的文件名，是中文的分词工具，后来，我debug 查原因，找到了原因，是 is_english  为 True，而你的 recognize 方法里面，没对这个变量做定义，只是运用默认值，所以，在 if is_english: 那里，做了操作。


我现在，下载了你百度云的数据，但是，那个 90k 的数据，下载不了，我没找到你的 相关的 .txt文档，不懂只做自己的数据集。暂时没办法训练。
我想请你，可否，发个文档给我，说明一下 .txt 文件 里面的信息指代什么，或截图说明一下。和如何制作 .txt 文件。






------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 晚上9:17
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com>; 
抄送: "求道"<1972241575@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] 做中文预测，代码需要有点小改进，不然，result会为空 (#353)




@wandaoyi 是的 否则会调用一个针对英文的分词工具。这个分词工具是不适用于中文的:)

**Comment by MaybeShewill-CV** [comment]
@wandaoyi 你留个邮箱 我找时间把那几个txt文件打包发给你

**Comment by wandaoyi** [comment]
好的，非常感谢，最好，能给个文档说明一下，如何制作 txt文件
邮箱为：1972241575@qq.com




------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 晚上9:40
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com>; 
抄送: "求道"<1972241575@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] 做中文预测，代码需要有点小改进，不然，result会为空 (#353)




@wandaoyi 你留个邮箱 我找时间把那几个txt文件打包发给你

**Comment by wandaoyi** [comment]
那，麻烦你帮忙描述一下， txt文件里面，代表什么意思。谢谢



------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 晚上9:55
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com>; 
抄送: "求道"<1972241575@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] 做中文预测，代码需要有点小改进，不然，result会为空 (#353)




@wandaoyi 如何制作的话 你自己看txt文件做吧 我暂时没有时间给你写说明文档==！

**Comment by wandaoyi** [comment]
大佬，你好，我已经下载到那个 90k 的数据了，并且，弄明白了数据之间的关系。你不用给我发 txt 文件了。
感谢你之前给予的帮助




------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 晚上9:55
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com>; 
抄送: "求道"<1972241575@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] 做中文预测，代码需要有点小改进，不然，result会为空 (#353)




@wandaoyi 如何制作的话 你自己看txt文件做吧 我暂时没有时间给你写说明文档==！

**Comment by wandaoyi** [comment]
------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 晚上9:55
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com>; 
抄送: "求道"<1972241575@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] 做中文预测，代码需要有点小改进，不然，result会为空 (#353)




@wandaoyi 如何制作的话 你自己看txt文件做吧 我暂时没有时间给你写说明文档==！

**Comment by MaybeShewill-CV** [comment]
@wandaoyi Ok:)

**Comment by ZhangZoffy** [comment]
> 对于中文预测，需要将：
> def recognize(image_path, weights_path, char_dict_path, ord_map_dict_path, is_vis, is_english=True):
> 中的 is_english 定义为 False，不然，预测的result 会显示为空。可以在
> parser.add_argument('-e', '--english', type=args_str2bool, nargs='?', const=True,
> default="False",
> help='Whether to display images')
> 然后，修改一下recognize 为下面的形式
> recognize(
> image_path=args.image_path,
> weights_path=args.weights_path,
> char_dict_path=args.char_dict_path,
> ord_map_dict_path=args.ord_map_dict_path,
> is_vis=args.visualize,
> is_english=args.english
> )
> 定义一下。
> 我把这个留下，为后面的朋友少踩坑

多谢，刚刚就掉坑里了。

**Comment by garspace** [comment]
我也掉坑里了，多谢
