### ISSUE TITLE
txt文件与图像间的关系

### ISSUE THREAD

**Issue by wandaoyi** [MaybeShewill-CV/CRNN_Tensorflow#354]
annotation.txt 文件中，由两个部分组成：image_path 和 label_index。如：
./3000/7/169_deliberations_20271.jpg 20271
它们之间以空格键隔开。

可以根据 image_path 找到目标图像，根据 label_index 在 lexicon.txt 文件中找到对应的 label。
如上面的例子，label 就在 lexicon.txt 的 20271 行，内容为: deliberation

同理，annotation_train.txt 里面的内容，也是一样的意义。

**Comment by wandaoyi** [comment]
我写这个，是为了给那些，下不到 synth90k数据 ，但是，又想自己做 数据，却又不明白 txt 含义的朋友一个 友好的 提示。这个，不算是问题，只是对 txt 文件的一个解说。

**Comment by MaybeShewill-CV** [comment]
@wandaoyi Thanks a lot. I will leave it here:)

**Comment by wandaoyi** [comment]
You are welcome

**Comment by YukMingLaw** [comment]
Thanks！This is a very useful information.

**Comment by wandaoyi** [comment]
you are welcome



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "York Law"<notifications@github.com&gt;; 
发送时间: 2019年11月8日(星期五) 晚上7:55
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)




Thanks！This is a very useful information.

**Comment by LW-CVer** [comment]
中文怎么办？这是以词来标注的吧，中文序列呢请问

**Comment by MaybeShewill-CV** [comment]
@LW-CVer 数据里面很多都不是词组而是句子

**Comment by wandaoyi** [comment]
中文是以 词 来标序号的。你仔细阅读以下，我记得，之前是有说明白的。只是，以前我无法上传图片，没办法图文结合讲解。但是，我是有文字说明的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LW-CVer"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 中午11:57
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 
中文怎么办？这是以词来标注的吧，中文序列呢请问

**Comment by wandaoyi** [comment]
你没发现，项目里面，有一个字典吗？你缕缕项目的思路先吧。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MaybeShewill-CV"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 中午12:52
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 
@LW-CVer 数据里面很多都不是词组而是句子

**Comment by 18796956836** [comment]
你好，我也想问中文数据集的图片都是句子，那么lexicon.txt里面也要写句子吗，还是有其他的形式呢

**Comment by wandaoyi** [comment]
这个，随便看一下逻辑，就知道了的呀。我们训练数据，有图片，有label。你的label 怎么来？
然后，将 label 根据 id，转为 数字。
而图片用卷积提取特征，进行损失计算。
这不是思路很简单嘛？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "18796956836"<notifications@github.com&gt;; 
发送时间: 2020年3月31日(星期二) 下午5:05
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 
你好，我也想问中文数据集的图片都是句子，那么lexicon.txt里面也要写句子吗，还是有其他的形式呢

**Comment by 18796956836** [comment]
对的。麻烦您了。我就是想问一下，中文数据集lexicon.txt里面写啥，不好意思，给你添麻烦了。

**Comment by 18796956836** [comment]
您好可以加一下联系方式吗，我想请教您问题，我的qq是992140698




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wandaoyi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 下午5:26
收件人:&nbsp;"MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"gsdfgdf"<992140698@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 这个，随便看一下逻辑，就知道了的呀。我们训练数据，有图片，有label。你的label 怎么来？ 
 然后，将 label 根据 id，转为 数字。 
 而图片用卷积提取特征，进行损失计算。 
 这不是思路很简单嘛？ 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "18796956836"<notifications@github.com&amp;gt;;  
 发送时间: 2020年3月31日(星期二) 下午5:05 
 收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&amp;gt;;  
 抄送: "求道"<1972241575@qq.com&amp;gt;; "Mention"<mention@noreply.github.com&amp;gt;;  
 主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354) 
 
 
 
 
 
   
 你好，我也想问中文数据集的图片都是句子，那么lexicon.txt里面也要写句子吗，还是有其他的形式呢

**Comment by wandaoyi** [comment]
我都好久没看这个了，你自己捋捋代码和思路，就知道的了。我之前没办法上传图片上去说明(好像是不给传)，久了，就忘记了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fagrgarhtshtj"<notifications@github.com&gt;; 
发送时间: 2020年3月31日(星期二) 下午5:33
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 
对的。麻烦您了。我就是想问一下，中文数据集lexicon.txt里面写啥，不好意思，给你添麻烦了。

**Comment by 18796956836** [comment]
好的，十分感谢。

**Comment by wandaoyi** [comment]
我晚上有空，找找看，如果能找到这个项目，再给你发一份吧我记得，我没用原来的，我是修改了的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fagrgarhtshtj"<notifications@github.com&gt;; 
发送时间: 2020年3月31日(星期二) 下午5:40
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 
好的，十分感谢。

**Comment by 18796956836** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wandaoyi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 下午5:42
收件人:&nbsp;"MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"gsdfgdf"<992140698@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 我晚上有空，找找看，如果能找到这个项目，再给你发一份吧我记得，我没用原来的，我是修改了的 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "fagrgarhtshtj"<notifications@github.com&amp;gt;;  
 发送时间: 2020年3月31日(星期二) 下午5:40 
 收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&amp;gt;;  
 抄送: "求道"<1972241575@qq.com&amp;gt;; "Mention"<mention@noreply.github.com&amp;gt;;  
 主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354) 
 
 
 
 
 
   
 好的，十分感谢。

**Comment by wandaoyi** [comment]
我没空去给你捋这东西呀，只能你自己去捋了。不然，你让那个作者给你提供一份吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fagrgarhtshtj"<notifications@github.com&gt;; 
发送时间: 2020年3月31日(星期二) 下午5:35
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 您好可以加一下联系方式吗，我想请教您问题，我的qq是992140698 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"wandaoyi"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月31日(星期二) 下午5:26 
 收件人:&amp;nbsp;"MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"gsdfgdf"<992140698@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354) 
 
 
 
 
 
  这个，随便看一下逻辑，就知道了的呀。我们训练数据，有图片，有label。你的label 怎么来？  
  然后，将 label 根据 id，转为 数字。  
  而图片用卷积提取特征，进行损失计算。  
  这不是思路很简单嘛？  
   
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "18796956836"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年3月31日(星期二) 下午5:05  
  收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&amp;amp;gt;;   
  抄送: "求道"<1972241575@qq.com&amp;amp;gt;; "Mention"<mention@noreply.github.com&amp;amp;gt;;   
  主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)  
   
   
   
   
   
     
  你好，我也想问中文数据集的图片都是句子，那么lexicon.txt里面也要写句子吗，还是有其他的形式呢

**Comment by lulupanPPY** [comment]
pre-trained model下载不了，有其他地址么？

**Comment by wandaoyi** [comment]
您好，你下载不了，是由于没有科学上网吗？你要先确定你可以科学上网，再去下载。
里面的英文model 是很好的，但是，中文model 不怎么样，需要你自己重新训练的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lulupanPPY"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 中午12:54
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 
pre-trained model下载不了，有其他地址么？

**Comment by MaybeShewill-CV** [comment]
@lulupanPPY @wandaoyi 中文模型之前上传错了 我已经重新上传过链接了 暂时没有dropbox以外的链接存放方式 中文模型路径 https://www.dropbox.com/sh/z22xsn4byddalv3/AAAiIxAHJKbqy44M73ow5znSa?dl=0 可以参考这个issue #390

**Comment by wandaoyi** [comment]
大佬，您可以把这个英文 和 中文的 模型，发一下给我，或百度云给我一下链接吗？我现在，也无法科学上网，都打不开这个网址。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MaybeShewill-CV"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 中午1:34
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 
@lulupanPPY @wandaoyi 中文模型之前上传错了 我已经重新上传过链接了 暂时没有dropbox以外的链接存放方式 中文模型路径 https://www.dropbox.com/sh/z22xsn4byddalv3/AAAiIxAHJKbqy44M73ow5znSa?dl=0 可以参考这个issue #390

**Comment by MaybeShewill-CV** [comment]
@wandaoyi 暂时没有办法:)

**Comment by wandaoyi** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MaybeShewill-CV"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 晚上8:22
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 
@wandaoyi 暂时没有办法:)

**Comment by aaferrero** [comment]
能发一份模型给我嘛，我下载不了，邮箱402059208@qq.com，万分感谢！

**Comment by wandaoyi** [comment]
链接：https://pan.baidu.com/s/1fmtWIITiF22vsQbIernl7A&nbsp;
提取码：tuzu





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aaferrero"<notifications@github.com&gt;; 
发送时间: 2020年7月10日(星期五) 晚上6:23
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





 
能发一份模型给我嘛，我下载不了，邮箱402059208@qq.com，万分感谢！

**Comment by aaferrero** [comment]
> 链接：https://pan.baidu.com/s/1fmtWIITiF22vsQbIernl7A&nbsp; 提取码：tuzu
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aaferrero"<notifications@github.com&gt;; 发送时间: 2020年7月10日(星期五) 晚上6:23 收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354) 能发一份模型给我嘛，我下载不了，邮箱402059208@qq.com，万分感谢！ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
谢谢！

**Comment by wandaoyi** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aaferrero"<notifications@github.com&gt;; 
发送时间: 2020年7月11日(星期六) 中午11:05
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





  
链接：https://pan.baidu.com/s/1fmtWIITiF22vsQbIernl7A&nbsp; 提取码：tuzu
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aaferrero"<notifications@github.com&gt;; 发送时间: 2020年7月10日(星期五) 晚上6:23 收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354) 能发一份模型给我嘛，我下载不了，邮箱402059208@qq.com，万分感谢！ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
 谢谢！

**Comment by wandaoyi** [comment]
发了两次图片说明，都发不成功图片。txt文件与图像的关系如图：
链接：https://pan.baidu.com/s/1_qOSRn7Pf0XwTbL-yflQFw&nbsp;
提取码：pouw

希望对大家有用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aaferrero"<notifications@github.com&gt;; 
发送时间: 2020年7月11日(星期六) 中午11:05
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354)





  
链接：https://pan.baidu.com/s/1fmtWIITiF22vsQbIernl7A&nbsp; 提取码：tuzu
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aaferrero"<notifications@github.com&gt;; 发送时间: 2020年7月10日(星期五) 晚上6:23 收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 抄送: "求道"<1972241575@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] txt文件与图像间的关系 (#354) 能发一份模型给我嘛，我下载不了，邮箱402059208@qq.com，万分感谢！ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
 谢谢！

**Comment by wouterk1MSS** [comment]
Hi, 
perhaps related; I'm getting the following error when trying to load the checkpoint: 
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape= [512,5825]
	 [[Node: save/Assign_45 = Assign[T=DT_FLOAT, _class=["loc:@shadow_net/sequence_rnn_module/w"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shadow_net/sequence_rnn_module/w, save/RestoreV2_45)]]
	 
Is this the correct input?:

python tools/test_shadownet.py --image_path ./1.png --weights_path checkpoint2/shadownet.ckpt-322000 --char_dict_path data/char_dict/char_dict_cn.json --ord_map_dict_path data/char_dict/ord_map_cn.json

many thanks!
