### ISSUE TITLE
将配置文件中的图片高度项改成48，训练的时候报错是为什么呢？是网络对输入图片的高度有限制吗？谢谢

### ISSUE THREAD

**Issue by Leedorado** [MaybeShewill-CV/CRNN_Tensorflow#355]

**Comment by MaybeShewill-CV** [comment]
@Leedorado 高度有限制:)

**Comment by Leedorado** [comment]
限制在多大的值？如何解除这个限制？thx~~

**Comment by MaybeShewill-CV** [comment]
@Leedorado 默认配置看config文件.要修改这个配置，你需要修改这个base network. 细节可以参考CRNN原文:)

**Comment by Leedorado** [comment]
能否具体些呢，我看原文里是按照高度为32去resize的，没提其他高度下如何去修改网络啊，thx~~

**Comment by MaybeShewill-CV** [comment]
@Leedorado 看下CNN base net提取的特征进入lstm那部分吧:)
