### ISSUE TITLE
Get position of definied symbols

### ISSUE THREAD

**Issue by oleshkoo** [MaybeShewill-CV/CRNN_Tensorflow#356]
I need to get positions of current recognized symbols. How can I solve it? Thanks for answers

**Comment by MaybeShewill-CV** [comment]
@oleshkoo What do you mean about the position here:)

**Comment by oleshkoo** [comment]
I need to get coordinates of symbol like [[x1, y1], [x2, y2]]

**Comment by MaybeShewill-CV** [comment]
@oleshkoo You may need text detection not text recognition:)
