### ISSUE TITLE
crnn_synth90k的模型是不是不能识别数字？

### ISSUE THREAD

**Issue by ZhangZoffy** [MaybeShewill-CV/CRNN_Tensorflow#360]
![timg](https://user-images.githubusercontent.com/28424232/67071892-470eb980-f1b6-11e9-9519-fe616f0c8645.jpg)
这个图片识别出来的结果是
Predict image timg.jpg result: dec s

**Comment by MaybeShewill-CV** [comment]
@ZhangZoffy 你自己看看synth90k这个数据集哈:)
