### ISSUE TITLE
Poor performance of the pre-trained model on the given test images

### ISSUE THREAD

**Issue by AyushP123** [MaybeShewill-CV/CRNN_Tensorflow#363]
Hi,
I used the models weights provided [here](https://www.dropbox.com/sh/y4eaunamardibnd/AAB4h8NkakASDoc6Ek4knEGIa?dl=0). To test if the installation was complete and successful I ran it on images provided in data/test_images/. I am getting the incorrect output ( Image with MASSAGING recognised as "massa g ling" ). 

Tensorflow version: 1.12.0

**Comment by MaybeShewill-CV** [comment]
@AyushP123 You may test to remove the wordnji function. See the code here https://github.com/MaybeShewill-CV/CRNN_Tensorflow/blob/master/tools/test_shadownet.py remove line 131, 132:)

**Comment by AyushP123** [comment]
@MaybeShewill-CV, thanks for your response I removed the wordnji function and ran the code again. This time the spaces are removed and the output is "massagling". Is there a different set of weights with  which the inference was run.

**Comment by MaybeShewill-CV** [comment]
@AyushP123 Sorry I do not get your point. What do you mean of a different set of weights?

**Comment by AyushP123** [comment]
Different ckpt file. I am trying to decode the reason for the wrong output, given the fact that we have correct weights, we should get an correct output -> "massaging", instead the output I am getting is "massagling"

**Comment by MaybeShewill-CV** [comment]
@AyushP123 Sorry do not have different ckpt file here:)

**Comment by yyyash8** [comment]
I'm also getting the same error
Expected output: massaging
Result getting: massagling

**Comment by yyyash8** [comment]
> @AyushP123 Sorry do not have different ckpt file here:)



> @AyushP123 Sorry I do not get your point. What do you mean of a different set of weights?

He is trying to say that the weights that you have uploaded on cloud might be of lower epoch trained model that's why we're getting bad output

**Comment by MaybeShewill-CV** [comment]
@yyyash8 Adjust local variable new_width here  https://github.com/MaybeShewill-CV/CRNN_Tensorflow/blob/master/tools/test_shadownet.py line 78 and you may get what you want:)

**Comment by yyyash8** [comment]
> you

If I increase the height above 47 I'm getting this assertion error: 
![Screenshot from 2019-11-06 13-58-49](https://user-images.githubusercontent.com/26182522/68281488-c00a7e00-009d-11ea-92c5-d80e8eed7d1b.png)

**Comment by MaybeShewill-CV** [comment]
@yyyash8 adjust new_width not new_height:)

**Comment by yyyash8** [comment]
> @yyyash8 adjust new_width not new_height:)

 I wanted to ask does synth90k dataset doesn't have numbers in it.

**Comment by MaybeShewill-CV** [comment]
@yyyash8 You may check yourself:)

**Comment by yyyash8** [comment]
Thank you

**Comment by MaybeShewill-CV** [comment]
@yyyash8 Welcome:)
