### ISSUE TITLE
请问作者,准确率是怎么计算的啊

### ISSUE THREAD

**Issue by 1810325** [MaybeShewill-CV/CRNN_Tensorflow#364]
@MaybeShewill-CV 您好,请问一下准确率是怎么计算的啊,另外我想怎么才能知道模型中的参数有多少啊

**Comment by MaybeShewill-CV** [comment]
@1810325 1.准确率计算可以参考https://github.com/MaybeShewill-CV/CRNN_Tensorflow/blob/master/local_utils/evaluation_tools.py compute_accuracy函数 2.模型的可训练参数个数可以通过统计tf.trainable_varaiables长度获取．

**Comment by 1810325** [comment]
@MaybeShewill-CV 谢谢您的回复,我去看看
