### ISSUE TITLE
Support tflite

### ISSUE THREAD

**Issue by sachaarbonel** [MaybeShewill-CV/CRNN_Tensorflow#365]
Hi @MaybeShewill-CV , I'm trying to export your model in order to convert it to tflite but I'm facing this error :
```
Unable to open table file new-model/shadownet.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node save/RestoreV2 (defined at tfserve/export_saved_model.py:1042)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```
Which version of tensorflow did you use for your trained model on Dropbox? My version is 1.12. Thank's for your incredible work on this.

**Comment by MaybeShewill-CV** [comment]
@Sach97 Use new-model/shadownet.ckpt instead:)

**Comment by Sach97** [comment]
Thank's @MaybeShewill-CV , it fixed my previous issue but we still need to wait on [Supporting control flow in TensorFlow Lite](https://github.com/tensorflow/tensorflow/issues/28485) to be able to convert this model to tflite. There are also several operators that will need to be implemented on the client side : CTC_BEAM_SEARCH_DECODER, LoopCond, RandomUniform, TensorArrayGatherV3, TensorArrayReadV3, TensorArrayScatterV3, TensorArrayV3, TensorArrayWriteV3.

**Comment by Sach97** [comment]
I guess we can use Mozilla : [ctc_beam_search_decoder](https://github.com/mozilla/DeepSpeech/blob/4c14c6b78b3daf90b67f840035a991bb94d9e1fa/native_client/ctcdecode/ctc_beam_search_decoder.h)

**Comment by MaybeShewill-CV** [comment]
@Sach97 Once I've got spare time. I will check for this. You may also contribute on this. You're welcome to pull requests:)

**Comment by Sach97** [comment]
@MaybeShewill-CV I would love to contribute to your project but I've some issues with the project setup it doesn't recognize the modules on any of my laptops like config and crnn_model. I haven't done any serious user facing project setup in python so don't quote me on this but I think we need a setup.py. I made a dirty workaround by copy pasting the modules in export_saved_model.py. Once I fix that maybe I'll be able to work on this. If you have sometime maybe we could schedule a 1:1 session on gitter.im or something to fix my environment ?

**Comment by MaybeShewill-CV** [comment]
@Sach97 You may set CRNN_PROJECT root dir in your PYTHONPATH:)

**Comment by Sach97** [comment]
Thank's I'll try that

**Comment by Jay-Kang1** [comment]
> @Sach97 Use new-model/shadownet.ckpt instead:)

Where can we find the new-model/shadownet.ckpt ? I have to same problem when I use the pretrained models on your [link](https://www.dropbox.com/sh/y4eaunamardibnd/AAB4h8NkakASDoc6Ek4knEGIa?dl=0)
