### ISSUE TITLE
中文模型转tensorflow serving后识别速度超慢

### ISSUE THREAD

**Issue by guanshuicheng** [MaybeShewill-CV/CRNN_Tensorflow#366]
使用楼主提供的ckpt模型，转换tensorflow serving可服务pb模型后部署了GPU，识别速度超慢（一个box大概是4秒），请问楼主有加速的方法吗？

**Comment by MaybeShewill-CV** [comment]
@guanshuicheng 1.本地测试模型看耗时是否正常，gpu是否正常启动 2.做frozen graph的时候减少beam search的beam width，但是这样可能会带来检测精度的损失 3.出问题的地方大概率是gpu没有正常启动或者你的网络传输有问题：）

**Comment by guanshuicheng** [comment]
> @guanshuicheng 1.本地测试模型看耗时是否正常，gpu是否正常启动 2.做frozen graph的时候减少beam search的beam width，但是这样可能会带来检测精度的损失 3.出问题的地方大概率是gpu没有正常启动或者你的网络传输有问题：）

十分感谢，我在转pb模型的时候调小了beam width，现在推理速度很快，但是识别的效果很差，和本地识别的效果差很多，不知如何改进？

**Comment by MaybeShewill-CV** [comment]
@guanshuicheng 是tfserve和本地运行得到的结果不一致吗?

**Comment by guanshuicheng** [comment]
差的很远，而且掉很多字




| |
追梦者
邮箱：18010149119@163.com
|

签名由 网易邮箱大师 定制

在2019年11月14日 18:43，MaybeShewill-CV 写道：

@guanshuicheng 是tfserve和本地运行得到的结果不一致吗?

**Comment by MaybeShewill-CV** [comment]
@guanshuicheng 本地结果应该和tfserve结果一致才对,检查下后处理部分的代码和用的模型还有参数文件是否一致吧。这些我都测试过, tfserve结果和本地结果是一致的:)

**Comment by guanshuicheng** [comment]
十分感谢，我检查一下。




| |
追梦者
邮箱：18010149119@163.com
|

签名由 网易邮箱大师 定制

在2019年11月14日 18:57，MaybeShewill-CV 写道：

@guanshuicheng 本地结果应该和tfserve结果一致才对,检查下后处理部分的代码和用的模型还有参数文件是否一致吧。这些我都测试过, tfserve结果和本地结果是一致的:)

**Comment by zhu2bowen** [comment]
@guanshuicheng 请问有解决问题吗？我CPU类似结果！见 #444
