### ISSUE TITLE
Model does not converge on larger dataset

### ISSUE THREAD

**Issue by guddulrk** [MaybeShewill-CV/CRNN_Tensorflow#367]
Hi,
I am trying to train the network on my own data-set, which has 0.5 million images of synthetic text words. I have increased the depth of the network (added more layers), changed learning rates, optimizers and kernel sizes. I also removed the max-pooling layer and used strided convolutional layers. But the network is not converging. Can you help me, what should I change so that the network can converge? 
The training cost does not reduce than the 12.

Thanks.

**Comment by MaybeShewill-CV** [comment]
@guddulrk I am afraid I can do nothing to help you with this. Remote assistance for such kind of a problem will not work in my opinion. Sorry for this:)

**Comment by guddulrk** [comment]
No problem.
Thanks
