### ISSUE TITLE
Excuse me, can we support binary image training

### ISSUE THREAD

**Issue by SimonWang00** [MaybeShewill-CV/CRNN_Tensorflow#368]
Thanks for the author's open source. I have a batch of pictures that have been binarized. Can I use our model for training？

**Comment by MaybeShewill-CV** [comment]
@SimonWang00 You need to change the first two stage of the cnn base net yourself if you want to use your own binary image. Or you can convert your binary image into 3 channel color image:)

**Comment by SimonWang00** [comment]
Thank you. I see. Can you share your Chinese recognition model to Baidu cloud disk? Dropbox can't access it. Thanks again

**Comment by SimonWang00** [comment]
> @SimonWang00 You need to change the first two stage of the cnn base net yourself if you want to use your own binary image. Or you can convert your binary image into 3 channel color image:)

Thank you. I see. Can you share your Chinese recognition model to Baidu cloud disk? Dropbox can't access it. Thanks again

**Comment by MaybeShewill-CV** [comment]
@SimonWang00 Sorry for that but i can not upload it there:)

**Comment by SimonWang00** [comment]
> @SimonWang00 Sorry for that but i can not upload it there:)

ok,thanks.
