### ISSUE TITLE
Upgrade to tensorflow 2.0

### ISSUE THREAD

**Issue by sachaarbonel** [MaybeShewill-CV/CRNN_Tensorflow#369]
In order to support tflite (see #365 ) we first need to upgrade to tensorflow 2.0 following this [article](https://medium.com/tensorflow/upgrading-your-code-to-tensorflow-2-0-f72c3a4d83b5).

**Comment by MaybeShewill-CV** [comment]
@Sach97 I will not upgrade my tensorflow to 2.0 recently but it will be done in the future:)
