### ISSUE TITLE
Other normalization scheme

### ISSUE THREAD

**Issue by hellbago** [MaybeShewill-CV/CRNN_Tensorflow#37]
Hi, i'm using your write_text_features.py script for storing my own data in tfrecords format. I'm trying to use a normalization scheme different from None ('divide_255' for example). The issue happens in this line of code:
`train_images = [bytes(list(np.reshape(tmp, [100 * 32 * 3]))) for tmp in train_images]`
and the error message is: 'numpy.float64' object cannot be interpreted as an integer

If i delete bytes form the instruction it works, but then I have problems with the encode function FeatureIO.bytes_feature in data_utils.py.
Any workaround for this issue? @TJCVRS 
Probably a possible solution is to store the data as integer without performing normalization inside write_text_features.py and then applying a normalization in the train script

**Comment by TJCVRS** [comment]
@hellbago Yep as what you said you could apply a normalization in training process.

**Comment by mdbenito** [comment]
@MaybeShewill-CV Since this is actually an issue with the way the tfrecords are built and is currently a bug, maybe we could leave it open? If we implement a workaround (e.g. a flag for tfrecords using bytes or another type) we can discuss / link here for reference

**Comment by MaybeShewill-CV** [comment]
@mdbenito Ok I will reopen it.
