### ISSUE TITLE
多个连续数字串的识别，如何提高准确率？

### ISSUE THREAD

**Issue by BigPandaCPU** [MaybeShewill-CV/CRNN_Tensorflow#376]

**Comment by BigPandaCPU** [comment]
作者您好：
      我在用你这个CRNN模型训练对连续数字串的识别的时候，连续数字的为数较多为24~25位，里面出现多个相同的连续的字符串，比如101000202005040000124068，最后识别为10100102102101150410101001241068。很容易将0和1这两个识别出错，会多个1或是将0识别为1。用到的参数文件如下：
![QQ截图20200103141612](https://user-images.githubusercontent.com/25834151/71709684-a97d6a80-2e33-11ea-98a2-82273401cfbd.png)

识别的结果接错误的如下：
![2019091904020000308205_num_deform_w_1_1_addnoise_0_1](https://user-images.githubusercontent.com/25834151/71709725-d893dc00-2e33-11ea-9995-295a53527367.jpg)
![jz_test_000_015_num_deform_h_0_9](https://user-images.githubusercontent.com/25834151/71709731-daf63600-2e33-11ea-9248-3eb85c02f923.jpg)
![jz_test_000_015_num_deform_w_1_1](https://user-images.githubusercontent.com/25834151/71709734-dd589000-2e33-11ea-8a76-02f0d583afc8.jpg)
![2019091904020000308205_num_lightness_0_87](https://user-images.githubusercontent.com/25834151/71709737-dfbaea00-2e33-11ea-9a76-647565cf4034.jpg)
这些数字是比较清晰的，但就是将0和1识别出错。想请问一下作者，这是啥原因呢？是CRNN模型本身就对连续的多个相同的字符识别准确率不高的原因吗？

**Comment by MaybeShewill-CV** [comment]
@BigPandaCPU 针对你自己需要使用的数据最好自己做一个模型finetune:)

**Comment by BigPandaCPU** [comment]
作者，您好：
通过一些实验，我发现我这问题所在了。主要是在训练和测试时候的预处理参数设置不一样导致的。
下图1
![1](https://user-images.githubusercontent.com/25834151/75844172-303ccc80-5e10-11ea-885b-ef408bf1f193.png)
![2](https://user-images.githubusercontent.com/25834151/75844176-329f2680-5e10-11ea-8456-e29c1c06da44.png)
这个在训练的时候，数据都是缩放到固定大小（280,32），而在测试的时候，看下图
![2](https://user-images.githubusercontent.com/25834151/75844250-64b08880-5e10-11ea-86cd-b838e50415c8.png)
数据的缩放时，高度时缩放到32像素，而宽度保持等比例缩放，并且当缩放后的宽大大于280时，保持原宽度，这就是为什么我这数据在识别时候出现多字符的原因。由于我这原始数据经过等比例缩放后，宽度大于原始宽度，导致输入到ctc的序列长度超过70，从而识别出比原始还多的字符。我在测试的时候，将输入参数改为和训练的一样，进行输入，识别结果就得到很大的提升。识别准确率在测试数据上能达到92%，之前的识别准确率不到60%。

**Comment by MaybeShewill-CV** [comment]
@BigPandaCPU 如果你的输入数据都是统一尺度的图像 那最好是缩放到统一的尺寸 测试的时候这么写主要是为了保持原始图像的长宽比:)

**Comment by MaybeShewill-CV** [comment]
@BigPandaCPU 赞

**Comment by BigPandaCPU** [comment]
谢谢作者的分享，我对CRNN的原理有了更深入的理解，也为你点赞！
