### ISSUE TITLE
识别一行汉字的数目有限制吗？

### ISSUE THREAD

**Issue by ballshapesdsd** [MaybeShewill-CV/CRNN_Tensorflow#379]
你好，我在自己的训练集上训练了模型，由于汉字的图片长度设置成了280*32，我的训练集汉字数量最多是10个，如果测试图片一行汉字的数目超过了10个，识别精度会不会下降？

**Comment by MaybeShewill-CV** [comment]
@ballshapesdsd 可以自己测试下：）

**Comment by ballshapesdsd** [comment]
> @ballshapesdsd 可以自己测试下：）

测试了下，好像没有什么限制，刚才的错误好像是模型的问题
