### ISSUE TITLE
关于准确率

### ISSUE THREAD

**Issue by ballshapesdsd** [MaybeShewill-CV/CRNN_Tensorflow#380]
你好，我看到你在下面贴的一个印刷体pdf中英文混杂的识别结果，效果好像不是很理想，出现了很多错误。我自己训练的结果也是这样，即使在非常简单的场景下（完美的印刷体，白底黑字），虽然大部分时候是不出错的，但有时候也可能出现错误，是我训练没有成功，还是模型本身的限制？我的loss最后降到了0.15左右。

**Comment by MaybeShewill-CV** [comment]
@ballshapesdsd 如果实际使用的话需要在自己使用的场景数据上finetune模型，直接拿来用是不行的。你也可以自己查看下你的数据和这里使用的训练数据之间的domain gap：）

**Comment by ballshapesdsd** [comment]
@MaybeShewill-CV 我是自己做了一个训练集的，都是白底黑字的印刷体，各种字体，但是效果还是不好。。。

**Comment by ballshapesdsd** [comment]
@MaybeShewill-CV 我就是想问问crnn能够达到多高的精度，不行的话我先分割再单字识别好了，感觉效果会好一些，印刷体的分割应该比较好做。

**Comment by ballshapesdsd** [comment]
@MaybeShewill-CV 好的，非常感谢，我自己再研究下
