### ISSUE TITLE
could you please tell me the solution for this?iam getting this:SyntaxError: Non-UTF-8 code starting with '\xff' in file test_02.jpg on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

### ISSUE THREAD

**Issue by santhubaby** [MaybeShewill-CV/CRNN_Tensorflow#381]

**Comment by MaybeShewill-CV** [comment]
@santhubaby not a bug from this repo. You may google how to solve it:)

**Comment by saravananponnaiah** [comment]
I had the similar problem and identified that this issue appears only when I use ui -> py command "**pyuic5 test.ui > test.py**". If I use the command "**pyuic5 -x test.ui -o test.py**", the issue got resolved. Probably, you can give a try once.
