### ISSUE TITLE
关于中文数据集转为tfrecords

### ISSUE THREAD

**Issue by zhiweiguo** [MaybeShewill-CV/CRNN_Tensorflow#384]
请问一下readme中的中文数据集如何转换为tfrecords呢？txt中的内容是： 图片路径   文字索引（包含多个文字）

**Comment by MaybeShewill-CV** [comment]
@zhiweiguo 看下这个文件 https://github.com/MaybeShewill-CV/CRNN_Tensorflow/blob/master/tools/write_tfrecords.py
