### ISSUE TITLE
crnn_chinese,Restoring from checkpoint failed

### ISSUE THREAD

**Issue by wzqy56789** [MaybeShewill-CV/CRNN_Tensorflow#386]
I run the following script ,but occur the error "Restoring from checkpoint failed." Could you answer?

python tools/recongnize_chinese_pdf.py -c ./data/char_dict/char_dict_cn.json -o ./data/char_dict/ord_map_cn.json --weights_path model/crnn_chinese/shadownet.ckpt --image_path data/test_images/test_pdf.png --save_path data/test_images/pdf_recognize_result.txt

tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from che
ckpoint failed. This is most likely due to a mismatch between the current graph
and the graph from the checkpoint. Please ensure that you have not altered the g
raph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [512,37] rhs shape=
[512,5825]
         [[node save/Assign_45 (defined at C:\ProgramData\Anaconda3\lib\site-pac
kages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/Assign_45':

**Comment by MaybeShewill-CV** [comment]
@wzqy56789 modify config file:)

**Comment by wzqy56789** [comment]
thanks a lot. I run successfully after modifying config file.

# Number character classes
__C.ARCH.NUM_CLASSES = 5825  # cn dataset
#__C.ARCH.NUM_CLASSES = 37  # synth90k dataset

**Comment by wzqy56789** [comment]
I run in windows ,suggest you add follows in the recongnize_chinese_pdf.py and others tools py file.

sys.path.append(os.getcwd())

**Comment by MaybeShewill-CV** [comment]
@wzqy56789 add module to PYTHONPATH can resolve this:)
