### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by yyynu** [MaybeShewill-CV/CRNN_Tensorflow#389]
When I going to test the picture through the pretrained crnn model weights on Synth90k, it occurs this question. How can I figure it?

**Comment by MaybeShewill-CV** [comment]
@yyynu check if your image path is valid or not:)

**Comment by yyynu** [comment]
> @yyynu check if your image path is valid or not:)

Thanks a lot. I've solved this question.

**Comment by yyynu** [comment]
Thanks a lot. I've solved this problem.
