### ISSUE TITLE
中文pretrained模型识别效果与readme结果不符

### ISSUE THREAD

**Issue by jackie930** [MaybeShewill-CV/CRNN_Tensorflow#390]
您好 

我按照readme运行识别chinese-pdf的结果如下，和您显示的有出入，但模型我是从您提供的dropbox直接下载使用的，不知道是什么原因造成结果的区别呢？

> 
> radSttinqs(J凶汹数可以载人之前使册月wrtSetnos)汹数所侏存的些设
>  望vleJ涿逡数的第.个参数盯以在疾有可月设堕望的情况下指定所需的默认僮在
>  应月程疗第一次适运行时，使虏的就是这些默认值出于炭舟为膨状或者鼠逝打开文伴
>  努表指定第.个参数，所以崔第一次适行时，窗日会使月侣意饱但是都俗理的大小利位
>  望，的鼠逝文伴匆表会是一个客表
>      在readSttinqs()租wrtSetins(中使州与QSettos档关的金部代翻为
>  MaiWndow所慈搭的布望方策，都尺是详多可丹方察中的一种比可以在应州
>  框房执行期阎的侄仰何时候和程劣代饵的乍仰何艳方，随时随趋创建一个QSttos劝
>  象，州它查询或者修淡一些设望
>      现在区经完成了劝Sprdshet的MiWndow的矣现在后续的几节中，
>  将会讨论姆仰何修放Spradshet应州框序来让它可以处理多文档以及如何矣现一个
>  框序启动酮曲(spshscren)烽会在下一草完成它的功能，包拒众式和排序的
>  处理

谢谢！！

**Comment by dashjim** [comment]
我也遇到同样的问题。使用的配置文件如下：
# Sequence length.  This has to be the width of the final feature map of the CNN, which is input size width / 4
__C.ARCH.SEQ_LENGTH = 70  # cn dataset
# __C.ARCH.SEQ_LENGTH = 25  # synth90k dataset
# Width x height into which training / testing images are resized before feeding into the network
__C.ARCH.INPUT_SIZE = (280, 32)  # cn dataset
# __C.ARCH.INPUT_SIZE = (100, 32)  # synth90k dataset
# Number of channels in images
__C.ARCH.INPUT_CHANNELS = 3
# Number character classes
__C.ARCH.NUM_CLASSES =5825  # cn dataset
# __C.ARCH.NUM_CLASSES = 37  # synth90k dataset

**Comment by juntao-hu** [comment]
使用作者Dropbox上提供的pretrain_model 运行 test_shadownet.py 测试识别单行文字，识别的结果和作者readme里展示的结果不一致：

`test_shadownet.py:133] Predict image test_04.jpg result: 计荆悬而未决发卡暨`  原文：计划悬而未决。发卡量

`test_shadownet.py:133] Predict image test_05.jpg result: 反动派茵反抗金被镇服]` 原文：反动派的反抗全被镇服

**Comment by MaybeShewill-CV** [comment]
@jackie930 @dashjim @juntao-hu 应该是我之前不小心把错误的模型替换到这个链接上了。由于这个项目已经比较久，我现在本地只有之前一个没有迭代完全的模型，我已经替换了原来错误的模型，你们可以试试。下载地址在这里 https://www.dropbox.com/sh/z22xsn4byddalv3/AAAiIxAHJKbqy44M73ow5znSa?dl=0 也欢迎你们训练新模型并提供效果展示 ：）

**Comment by MaybeShewill-CV** [comment]
@juntao-hu 刚上传的那个模型文件 效果如下：
![Screenshot from 2020-03-26 14-39-02](https://user-images.githubusercontent.com/15725187/77617758-e14a0900-6f6f-11ea-8a10-656f75a14e93.png)
![Screenshot from 2020-03-26 14-39-38](https://user-images.githubusercontent.com/15725187/77617767-e60ebd00-6f6f-11ea-939b-9dbd117f2344.png)

**Comment by MaybeShewill-CV** [comment]
@jackie930 刚上传的那个模型文件 效果如下：
![Screenshot from 2020-03-26 14-45-52](https://user-images.githubusercontent.com/15725187/77618078-98468480-6f70-11ea-89f2-ea5971d8b380.png)

**Comment by dashjim** [comment]
感谢！我马上试用下。

**Comment by MaybeShewill-CV** [comment]
@dashjim 如果测试中文模型需要修改global_config.py文件中的配置为中文相关的配置 具体可以看注释。 test_shadownet.py 中的recognize函数需要设置is_english为false避免使用wordninja分词

**Comment by dashjim** [comment]
@MaybeShewill-CV 收到。

**Comment by dashjim** [comment]
我重现了 @MaybeShewill-CV 的结果！

**Comment by MaybeShewill-CV** [comment]
@dashjim 好的 ok：）

**Comment by juntao-hu** [comment]
> @juntao-hu 刚上传的那个模型文件 效果如下：
> ![Screenshot from 2020-03-26 14-39-02](https://user-images.githubusercontent.com/15725187/77617758-e14a0900-6f6f-11ea-8a10-656f75a14e93.png)
> ![Screenshot from 2020-03-26 14-39-38](https://user-images.githubusercontent.com/15725187/77617767-e60ebd00-6f6f-11ea-939b-9dbd117f2344.png)

收到！感谢作者。

**Comment by MaybeShewill-CV** [comment]
@juntao-hu 不客气

**Comment by Lie-huo** [comment]
> 我重现了 @MaybeShewill-CV 的结果！

您好，我也把中文权重下载下来后，没有shadownet.ckpt 文件，只有checkpoint，shadownet.ckpt-322000.data-00000-of-00001，shadownet.ckpt-322000.index，shadownet.ckpt-322000.meta四个文件，这是怎么回事呢，是我下的不对吗，这应该怎么解决呢，求解答

**Comment by MaybeShewill-CV** [comment]
@Lie-huo 就这个文件 调用的时候输入正确的权重文件路径就完了:)
