### ISSUE TITLE
Problem of test the model on the single image?

### ISSUE THREAD

**Issue by Timthony** [MaybeShewill-CV/CRNN_Tensorflow#391]
If you want to test a single image you can do it with
python tools/test_shadownet.py --image_path PATH/TO/IMAGE 
--weights_path PATH/TO/MODEL_WEIGHTS
--char_dict_path PATH/TO/CHAR_DICT_PATH 
--ord_map_dict_path PATH/TO/ORD_MAP_PATH

"--weights_path PATH/TO/MODEL_WEIGHTS" 
Whether the selection of weights can be used directly use "model/crnn_syn90k_saved_model/1"?
If can, I encountered some errors.

**Comment by MaybeShewill-CV** [comment]
@tensor-flower crnn_syn90k_saved_model/1是给tfservering用的模型  你测试单张图 需要下载ckpt模型文件 例如中文模型在这里 https://www.dropbox.com/sh/z22xsn4byddalv3/AAAiIxAHJKbqy44M73ow5znSa?dl=0

**Comment by MaybeShewill-CV** [comment]
@Timthony 可以参考 #390

**Comment by Timthony** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好，有英文模型权重的地址吗，readme里边的失效了
    
        
            
        
    
    
    
    

    

    

    On 03/27/2020 14:42，MaybeShewill-CV<notifications@github.com> wrote： 




@Timthony 可以参考 #390

**Comment by MaybeShewill-CV** [comment]
@Timthony 英文的我这几天找时间重新上传下 之前上传的好像是个错误的权重文件:)

**Comment by Timthony** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，太感谢了，这个网站的链接是要科学上网吗，还是链接有问题，都打不开我这里。
    
        
            
        
    
    
    
    

    

    

    On 03/27/2020 14:46，MaybeShewill-CV<notifications@github.com> wrote： 




@Timthony 英文的我这几天找时间重新上传下 之前上传的好像是个错误的权重文件:)

**Comment by MaybeShewill-CV** [comment]
@Timthony 对 dropbox可能需要科学上网:)

**Comment by Timthony** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    好的，感谢，等您重新上传了英文的模型我再试试。
    
    
    

    

    

    On 03/27/2020 15:24，MaybeShewill-CV<notifications@github.com> wrote： 




@Timthony 对 dropbox可能需要科学上网:)

**Comment by MaybeShewill-CV** [comment]
@Timthony 模型链接已更新 https://www.dropbox.com/sh/y4eaunamardibnd/AAB4h8NkakASDoc6Ek4knEGIa?dl=0 可以下载尝试:)

**Comment by Timthony** [comment]
好的，感谢，但是这个和之前的模型网址是一样的，不知道有没有上传错误。



---Original---

**Comment by Timthony** [comment]
和之前一样的方式加载模型报错了。显示：ValueError: The passed save_path is not a valid checkpoint: /Users/tianhangz/Desktop/work/tianchi/chencode/CRNN_Tensorflow/model/crnn2/shadownet.ckpt&nbsp;









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MaybeShewill-CV"<notifications@github.com&gt;; 
发送时间: 2020年3月27日(星期五) 晚上10:09
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "781068447"<781068447@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] Problem of test the model on the single image? (#391)





 
@Timthony 模型链接已更新 https://www.dropbox.com/sh/y4eaunamardibnd/AAB4h8NkakASDoc6Ek4knEGIa?dl=0 可以下载尝试:)

**Comment by MaybeShewill-CV** [comment]
@Timthony 1.地址一样 但是模型文件不一样么 2. 你是怎么调用的 贴个command出来吧

**Comment by Timthony** [comment]
在调用tf.train.Saver#save时，如果使用的路径是绝对路径，那么保存的checkpoint里面用的就是绝对路径；如果使用的是相对路径，那么保存的checkpoint里面用的就是相对路径。正确的方法应该是使用相对路径进行保存，这样才能保证较好的可移植性。如果使用相对路径，复制到本地之后，会报找不到文件的错误。不知道是不是保存的时候的问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MaybeShewill-CV"<notifications@github.com&gt;; 
发送时间: 2020年3月27日(星期五) 晚上10:09
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;; 
抄送: "781068447"<781068447@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] Problem of test the model on the single image? (#391)





 
@Timthony 模型链接已更新 https://www.dropbox.com/sh/y4eaunamardibnd/AAB4h8NkakASDoc6Ek4knEGIa?dl=0 可以下载尝试:)

**Comment by Timthony** [comment]
python tools/test_shadownet.py --image_path data/test_images/test_01.jpg --weights_path model/crnn_synth90k2/shadownet.ckpt --char_dict_path data/char_dict/char_dict_en.json --ord_map_dict_path data/char_dict/ord_map_en.json

python tools/test_shadownet.py --image_path data/test_images/test_01.jpg --weights_path model/crnn_synth90k2/shadownet.ckpt-80000 --char_dict_path data/char_dict/char_dict_en.json --ord_map_dict_path data/char_dict/ord_map_en.json

换成第二个时候可以了，经过测试现在输出也是准确的了，感谢！

**Comment by Timthony** [comment]
这个英文的模型对数字也具有识别能力吗？

**Comment by MaybeShewill-CV** [comment]
@Timthony 1.是因为我上传的模型文件换了名字 没有同步更新readme 明天更新下 2.对数字有一定识别能力 但是主要要看你的应用场景和这个训练数据中的数据的domain gap是不是过大：）

**Comment by Timthony** [comment]
好的。
对数字进行了简单测试，对于网页截图对12345识别有时也会出错。下图的识别
![image](https://user-images.githubusercontent.com/25346492/77772748-991c0b00-7083-11ea-8305-dc72f95c6c16.png)


识别为：result: sralobhos

**Comment by MaybeShewill-CV** [comment]
@Timthony 你可以看下synth90k的数据集 就知道什么问题了：）

**Comment by Timthony** [comment]
> @Timthony 你可以看下synth90k的数据集 就知道什么问题了：）

看了下网站上synth90k的例子应该全是英文字符的，去不了学校没资源训练新模型--。

**Comment by MaybeShewill-CV** [comment]
@Timthony 有部分数字 但是比较少:)

**Comment by MaybeShewill-CV** [comment]
@Timthony 你可以试试中文模型 中文模型中的数字貌似还能多一点：）

**Comment by Timthony** [comment]
中文模型对英文有没有识别能力，我的主要是数字和英文。



---Original---

**Comment by MaybeShewill-CV** [comment]
@Timthony 那你可以尝试synthtext生成一部分训练数据 试试看：）

**Comment by Timthony** [comment]
好的，太感谢了，都试试，没gpu自己训练太麻烦T_T



---Original---

**Comment by MaybeShewill-CV** [comment]
@Timthony 好的 没有别的问题我就close了：）

**Comment by Timthony** [comment]
> @Timthony 好的 没有别的问题我就close了：）

好的，-^_^-

**Comment by Lie-huo** [comment]
您好，我把中文权重下载下来后，没有shadownet.ckpt 文件，只有checkpoint，shadownet.ckpt-322000.data-00000-of-00001，shadownet.ckpt-322000.index，shadownet.ckpt-322000.meta四个文件，这怎么解决呢

**Comment by Cabbagehust2507** [comment]
> 您好，我把中文权重下载下来后，没有shadownet.ckpt 文件，只有checkpoint，shadownet.ckpt-322000.data-00000-of-00001，shadownet.ckpt-322000.index，shadownet.ckpt-322000.meta四个文件，这怎么解决呢
shadownet.ckpt consists of hadownet.ckpt-322000.data-00000-of-00001，shadownet.ckpt-322000.index，shadownet.ckpt-322000.meta
