### ISSUE TITLE
在文件train_shadownet.py中387行 学习率的函数中有点疑惑

### ISSUE THREAD

**Issue by zgsxwsdxg** [MaybeShewill-CV/CRNN_Tensorflow#393]
learning_rate = tf.train.polynomial_decay(
        learning_rate=CFG.TRAIN.LEARNING_RATE,
        global_step=global_step,
        decay_steps=CFG.TRAIN.EPOCHS,
        end_learning_rate=0.000001,
        power=CFG.TRAIN.LR_DECAY_RATE
    )

参数 decay_step 为什么是训练总共的次数？期待您的回复，谢谢！

**Comment by MaybeShewill-CV** [comment]
@zgsxwsdxg 参考计算公式
![Uploading Screenshot from 2020-03-31 16-36-45.png…]()

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg 参考计算公式
您发的这个公式 好像不是求 decay_steps 的吧？

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg 参考计算公式

您发的这个公式，好像不是计算decay_steps的吧？还有我理解decay_steps 是不是每个多少次学习率会调整的意，但是你设置成总的训练次数的话，就相当于训练完了再调整，这样是不是没起到调整学习率的作用，我是一个小白，期待您回复

**Comment by MaybeShewill-CV** [comment]
@zgsxwsdxg decay_steps是个常数 这个学习率会随着global step的不断变化而变化

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg decay_steps是个常数 这个学习率会随着global step的不断变化而变化

谢谢，我这个问题，我理解了
