### ISSUE TITLE
中文数据集对应的labels问题

### ISSUE THREAD

**Issue by 18796956836** [MaybeShewill-CV/CRNN_Tensorflow#394]
你好，我如果用中文数据集，数据集中每个图片都是一句话的形式，那么lables在lexicon.txt中所对应的位置是不是也要写上图片上的那句话。因为我在尝试做中文数据集，遇到些问题。期待您的回复

**Comment by MaybeShewill-CV** [comment]
@18796956836 对 在对应位置写上label. 你可以自己仔细看看synth90k数据集的格式 还可以参考 #354  不难的：）

**Comment by 18796956836** [comment]
嗯，只不过工作量太大

**Comment by MaybeShewill-CV** [comment]
@18796956836 加油:)
