### ISSUE TITLE
你好当我在win10用spyder准备生成tfrecords时，程序停住了，我的命令是否对呢

### ISSUE THREAD

**Issue by WoshiBoluo** [MaybeShewill-CV/CRNN_Tensorflow#399]
我在console输的命令如下 %run tools/write_tfrecords.py --dataset_dir 'datasynth' --save_dir 'tfrecords'

程序停住只显示这些
W0426 11:37:33.968904 20376 warnings.py:99] D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])

WARNING:py.warnings:D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

W0426 11:37:33.969906 20376 warnings.py:99] D:\Anaconda\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

**Comment by MaybeShewill-CV** [comment]
@WoshiBoluo windows上的multiprocess和linux上不太一样 你翻一下前面的issue 有说到这个问题的:)
