### ISSUE TITLE
Need help with config

### ISSUE THREAD

**Issue by xxxpsyduck** [MaybeShewill-CV/CRNN_Tensorflow#401]
I have a chinese dataset with image in different sizes. How can I choose the ideal size for resizing when creating tfrecord? For more information: currently I'm using your config for chinese dataset, image size (280, 32), SEQ_LENGTH 70 but having "No valid path found" issue. Thank for all the help!

**Comment by MaybeShewill-CV** [comment]
@xxxpsyduck Modified the class nums in config file. And generate new char_dict.json and ord_map.json file:)

**Comment by xxxpsyduck** [comment]
@MaybeShewill-CV Already done that but having "No valid path found" issue :( I believe this can be solved by configure the right SEQ_LENGTH, and SEQ_LENGTH is related to image size (img_h/4). But I don't know how to select the proper img height
