### ISSUE TITLE
您好数据集太大了，我能否选取部分进行训练？

### ISSUE THREAD

**Issue by WoshiBoluo** [MaybeShewill-CV/CRNN_Tensorflow#402]
数据集太大传服务器时间太久了，想选部分数据生成tfrecords进行训练，请问数据集中的imlist.txt和lexicon.txt该怎么修改呢？Help啊Help！TAT

**Comment by MaybeShewill-CV** [comment]
@WoshiBoluo 可以 那部分你看下 #354 然后截取你需要的数据就好了。 然后统计下你的数据集中的类别数并生成新的json文件再训练就完了:)
