### ISSUE TITLE
Performance on unseen images

### ISSUE THREAD

**Issue by xxxpsyduck** [MaybeShewill-CV/CRNN_Tensorflow#403]
I've created for my own a synthetic dataset in Chinese which has 5M images (4.5M train, 500k test, 500k val). I trained the model on that and it recognize really well on the test set (can say 100%). But when I test an unseen image it can't recognize even a word. The texts in this image has similar font to the texts in my dataset. Can you please provide me some advices how to improve this? Thanks in advance!

**Comment by MaybeShewill-CV** [comment]
@xxxpsyduck I'm afraid can not provide useful tips on this since that problem is really data relative. Make sure the same preprocess was excuted on both train set and test set. If there is a big domain gap between train set and test set the model can not perform well:)
