### ISSUE TITLE
关于图像尺寸的问题

### ISSUE THREAD

**Issue by ZOUYIyi** [MaybeShewill-CV/CRNN_Tensorflow#405]
通过查看您的代码，发现代码中图像的输入尺寸被限定在（32，100）或一固定值，但是我查看论文时，发现论文中只是对图像高度有限制，而宽度则保持原有比例进行相应缩放，与代码中不一致。请问是我理解有错误还是您的代码中做了简化？

**Comment by MaybeShewill-CV** [comment]
@ZOUYIyi 是我在处理的时候统一了尺寸:)
