### ISSUE TITLE
能否给一个百度云的预训练模型

### ISSUE THREAD

**Issue by ywking** [MaybeShewill-CV/CRNN_Tensorflow#406]
模型的与训练无法下载

**Comment by MaybeShewill-CV** [comment]
@ywking 这个暂时不方便哈==！ sorry

**Comment by ywking** [comment]
好吧



---原始邮件---
发件人: "MaybeShewill-CV"<notifications@github.com&gt;
发送时间: 2020年6月3日(周三) 下午2:06
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"ywking"<1183235940@qq.com&gt;;
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] 能否给一个百度云的预训练模型 (#406)




 
@ywking 这个暂时不方便哈==！ sorry

**Comment by MaybeShewill-CV** [comment]
@ywking 你可以留个邮箱 要哪个链接的模型 你发给我 我下来有时间单独发给你好了

**Comment by ywking** [comment]
带中文的那个训练模型我邮箱1183235940@qq.com



---原始邮件---
发件人: "MaybeShewill-CV"<notifications@github.com&gt;
发送时间: 2020年6月3日(周三) 下午2:18
收件人: "MaybeShewill-CV/CRNN_Tensorflow"<CRNN_Tensorflow@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"ywking"<1183235940@qq.com&gt;;
主题: Re: [MaybeShewill-CV/CRNN_Tensorflow] 能否给一个百度云的预训练模型 (#406)




 
@ywking 你可以留个邮箱 要哪个链接的模型 你发给我 我下来有时间单独发给你好了

**Comment by MaybeShewill-CV** [comment]
@ywking 好 下来找时间发给你:)
