### ISSUE TITLE
Is that support handwritten chinese text?

### ISSUE THREAD

**Issue by dagongji10** [MaybeShewill-CV/CRNN_Tensorflow#407]
@mdbenito 
Is that work support handwritten chinese text recognition?

**Comment by MaybeShewill-CV** [comment]
@dagongji10 The pretrained model doesn't support. You may train your own model:)

**Comment by dagongji10** [comment]
@MaybeShewill-CV 
So that is to say, this model still supports handwritten Chinese character text sequence, just need to do transfer learning?

**Comment by MaybeShewill-CV** [comment]
@dagongji10 Yep
