### ISSUE TITLE
English data set

### ISSUE THREAD

**Issue by yang-gis** [MaybeShewill-CV/CRNN_Tensorflow#409]
Hello,thanks for your nice repo!Since the sy90k dataset is large ,I would like to makesure whether existing English characters and numbers for sy90k dataset or not.As far as as know, sy90k contains only English characters.Looking forward to your reply!

**Comment by MaybeShewill-CV** [comment]
@yang-gis You may check the label file which is not hard for you in my view:)

**Comment by yang-gis** [comment]
> @yang-gis You may check the label file which is not hard for you in my view:)



> @yang-gis You may check the label file which is not hard for you in my view:)



> @yang-gis You may check the label file which is not hard for you in my view:)

Thanks for your reply!I have checked it.It's obviously that the dataset don't contain  numbers.But after testing your weights file for recognizing english and numbers,I suppose your English train dataset contains English characters and numbers.Could you release your numbers dataset for training and testing?
