### ISSUE TITLE
Annotation and pipeline for lexicon free custom dataset

### ISSUE THREAD

**Issue by AumXIV** [MaybeShewill-CV/CRNN_Tensorflow#410]
Hello, I’m working on license plate which is lexicon free. Now I understand about Synth90k dataset which is lexicon. And my annotation is shown below. How can I use this dataset for CRNN? 

![image](https://user-images.githubusercontent.com/42962440/87378858-6873c900-c5c1-11ea-9baa-68327f56ffba.png)

I wonder if the Chinese recognition example could help, but I can’t download the dataset. Is the Chinese dataset use the same pipeline with Synth90k? And the same tfrecord?

![image](https://user-images.githubusercontent.com/42962440/87378886-7fb2b680-c5c1-11ea-9b77-def2771ca877.png)

I can also write char_dict_th.json and ord_map_th.json from my char_dict_th.txt by using local_utils/establish_char_dict.py to generate the json file. But the ord_map_th.json have repeatedly number 32, I don’t know that it can use or not. Please give me some suggestions. Thanks. :)

![image](https://user-images.githubusercontent.com/42962440/87380001-1da78080-c5c4-11ea-99cc-7c8a88c7d379.png)
![image](https://user-images.githubusercontent.com/42962440/87380054-3adc4f00-c5c4-11ea-925c-573ed9cc0c9b.png) ![image](https://user-images.githubusercontent.com/42962440/87380104-5b0c0e00-c5c4-11ea-9dff-1bb49957b2e7.png) ![image](https://user-images.githubusercontent.com/42962440/87380061-3fa10300-c5c4-11ea-9fa7-00cdca87a208.png)

**Comment by MaybeShewill-CV** [comment]
@AumXIV 1.If you want use new dataset. You can remove ./data/char_dict/*.json. The char_dict.json and ord_map.json file will be automatically generated when you make the tfrecords. 2. As for the repetition in order_map.json that may due to the repetition in your char_dict.txt file. The old_map.json file records the character's ord number:)

**Comment by AumXIV** [comment]
Okay, thanks. Here, I try the tfrecord and some errors are appearing. :)
![image](https://user-images.githubusercontent.com/42962440/87402406-19905880-c5ee-11ea-871d-fa3b55ad8d25.png)

**Comment by MaybeShewill-CV** [comment]
@AumXIV Label index should be a number sequence. You should follow the synth90k's dataset format to reconstruct your dataset. As for dataset's format this may help #354

**Comment by AumXIV** [comment]
So you mean I must have a lexicon file? How about let the lexicon file be like the label of each image? 
![image](https://user-images.githubusercontent.com/42962440/87496647-9b33c500-c686-11ea-94a9-9e41cc743b71.png) ![image](https://user-images.githubusercontent.com/42962440/87496663-a129a600-c686-11ea-98fe-c3127459113b.png)
Become like this?
![image](https://user-images.githubusercontent.com/42962440/87496695-b0105880-c686-11ea-8e06-5662db6170c7.png)

**Comment by MaybeShewill-CV** [comment]
@AumXIV The second col in annotation file should be the row index in lexicon file:)

**Comment by AumXIV** [comment]
From 
![image](https://user-images.githubusercontent.com/42962440/87499520-18facf00-c68d-11ea-9043-bd9b37178759.png)
Become
![image](https://user-images.githubusercontent.com/42962440/87499539-21eba080-c68d-11ea-85d2-54d74350173c.png)

Right? :)

**Comment by MaybeShewill-CV** [comment]
@AumXIV Right. But I'm not sure if the row index begin with 0 or 1. You may check it yourself:)

**Comment by AumXIV** [comment]
Okay, now I can generate tfrecord and train the model. Thank you lots. :)  ><

**Comment by GarhwalRifles** [comment]
@AumXIV @MaybeShewill-CV so row index begin with 0 right??

**Comment by XinyuDu** [comment]
> @AumXIV @MaybeShewill-CV so row index begin with 0 right??

yes, the row index begin with 0. 
In annotation.txt of synth90k's dataset:
`./2919/3/160_0_0.jpg 0`
