### ISSUE TITLE
problem while reading 

### ISSUE THREAD

**Issue by padmareddy21** [MaybeShewill-CV/CRNN_Tensorflow#411]
when trying to run test_shadownet.py I am getting this error
Traceback (most recent call last):
  File "tools/test_shadownet.py", line 160, in <module>
    is_vis=args.visualize
  File "tools/test_shadownet.py", line 78, in recognize
    image = cv2.resize(image, dsize=tuple(CFG.ARCH.INPUT_SIZE), interpolation=cv2.INTER_LINEAR)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
I couldn't figure why

**Comment by MaybeShewill-CV** [comment]
@padmareddy21 Your image was not correctly read into the model:)

**Comment by padmareddy21** [comment]
python tools/test_shadownet.py --weights_path model/crnn_syn90k_saved_model/1/saved_model.pb --char_dict_path data/char_dict/char_dict_en.json --ord_map_dict_path data/char_dict/ord_map_en.json --image_path test_01.jpg
I gave the same image that u provided in your images file

**Comment by MaybeShewill-CV** [comment]
@padmareddy21 Use absolute path will fix your problem:)

**Comment by padmareddy21** [comment]
> @padmareddy21 Use absolute path will fix your problem:)

which absolute path
The one u provided in readme file
