### ISSUE TITLE
please can you help me here 

### ISSUE THREAD

**Issue by padmareddy21** [MaybeShewill-CV/CRNN_Tensorflow#412]
python tools/test_shadownet.py --image_path data/test_images/card.png --weights_path model/shadownet.ckpt --char_dict_path data/char_dict/char_dict_en.json --ord_map_dict_path data/char_dict/ord_map_en.json
I0722 17:55:55.043348 18306 utils.py:129] Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
I0722 17:55:55.043450 18306 utils.py:141] NumExpr defaulting to 8 threads.
Namespace(char_dict_path='data/char_dict/char_dict_en.json', image_path='data/test_images/card.png', ord_map_dict_path='data/char_dict/ord_map_en.json', visualize=None, weights_path='model/shadownet.ckpt')
Traceback (most recent call last):
  File "tools/test_shadownet.py", line 160, in <module>
    is_vis=args.visualize
  File "tools/test_shadownet.py", line 76, in recognize
    cv2.imshow('',image)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/highgui/src/window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'
That image is readable when I am trying with OpenCV but when I am running with model it is unable to read

**Comment by MaybeShewill-CV** [comment]
@padmareddy21 That's not a bug relative to this repo. You may find a solution yourself:)
