### ISSUE TITLE
crnn_synth90k weights 

### ISSUE THREAD

**Issue by padmareddy21** [MaybeShewill-CV/CRNN_Tensorflow#413]
The downloaded crnn_synth90k I downloaded is in a different format,
I got the below four file
checkpoint
shadownet.ckpt-80000.data-00000-of-00001
shadownet.ckpt-80000.index
shadownet.ckpt-80000.meta
Now which one should I be using
I followed your readme file and everything went well but I cannot figure this one

**Comment by MaybeShewill-CV** [comment]
@padmareddy21 --weights_path ./shadownet.ckpt

**Comment by padmareddy21** [comment]
I couldn't find any file in the format, I have files with this format shadownet.ckpt-80000.data-00000-of-00001

**Comment by MaybeShewill-CV** [comment]
@padmareddy21 Just type what i paste here in your command terminal.

**Comment by padmareddy21** [comment]
but you said in readme file to download defined weights files but those are in different format.How to get those to normal form

**Comment by MaybeShewill-CV** [comment]
@padmareddy21 Learn some basic tensorflow knowledge first:)

**Comment by padmareddy21** [comment]
I know they should be restored but when trying to restore I am getting an error

**Comment by beyonder01** [comment]
!python tools/test_shadownet.py --image_path data/test_images/test_01.jpg 
--weights_path /content/shadownet.ckpt-80000 
--char_dict_path data/char_dict/char_dict_en.json --ord_map_dict_path data/char_dict/ord_map_en.json
