### ISSUE TITLE
crnn tensorflow with openvino

### ISSUE THREAD

**Issue by GarhwalRifles** [MaybeShewill-CV/CRNN_Tensorflow#416]
hi, thanks for the project, i trained the model with custom dataset around 1000 images, and with test_shadownet i can also see the outputs.
i was following https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_CRNN_From_Tensorflow.html and got this project's link, now i have created frozen graph as instructed in this link, only thing i changed in step 3 is  
`frozen = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, ['shadow/LSTMLayers/transpose_time_major'])` 
i was getting error  shadow/LSTMLayers/transpose_time_major is not in the graph
i changed it to 
`frozen = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, ['shadow_net/sequence_rnn_module/stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/fw/while/Identity_2'])`
and without any error frozen_graph.pb got generated

then i am trying to use this in this sample https://github.com/opencv/opencv/blob/master/samples/dnn/text_detection.cpp 

but here i got error 
`[ERROR:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.3\build\windows\opencv\modules\dnn\src\dnn.cpp (3272) cv::dnn::dnn4_v20200310::Net::Impl::getLayerShapesRecursively OPENCV/DNN: []:(_input): getMemoryShapes() throws exception. inputs=1 outputs=0/0 blobs=0
[ERROR:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.3\build\windows\opencv\modules\dnn\src\dnn.cpp (3275) cv::dnn::dnn4_v20200310::Net::Impl::getLayerShapesRecursively input[0] = [ 1 1 32 100 ]
[ERROR:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.3\build\windows\opencv\modules\dnn\src\dnn.cpp (3285) cv::dnn::dnn4_v20200310::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.3.0-openvino-2020.3.0) C:\jenkins\workspace\OpenCV\OpenVINO\2020.3\build\windows\opencv\modules\dnn\src\dnn.cpp:790: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'cv::dnn::dnn4_v20200310::DataLayer::getMemoryShapes'

OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.3.0-openvino-2020.3.0) Error: Assertion failed (inputs.size() == requiredOutputs) in cv::dnn::dnn4_v20200310::DataLayer::getMemoryShapes, file C:\jenkins\workspace\OpenCV\OpenVINO\2020.3\build\windows\opencv\modules\dnn\src\dnn.cpp, line 790`

i have uploaded my model to drive https://drive.google.com/drive/folders/1wgFcC3a5jMqcRFvKmj4XFAv_b7ATt9xV?usp=sharing please have a look.

**Comment by MaybeShewill-CV** [comment]
@GarhwalRifles Shape mismatch problem occured according to opencv's assertion. Can not figure out what happened here. I have not tested to convert it into OPENVINO. I'm afraid i can not help you here.

**Comment by GarhwalRifles** [comment]
thanks for your reply,
ok for some confirmation , i am new to tensorflow and deep learning
 while generating frozen_graph from the openvino link i have changed following line 
`frozen = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, ['shadow/LSTMLayers/transpose_time_major'])`
to  
`frozen = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, ['shadow_net/sequence_rnn_module/stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/fw/while/Identity_2'])`

is that ok.

**Comment by MaybeShewill-CV** [comment]
@GarhwalRifles You may change the output node like that but I'm not sure that node called 'shadow_net/sequence_rnn_module/stack_bidirectional_rnn/cell_0/bidirectional_rnn/fw/fw/while/Identity_2' is that what you need.

**Comment by GarhwalRifles** [comment]
@MaybeShewill-CV  yes i think that is right, and in the opencv c++ sample that code is using NCHW format and i checked my frozen_graph with netron application and input requires NHWC format so now i think i need to convert NCHW to NHWC,

can you help me to how can i convert NCHW to NHWC in c++ opencv.

**Comment by MaybeShewill-CV** [comment]
@GarhwalRifles You may get a better answer to that in OPENVINO repo.
