### ISSUE TITLE
Error with tensorflow  Serve

### ISSUE THREAD

**Issue by sushantag9** [MaybeShewill-CV/CRNN_Tensorflow#417]
external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at ctc_decoder_ops.cc:288 : Failed precondition: sequence_length(0) <= 128

I am getting this error

**Comment by MaybeShewill-CV** [comment]
@sushantag9 Can not figure out what happened:)
