### ISSUE TITLE
固定label shape后训练loss比较高

### ISSUE THREAD

**Issue by wb-finalking** [MaybeShewill-CV/CRNN_Tensorflow#422]
你好，我在使用synth90k数据集训练，原始代码中label shape是每个batch动态变化的，由于某些原因我这边需要固定shape且将sparse tensor密集化，因此将label长度固定为最大的长度同时对其他位置填默认值为num_classes-1，最后使用ctc_loss_v2（tensorflow1.15）做计算。最后loss一直稳定在25左右，麻烦您帮忙看一看
```
I1020 18:59:10.391937 3817 train_shadownet.py:336] Epoch_Train: 1047 cost= 24.408293
I1020 18:59:10.959847 3817 train_shadownet.py:336] Epoch_Train: 1048 cost= 25.260067
I1020 18:59:11.530904 3817 train_shadownet.py:336] Epoch_Train: 1049 cost= 25.272688
I1020 18:59:12.099234 3817 train_shadownet.py:336] Epoch_Train: 1050 cost= 25.382938
I1020 18:59:12.661026 3817 train_shadownet.py:336] Epoch_Train: 1051 cost= 25.619183
I1020 18:59:13.231471 3817 train_shadownet.py:336] Epoch_Train: 1052 cost= 23.983835
```

**Comment by MaybeShewill-CV** [comment]
@wb-finalking 这个我也不是很清楚==! sry

**Comment by wb-finalking** [comment]
@MaybeShewill-CV 我发现使用你的原始代码跑，loss也是一直在25左右，我数据就是按照你给的write_tfrecords准备的，但是char_dict_path和ord_map_dict_path是在代码中data/char_dict/中找的

**Comment by wb-finalking** [comment]
@MaybeShewill-CV 抱歉，你的原始代码没问题，我自己再找找问题

**Comment by MaybeShewill-CV** [comment]
@wb-finalking 好的 也欢迎分享出现的问题和解决方案:)

**Comment by MaybeShewill-CV** [comment]
@wb-finalking 有解决方案了吗

**Comment by wb-finalking** [comment]
@MaybeShewill-CV 目前问题已经解决了，使用tf.ctc_loss_v2可以解决输入是dense tensor的问题，但是需要给定每个输入序列的真实长度label_length。修改后训练loss收敛是一样的
