### ISSUE TITLE
Are the results from the pretrained model on real world images supposed to be poor?

### ISSUE THREAD

**Issue by IanPhilips** [MaybeShewill-CV/CRNN_Tensorflow#427]
Hello again! Because you've been so helpful I figured you might take a gander at this. I ran the command:   
`python test_shadownet.py --image_path ian_images/numbers.png --weights_path model/crnn_synth90k/shadownet.ckpt-80000 --char_dict_path data/char_dict/char_dict_en.json --ord_map_dict_path data/char_dict/ord_map_en.json`  

on this ![image](https://raw.githubusercontent.com/IanPhilips/images/main/numbers.png)  

and I got this results: `I0122 15:53:35.006593 1247 test_shadownet.py:132] Predict image numbers.png result: dmmees`  

I might not understand the ord_map and char_map relationship, is that it? Or is it that the pretrained network (on purely synthetic images) just not great at real world images?

**Comment by bunny66** [comment]
I am also getting pretty wrong results. digits are givings characters.

**Comment by MaybeShewill-CV** [comment]
@IanPhilips The pertained weights was trainned on synched dataset. You may train the model on your own dataset to see if the performance would become better:)

**Comment by dcdethan** [comment]
> 我也得到了非常错误的结果。数字给出字符。

请问您解决了吗
