### ISSUE TITLE
Train on other languages like Farsi

### ISSUE THREAD

**Issue by rzamarefat** [MaybeShewill-CV/CRNN_Tensorflow#428]
Firstly I thank you for this wonderful repo. I was wondering if it is possible to train this on some other languages whose style is in essence cursive. By that I mean, for instance Farsi is a language in which the characters of a word are all connected to each other. Thanks in advance

**Comment by MaybeShewill-CV** [comment]
@rzamarefat In my opinion it's worthing trying. Those words or sentences will be processed into a sequence features no matter they are connected to each other or not. But I have to say it will be much more difficult than English or Chinese:)
