### ISSUE TITLE
自己训练的模型预测结果完全不对

### ISSUE THREAD

**Issue by dcdethan** [MaybeShewill-CV/CRNN_Tensorflow#429]
您好，感谢您杰出的工作
现在有这样的问题，我训练的是crnn_synth90k官方数据集，损失停留在1左右不下降，并且预测结果完全不对，大概是什么原因呢？
![1622689072(1)](https://user-images.githubusercontent.com/29277128/120580365-a6890e00-c45b-11eb-9472-b08c9dd7b3fa.jpg)
![1622689376(1)](https://user-images.githubusercontent.com/29277128/120580374-abe65880-c45b-11eb-9d97-f9aef47c40c5.jpg)

**Comment by dcdethan** [comment]
测试图片如下
![test_01](https://user-images.githubusercontent.com/29277128/120580801-5cecf300-c45c-11eb-958b-b6f460ead476.jpg)

**Comment by MaybeShewill-CV** [comment]
@dcdethan 训练和预测使用的char_dict文件看下是不是不一致:)

**Comment by dcdethan** [comment]
> @dcdethan 训练和预测使用的char_dict文件看下是不是不一致:)

好的，我去看一下，谢谢回复。

**Comment by dcdethan** [comment]
已解决，参考
#431
