### ISSUE TITLE
python tools/test_shadownet.py --weights_path ./model/crnn_synth90k --char_dict_path ./data/test_images/char_dict/char_dict_en.json --ord_map_dict_path ./data/test_images/char_dict/ord_map_en.json --visualize 1

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [MaybeShewill-CV/CRNN_Tensorflow#430]
This probably means that you are not using fork to start your
    child processes and you have forgotten to use the proper idiom
    in the main module:

        if __name__ == '__main__':
            freeze_support()
            ...

    The "freeze_support()" line can be omitted if the program
    is not going to be frozen to produce an executable.

**Comment by NarasimmanSaravana1994** [comment]
@MaybeShewill-CV  please update the code for multi process in github...

**Comment by MaybeShewill-CV** [comment]
@NarasimmanSaravana1994 Maybe it's not necessary to add this:)
