### ISSUE TITLE
evaluate_shadownet.py 发现标签不正确的问题

### ISSUE THREAD

**Issue by dcdethan** [MaybeShewill-CV/CRNN_Tensorflow#431]
您好，我在执行evaluate_shadownet.py文件时，发现tfrecord的gt label是错的，请问您知道是什么原因引起的吗，我仔细检查了自己的编解码json文件，引入的没有问题。
![565de522bb07605d3784592ac957974](https://user-images.githubusercontent.com/29277128/120986284-01e63380-c7af-11eb-8471-531832065eaf.png)

**Comment by dcdethan** [comment]
#429 
这个问题也是由于这里引起的

**Comment by dcdethan** [comment]
此问题是由于tfrecord写入的时候使用的编解码文件和训练时候不一致导致的，感谢作者的耐心回复。

**Comment by dcdethan** [comment]
此问题是由于tfrecord写入的时候使用的编解码文件和训练时候不一致导致的，感谢作者wechat上耐心回复。

**Comment by stoneyang** [comment]
> 此问题是由于tfrecord写入的时候使用的编解码文件和训练时候不一致导致的，感谢作者wechat上耐心回复。

所以到底是啥原因？编码为何不同？如何确保相同？这个问题的解决办法是不是应该给出来，谢谢：@MaybeShewill-CV @dcdethan

**Comment by dcdethan** [comment]
> > 此问题是由于tfrecord写入的时候使用的编解码文件和训练时候不一致导致的，感谢作者wechat上耐心回复。
> 
> 所以到底是啥原因？编码为何不同？如何确保相同？这个问题的解决办法是不是应该给出来，谢谢：@MaybeShewill-CV @dcdethan

应该训练的时候指定编解码文件，指定成和tfrecord使用的编解码文件一致，如果不指定就会默认生成新的编解码文件。不知道解释清楚没有
