### ISSUE TITLE
the predict text is longer than the labeled text

### ISSUE THREAD

**Issue by SharonJin422** [MaybeShewill-CV/CRNN_Tensorflow#432]
Hello,  I  got a problem that the predict text is longer than the labeled text by non-sense words jointed the corrected words. What reasons may cause that?

I  set the max seq_len to 128,  I am not sure if it's that reason.

**Comment by MaybeShewill-CV** [comment]
@SharonJin422 Try to reduce seq_len

**Comment by SharonJin422** [comment]
Hello, I have taken contrast tests,  with input size = [32, 512], and the max time step will be 128,but set different seq_len:
1)seq_len = 64
2) seq_len = 15

I find that the first test has more accurate predictions than the second, but i cannot explain what cause this, do you have any idea?

**Comment by MaybeShewill-CV** [comment]
@SharonJin422 You may look up something relative to ctc:)

**Comment by SharonJin422** [comment]
thanks, i finally figure out that it's the learning rate set too large.

**Comment by MaybeShewill-CV** [comment]
@SharonJin422 welcome:)
