### ISSUE TITLE
训练所使用的数据集

### ISSUE THREAD

**Issue by huahuabai** [MaybeShewill-CV/CRNN_Tensorflow#440]

**Comment by huahuabai** [comment]
请问您训练时所使用的数据集是什么呢

**Comment by MaybeShewill-CV** [comment]
@huahuabai 就是合成的synth_90k数据集：）

**Comment by huahuabai** [comment]
> @huahuabai 就是合成的synth_90k数据集：）
抱歉没有仔细读您的项目介绍，除此之外请问您有无在其他数据集如：ICDAR相关数据集上进行测评呢

**Comment by MaybeShewill-CV** [comment]
@huahuabai ICDAR之前做过，不过时间太久了，具体指标记不清楚了。有空的话重新做个模型放上来:)
