### ISSUE TITLE
该如何对其他数据集进行测试？

### ISSUE THREAD

**Issue by huahuabai** [MaybeShewill-CV/CRNN_Tensorflow#442]
我尝试使用evaluate_shadownet.py对synth数据集进行测试，使用
![image](https://user-images.githubusercontent.com/55180640/155454675-39db9a83-c68a-493b-9f4f-4132065fa859.png)
出现加载权重失败的问题，如图，对此我按照网上相关的更改您提供的第8W次的data文件为ckpt但仍然未解决
![image](https://user-images.githubusercontent.com/55180640/155454942-2864bb4f-8721-48ac-b214-4629c1ec04a1.png)
下面是我存放权重文件的地址
![image](https://user-images.githubusercontent.com/55180640/155454529-e662c6a9-6cc9-4d65-851b-b39e8122b1ee.png)

除此之外，我也想请教您，针对比如icdar类的数据如果要进行测试，我是否先应该将其利用您的write_tfrecords.py文件将其转换之后再进行test呢

**Comment by MaybeShewill-CV** [comment]
@huahuabai 1.检查下载的模型文件是不是正确的。2.检查代码是不是最新的。3.检查tensorflow版本：）
