### ISSUE TITLE
中文识别问题

### ISSUE THREAD

**Issue by LvJC** [MaybeShewill-CV/CRNN_Tensorflow#50]
@TJCVRS 
您好，目前预训练的模型只是在英文合成字符的数据库上进行的吗？因为我试着用中文图片去测试，发现并不能识别。但是在您的README里，却有演示中文识别的例子。

**Comment by LXLun** [comment]
你应该download那个中文分支

**Comment by TJCVRS** [comment]
@LvJC 你可以切换分支试试看哈

**Comment by LvJC** [comment]
@TJCVRS but what's the correct model/weight path? 
When I set weight path = 'model/shadownet/chinese_two_five_merge/shadownet_2018-03-02-14-53-59.ckpt-6000', it reported error as followed:
W tensorflow/core/framework/op_kernel.cc:1192] Data loss: not an sstable (bad magic number)

**Comment by LvJC** [comment]
@TJCVRS 检查了一下`chinese_two_five_merge`里面的文件只有100来字节，而上层文件夹里的文件都是100M左右，是不是我不会用？可否教一下

**Comment by zhaohandd** [comment]
@LvJC  the same error! Don't know how to solve the problem! Do you solve the problem??

**Comment by LvJC** [comment]
@zhaohandd absolutely not!!!

**Comment by phybrain** [comment]
估计作者把模型 或什么 和英文的弄错了有问题

**Comment by LvJC** [comment]
@phybrain 你是不是也不行

**Comment by bignwei1029** [comment]
@TJCVRS 切换分之后，chinese_two_five_merge里面的没有模型，请重新上传一下，谢谢！

**Comment by zhaohandd** [comment]
@TJCVRS 中文识别版本模型确实有问题，参数匹配不上，请问有时间帮忙看看吗

**Comment by JungleStars** [comment]
@MaybeShewill-CV 可以传到百度云上吗

**Comment by MaybeShewill-CV** [comment]
@JungleStars 暂时不能上传 能上传了会上传到dropbox上的
