### ISSUE TITLE
charsets error

### ISSUE THREAD

**Issue by ccnankai** [MaybeShewill-CV/CRNN_Tensorflow#62]
你好， @TJCVRS 

我就测试下程序，char_dict数字和大写英文字母，  训练集只有两张图片，
python tools/train_shadownet.py --dataset_dir /Users/leo/Desktop/tfrecord1 
![image](https://user-images.githubusercontent.com/33537489/38725383-c5e13e44-3f39-11e8-83f7-d036d7877881.png)

会有下面key error ,  请问如果改换字符集 ，还要的改其他地方吗？字符集一共才36行。   搞了好久没明白，  先谢过了。

**Comment by mdbenito** [comment]
Without translating the chinese (sorry) it seems you are training on a different dataset with different charset. You need to regenerate it with `write_text_features.py`.

**Comment by ccnankai** [comment]
@mdbenito   thank you very much.
