### ISSUE TITLE
中文训练cost下降不了

### ISSUE THREAD

**Issue by hanglu** [MaybeShewill-CV/CRNN_Tensorflow#64]
作者您好，我用3700多的中文字符训练集 训练模型，发现 训练几个小时后 cost 到50多就不下降了，然后把batch 改大 ，然后训练到cost 为30之后又不下降了。请问你出现过类似的问题吗？3700个类别会不会太多了，所以会产生这个问题？ 我之前之用了100个中文做实验，效果挺好的。

**Comment by haneSier** [comment]
hello , hanglu, can you share your chinese char train models with me?(kinhanesier@163.com）

**Comment by mialrr** [comment]
我的也是这个问题，6000类别  lose就是不降

**Comment by mialrr** [comment]
@hanglu   你修改学习率试试  我发现有些改善，之前版主可能没有测试那么多分类，所有我觉得可能是学习率问题导致的   个人猜测，毕竟小的分类上面是可以的。

**Comment by mialrr** [comment]
![_20180522130633](https://user-images.githubusercontent.com/19602341/40344213-5cf19fae-5dc6-11e8-8eb8-870d1de226e7.png)

**Comment by Mr-zihao** [comment]
请问您用的是什么中文数据集

**Comment by Mr-zihao** [comment]
前期训练很容易收敛到局部最小，建议你先隔一些epoch降低学习率，等到收敛到局部最小时（我的是20），再调大学习率让他跳出局部最小，会好一些。

**Comment by xuenhappy** [comment]
set exponential_decay staircase=False and use this settings
__C.TRAIN.LEARNING_RATE = 1.0
__C.TRAIN.LR_DECAY_STEPS = 25000
__C.TRAIN.LR_DECAY_RATE = 0.1

**Comment by Sierkinhane** [comment]
我用训练pytorch 实现的crnn 中文识别（不定长）准确率能达到97.8%

**Comment by Sierkinhane** [comment]
我用六千多个分类，收敛的也很快

**Comment by Lemonyue** [comment]
@Sierkinhanen您好，请问您能提供一下中文模型完整代码和数据集吗？如果能收到回复将感激不尽，谢谢！2953143236@qq.com

**Comment by haneSier** [comment]
@Lemonyue我的 github 仓库有，训练集在我的博客上有链接

**Comment by haneSier** [comment]
https://github.com/Sierkinhane

**Comment by Sierkinhane** [comment]
@Lemonyue https://blog.csdn.net/Sierkinhane/article/details/82857572

**Comment by Lemonyue** [comment]
@Sierkinhane 请问是中文、英文、数字、标点符号都可以识别吗？我看结果中好像是这样的

**Comment by haneSier** [comment]
嗯嗯，中文，英文单词，标点符号都有训练过

**Comment by Sierkinhane** [comment]
@MaybeShewill-CV thanks

**Comment by Lemonyue** [comment]
@haneSier 您好，请问中文、英文、数字、标点符号都是用同一个数据集训练的吗？都是用的那个360万数据集吗

**Comment by haneSier** [comment]
是的

**Comment by MaybeShewill-CV** [comment]
@haneSier The repo has been updated and I will upload a new model later:)
