### ISSUE TITLE
The category is more than 6000, GPU usage is almost 0, CPU single core 100%

### ISSUE THREAD

**Issue by mialrr** [MaybeShewill-CV/CRNN_Tensorflow#71]
The category is more than 6000, GPU usage is almost 0, CPU single core 100%

**Comment by mialrr** [comment]
类别大于6000个是gpu使用率几乎为0,cpu单核心100%

**Comment by TJCVRS** [comment]
@mialrr 训练过程可以关掉beam search试试看 我在本机训练的时候发现beam search很耗时。

**Comment by mialrr** [comment]
@TJCVRS 老大  关掉beam search  会不会导致不收敛？

**Comment by TJCVRS** [comment]
@mialrr beam search只是解码获取最终结果的一种方法和训练过程没有关系

**Comment by ryanwcyin** [comment]
@mdbenito Have you tried a bigger training batch size?

**Comment by mdbenito** [comment]
Yes, I've gone to sizes 1024 and beyond. The blocker is the CPU. For some reason I only get 2 jobs at 100% CPU usage no matter how high I set the job count for tensorflow and despite the fact that dozens of processes are spawned (I have a machine with 40 cores)

**Comment by xuenhappy** [comment]
注释tf.summary.scalar(name='Seq_Dist', tensor=sequence_dist)
以及ctc_beam_search_decoder可以提高速度

**Comment by mdbenito** [comment]
@xuenhappy I thought I had disabled computation of `sequence_dist` (I had removed it from the call to `sess.run()`), but thanks to your comment I just realised I had forgotten to disable the summary as well. 
So, after one run disabling decoding after this fix results in a ~40% speedup (not an average, no idea about variance ¯\_(ツ)_/¯ )
Thank you!
