### ISSUE TITLE
write_text_tfrecords.py

### ISSUE THREAD

**Issue by zhuliqian** [MaybeShewill-CV/CRNN_Tensorflow#92]
python tools/write_text_tfrecords.py --dataset_dir out/ --save_dir data/ --batch_size 1
Initialize the dataset provider ......
Dataset provider intialize complete
Start writing training tf records
  0%|                                                   | 0/475 [00:00<?, ?it/s]OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/imgwarp.cpp, line 3492

Traceback (most recent call last):
  File "tools/write_text_tfrecords.py", line 131, in <module>
    write_features(dataset_dir=args.dataset_dir, save_dir=args.save_dir, batch_size=args.batch_size)
  File "tools/write_text_tfrecords.py", line 71, in write_features
    train_images = [cv2.resize(tmp, (100, 32)) for tmp in train_images]
  File "tools/write_text_tfrecords.py", line 71, in <listcomp>
    train_images = [cv2.resize(tmp, (100, 32)) for tmp in train_images]
cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by MaybeShewill-CV** [comment]
@zhuliqian Please check if your image is not read correctly
