### ISSUE TITLE
Does the model support recognition of special characters also?

### ISSUE THREAD

**Issue by vinayakkailas** [MaybeShewill-CV/CRNN_Tensorflow#97]
I ran pretrained model of some images with text and special charecters like "," and "." It recognized text, but was not able to recognize special characters. I am trying to train the model for my own dataset which has a lot of special charcters along with text. What changes i should make in char_dict.json and ord_map.json

**Comment by vinayakkailas** [comment]
i have made changes taking the ASCII values of all special characters and updated the jsons. Hope it should work now

**Comment by Giribushan** [comment]
Working for me ..after updating the ascii values for those special characters in char_dict.json  ord_map.json
